### ISSUE TITLE
Model with no attention

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian-dev#101]
Is it possible to turn off attention with a command line flag, or does it need to be done in the code?

**Comment by tomekd** [comment]
You need to change the code.

The best solution is to add a new model (e.g. copy-paste from s2s) and change decoder in two places: in RNN (somewhere there: https://github.com/marian-nmt/marian-dev/blob/master/src/models/s2s.h#L204) and before gettings probs (https://github.com/marian-nmt/marian-dev/blob/master/src/models/s2s.h#L329)

**Comment by hieuhoang** [comment]
cheers

**Comment by hieuhoang** [comment]
oh, and is there a max pooling operator?

**Comment by tomekd** [comment]
https://github.com/marian-nmt/marian-dev/blob/master/src/graph/expression_operators.h#L109

**Comment by hieuhoang** [comment]
pushed out no-attention s2s class on separate branch. Not sure if it's correct but its training anyway.

So we're ultimately trying to replicate this model https://arxiv.org/abs/1704.04154
which uses max-pooling over the word embedding, instead of the final LSTM states. What do you think is the best way to implement this? I see 2 options:
   1. Create a copy of SingleLayerRNN class and change rnn.h 80 & 82 when applying the cells.
   2. Create a copy of FastLSTM class and change the apply methods to do max pooling. 
Though I can't figure of where the derivs are calculate in either option.

**Comment by hieuhoang** [comment]
init commit with segfaults https://github.com/marian-nmt/marian-dev/commit/85204a7a24acee785a0b12a7d9b1cde8004d317c
