### ISSUE TITLE
Name change for "dynamic-batching" option

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#110]
Hi,
In marian `dynamic-batching` means adaptive batch size based on sentence length. Recently a different meaning has emerged: automatic joining of training examples into batches. In order to avoid confusion we should change the name of our option. 

This options supersedes `--mini-batch N` with a constant batch size N, should we use `--mini-batch dynamic` to switch on the adaptive behaviour? Any other suggestions?

**Comment by lparam** [comment]
I think use `--mini-batch 0` is more clearer.
Options value use different type will cause confusion.

**Comment by emjotde** [comment]
I am thinking about `--mini-batch-fit` as a boolean argument.
