### ISSUE TITLE
Binary for vocabulary creation

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#113]
Add a standalone binary that takes data on stdin and outputs a yaml vocabulary on stdout. Possible name `marian-voc` ?

Should also take an optional parameter `--max-vocab N` and generate only N most common vocabulary items. Generate all if unspecified.

**Comment by snukky** [comment]
Added a simple `marian-vocab` command, which takes two positional arguments:

    ./build/marian-vocab <corpus-path> <vocab-path>

**Comment by emjotde** [comment]
STDIN might be better:

``
cat file1 ... fileN | marian-vocab > vocab.yml
``

**Comment by tomekd** [comment]
btw. isn't it a good idea to add vocab files to model?

**Comment by snukky** [comment]
Implemented.
```
Usage: ./marian-vocab [options]

Allowed options:
  --max-size arg (=0)   Generate only  arg  most common vocabulary items
  -h [ --help ]         Print this message and exit
```

**Comment by emjotde** [comment]
in `develop` ? I am not sure we need a `develop` branch in a `develop` repo :) Seems redundant.

**Comment by snukky** [comment]
In `master` now.

**Comment by cshanbo** [comment]
Hi all,
I did some test with `marian` and it's awesome! Thank you for your excellent work.
But still, I think there's something we could do to make it better. 
For example, it might be better to provide detailed information in `marian-vocab` binary, like the parameter informations.
Maybe something like:
```
Usage: ./marian-vocab [options]
Usage: ./marian-vocab train.src train.tgt
Allowed options:
  -m [ --max-size ] arg (=0) Generate only  arg  most common vocabulary items
  -h [ --help ]              Print this message and exit

```

**Comment by emjotde** [comment]
Hi,
thanks.

`marian-vocab` is meant to read from `stdin`. What do you mean?

```
cat file1 file2 file3 ... | marian-vocab > vocab.txt
```

**Comment by cshanbo** [comment]
Yes, I think it's better to tell others that `marian-vocab` reads from `stdin` and writes to `stdout` by whatever means. 

Maybe one line in the help information like the following is enough: 
`Usage: ./marian-vocab < input.data > vocab.txt`

**Comment by emjotde** [comment]
Ah, ok. That makes sense.
