### ISSUE TITLE
Add unit tests for all GPU based kernels and functions

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#125]
I am adding dynamic shapes to marian and changing dimension order to match that from Numpy. Since this requires a lot of changes in many places, we need unit tests for graph operations and GPU based function. 

I will start with implementing a number of unit tests for graph based operators.

**Comment by hieuhoang** [comment]
the best thing you can do is add lots of regression tests based on problem models that have been reported by people using the toolkit. It maintains the overall integrity of the system and covers things you wouldn't have thought about. Thats how I stablised amun

**Comment by emjotde** [comment]
I currently need this for something different. Changing the organization of dimensions is such a deep cutting change that I need to make sure I does not mess up all the computation. Hence I now need lots of small low-level tests. If only to pin-point which operations I still have to modify to work with the new code.

**Comment by snukky** [comment]
@hieuhoang: unit tests and regression tests are complementary.
