### ISSUE TITLE
Should we turn synchronous SGD on by default?

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#129]
I have some hints that asynchronous SGD seems to suffer in terms of quality and convergence on GPUs with large amount of RAM with large mini-batch training. Synchronous SGD does not have this problem, but is a bit slower. 

Should we turn async into the optional behaviour for people who know what they are doing and set sync to be the default?

There is the currently unconfirmed case of issue #128 and I have some results that the Google Transformer model stays more than 1 BLEU point behind when trained with async instead of sync. The same seems to be true for Edinburgh's deep WMT17 models, which reach lower CE with sync.

**Comment by kpu** [comment]
I think we can do a better job at balancing work than we are currently, which would improve sync speed.

**Comment by emjotde** [comment]
Speed is one aspect, but sync sgd is bascially fool proof. If it works on a single GPU it will work with sync. All the fancy asynchronous methods may blow up into your face with unexpected hyperparameters.

**Comment by obo** [comment]
I haven't compared it head to head but I followed your recommendations and used synchronous only, which worked very well. I'd recommend to turn in on by default.

**Comment by emjotde** [comment]
Yes... ironically sync SGD also seems to scale waaaay better than async across multiple GPUs with near linear improvements in terms of words/sec (but not necessarily in convergence vs. number of epochs).

I am starting to think async might just be asking for trouble when doing anything that's not a shallow GRU model.
