### ISSUE TITLE
the result of marian nematus on C2E

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#136]
when i compare the Chinese to English translation, i found marian's translation will miss some words,i will give some examples. the corpus is the same, and the result of marian is both contains the type of amun and s2s and epoches exceed ten.
1.
source sentence: 那 不 是 我们 部门 处理 的 事 。
result of nematus : that 's   not what we 're dealing with .
result of marian : that 's   not our department .
2.
source sentence: 是 与 昨天 发送 的 电子 邮件 相关 的 资料 。
result of nematus:  information   relating to e-mail sent yesterday .
result of marian: is   related to the e-mail sent yesterday .
3. (i fee the expression of nematus will be better myself)
source sentence:下班 之后 ， 想 喝 一 杯 吗 ？
result of nematus: would   you like a drink after work ?
result of marian:  want a   drink after work ?

**Comment by 520jefferson** [comment]
when  translating i set
-n 1 
--layer-normalization 
it seems better than before , bleu a litter lower but meter a litter higher.

**Comment by emjotde** [comment]
These are different model files?

**Comment by 520jefferson** [comment]
Yes,there are different.

**Comment by emjotde** [comment]
So what's the total BLEU and METEOR score for both?

**Comment by 520jefferson** [comment]
marian-dev s2s before: 0.4188 | 0.60498 
marian-dev s2s after   : 0.4113 | 0.620729 
same model

**Comment by emjotde** [comment]
And for nematus?

**Comment by 520jefferson** [comment]
Add in my  last comment

**Comment by emjotde** [comment]
So everything is fine. You will get different trainslations for different models if they have been trained from scratch, that's normal. If you trained another nematus model with new randomly initialized weights it would also produce different translation. That's why ensembling works.
