### ISSUE TITLE
Python's incredibly annoying unicode breaks client_example.py

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#137]
The shebang at the top of client_example.py doesn't specify a version.  
``#!/usr/bin/env python``
but if it's meant to run with python2, then the line from sys.stdin needs to be decoded: ``batch += line.decode('utf-8')``
Of course that breaks python3.

**Comment by alvations** [comment]
Using `from __future__ import unicode_literals` may solve the problem. But that'll will enforce unicode for all marian input; and that's not a bad thing. I haven't seen non-unicode encoding for new datasets for the past 1-2 years.

**Comment by alvations** [comment]
Using `from __future__ import unicode_literals` may solve some unicode problem. 

But that'll will enforce unicode for all marian input; and that's not a bad thing. I haven't seen non-unicode encoding for new datasets for the past 1-2 years.

Using `six` would be one of the solution to support Python 2 and Python 3 code without the pain: http://six.readthedocs.io 

Although that'll add another dependency, it's one of the must-have dependencies text processing Python libraries without lots of Python version checking and if-else code.

**Comment by snukky** [comment]
I couldn't make it working with `six`, so added stupid `if-else`.
