### ISSUE TITLE
about marian-dev

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#140]
First, i build marian-dev after i delete tcmalloc_minimal in CMakefile.txt. And i build successed, then i can start the training process. It can work well without tcmalloc_minimal ?

Second,  whether the NaN and lr is stability enough in marian-master,then i can used marian-master directly ?

Third, when i train with nematus and marian-dev. I get the bleu and meter in deep network .
i find maybe nematus will be  bleu:52 meter:62 ,but marian will be bleu:53 meter:61  ,(when i set -n 1 --layer-normalization)bleu:51 meter:63. whether Nematus blance the bleu and meter well ? i just guess
@emjotde

**Comment by emjotde** [comment]
Hi,
1) removed tcmalloc_minimal, that was my mistake from local testing. tcmalloc makes translation a bit faster, but its purely optional. 

2) Yes, marian is now updated to point to the same revision as marian-dev. This can change in the future again. 

3) I don't quite understand. When you train models repeatedly you will always get small fluctuations. The differences you report do not seem to be something worth worrying about. 

Apart from that I found METEOR to be a rather weak metric and not very trustworthy. It's interesting to see that even the authors of METEOR do not report METEOR results in their papers anymore :)

**Comment by 520jefferson** [comment]
Thanks for you  patiently reply. How to  judge the result as to you, BLEU , MOS?

**Comment by emjotde** [comment]
No problem. For questions that aren't really bugs it might be better to use the google group marian-nmt@googlegroups.com, maybe others will join a discussion there. 

I usually rely on BLEU, at least with BLEU it is easy to understand what the metric means. METEOR was always a black box for me. As for MOS, that's a lot of work.
