### ISSUE TITLE
how can i get the  n-best result 

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#143]
Hi, how can i get the n best sentences ,when i input the source sentence.

**Comment by emjotde** [comment]
During translation? Try 

```
--n-best --beam-size 10
```

That will give you an n-best list of the size of the beam.

**Comment by 520jefferson** [comment]
I mean when i input a source sentence.It will return 5 ( maybe others) target sentece according to the overall score ,as follows:
source: It's a nice day today
target：
今天天气不错
今天天气很好
今天气候很好
今天气温很好
今天天气真棒

There will be five sentences to be return when i input a sentence.

**Comment by emjotde** [comment]
That's what n-best is doing, just with some more information. You can extract the translation from that with a python script or similar things. There is no mode for only outputting raw n-best sentences.

**Comment by 520jefferson** [comment]
Thanks a lot ,I see the n-best's result file . I am confused by the log in  screen .

**Comment by emjotde** [comment]
You can disable logging entirely by `--quiet` or just logging of the translations by `--quiet-translation`.

**Comment by 520jefferson** [comment]
Okay, thanks for remind.
