### ISSUE TITLE
Add regression tests for vocabulary creation and model permissions

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#144]
Would be good to have regression tests that cover the following situations:

## Vocabularies

Training:
* If no vocabulary provided, create or load vocab for trainset with .yml suffix, check write permissions
* If vocab path provided, load or create, again check existence and permissions. 

Translation and rescoring:
* If no vocabulary provided, abort.
* If vocab path provided, check existence and load. 

## Model

Training:
* Check if write permission, take into account different types of paths (no path, relative, absolute)

Translation and rescoring:
* Check if model exists.

**Comment by emjotde** [comment]
Should protect against #139

**Comment by snukky** [comment]
I think I test most of the cases with regression tests here: https://github.com/marian-nmt/marian-regression-tests/tree/master/tests/interface, but I'll wait with closing the issue until GPU on the machine with Jenkins is free and ensure that all tests pass.
