### ISSUE TITLE
docker images fail to build

### ISSUE THREAD

**Issue by aoboturov** [marian-nmt/marian-dev#162]
Try to build with gcc 4.9, 5 and 6. Have the following error on all combinations:

`c++: internal compiler error: Killed (program cc1plus)`

Both GPU and CPU versions fail.

**Comment by emjotde** [comment]
We have docker images?

**Comment by aoboturov** [comment]
Sorry. I meant to open it for the `marian` project.

**Comment by emjotde** [comment]
That's fine. I am just not aware of having docker images in https://github.com/marian-nmt/marian either.

**Comment by aoboturov** [comment]
@emjotde could you either it or should I re-create it there?

**Comment by aoboturov** [comment]
https://github.com/marian-nmt/marian/tree/master/scripts/docker

**Comment by emjotde** [comment]
Ah. This is in `contrib`, so potentially out-of-date, not really supported by us, or even just junk. Let's see if I can track down the original author.

**Comment by emjotde** [comment]
Oh. Not in contrib. Sorry. OK, re-open this in `marian`. We will take a look.

**Comment by aoboturov** [comment]
https://github.com/marian-nmt/marian/issues/153

**Comment by alvations** [comment]
BTW, the original author is @natgillin ;P
