### ISSUE TITLE
Empty outputs = out-of-memory (main RAM); Please report out-of-memory if allocation fails.

### ISSUE THREAD

**Issue by obo** [marian-nmt/marian-dev#166]
Marian apparently does not check the return value of malloc and friends. As a result, if your system limits memory consumption in some way, or if you run out of memory, you will get:

a) plain segfault in training
b) empty outputs in decoding (the number of sentences will match, so it is particularly hard to diagnose the problem)

I don't think it would be a too big performance penalty to check the value and die with a clarifying message.

**Comment by emjotde** [comment]
The problem is exception propagation through threads. We should just do a proper std::abort() as we have for all other errors. Currently it probably throws exceptions which kill the thread, but do not get through to the parent process.

**Comment by obo** [comment]
(In training -- or corpus shuffling specifically -- it's a plain segfault, no exception.)

----- Original Message -----
> From: "Marcin Junczys-Dowmunt" <notifications@github.com>
> To: "marian-nmt/marian-dev" <marian-dev@noreply.github.com>
> Cc: "Ondrej Bojar" <bojar@ufal.mff.cuni.cz>, "Author" <author@noreply.github.com>
> Sent: Monday, 22 January, 2018 23:34:07
> Subject: Re: [marian-nmt/marian-dev] Empty outputs = out-of-memory (main RAM); Please report out-of-memory if allocation
> fails. (#166)

> The problem is exception propagation through threads. We should just do a proper
> std::abort() as we have for all other errors. Currently it probably throws
> exceptions which kill the thread, but do not get through to the parent process.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/marian-nmt/marian-dev/issues/166#issuecomment-359593770

-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by emjotde** [comment]
Probably secondary to a thrown but not propagated std::bad_alloc. It just vanishes and leaves things unfinished, potentially undefined. 

What was the RAM limit you had on your machine?

**Comment by obo** [comment]
It was just 6 GB for both the decoding and the training troubles. It was never observed on other machines, just this one suddenly started observing it.

22. ledna 2018 23:59:35 SEČ, Marcin Junczys-Dowmunt <notifications@github.com> napsal:
>Probably secondary to a thrown but not propagated std::bad_alloc. It
>just vanishes and leaves things unfinished, potentially undefined. 
>
>What was the RAM limit you had on your machine?


-- 
Ondrej Bojar (mailto:obo@cuni.cz / bojar@ufal.mff.cuni.cz)
http://www.cuni.cz/~obo

**Comment by emjotde** [comment]
I would expect 6GB to be more than enough for decoding. Not surprised about the training.

**Comment by emjotde** [comment]
@obo regardless of the exception, you can now use large corpora with little RAM: #148

**Comment by emjotde** [comment]
This should work now, exceptions should be caught and reported.
