### ISSUE TITLE
Allow to specify --threads or diable multithreading completely

### ISSUE THREAD

**Issue by obo** [marian-nmt/marian-dev#167]
For debugging purposes, it would be good to be able to disable multithreading, or limit the number of threads to 1.
I don't see such a switch among the command-line parameters.

**Comment by emjotde** [comment]
If I am not wrong, running it on one device should do the trick, not sure though. 

Anyway, we have no reasons to allow to set --threads as we do not do anything that's multi-threaded that should be controlled by the user. We only use mult-threading for multi-gpu training/translation where one thread gets control over one gpu. The user has no business there.  

A compile-time option might be a better way to do this. I admit whenever I was debugging thread related stuff I would just switch it off directly in code.

**Comment by emjotde** [comment]
Won't fix at the moment. Ping this if anyone else encounters problems with that.
