### ISSUE TITLE
CPU memory use

### ISSUE THREAD

**Issue by phikoehn** [marian-nmt/marian-dev#168]
One question: I am running the decoder with an ensemble of 4 models (each is 852MB). The GPU reports 4111MiB memory use, but the process also uses 10GB of CPU memory. What is all this additional RAM used for?

**Comment by emjotde** [comment]
Hm. Need to take a look at that. It loads the models into RAM first and transfers that to the GPU, not sure what else is there.

**Comment by phikoehn** [comment]
There may be also some memory leaking going on for long running processes (1 week or more).

My friendly cluster sends me emails like this:

Killed process marian (PID: 193038) of user pkoehn
User was using total 21844M, and had requested ram_free=9000M;
the process we killed was using 21032M

**Comment by emjotde** [comment]
I am looking into this now. I have been running a Transformer model to translate by now about 16 million sentences using 8 GPUs and I am seeing no leaking. But the base memory usage is indeed high, about 9GB. No good reason for that.

**Comment by emjotde** [comment]
Take a look now. It's still not ideal, for GPU-based translation there should in fact be barely any CPU memory usage, but it should be a lot better. Apparently using lambda functions with captures is not a great idea.

**Comment by emjotde** [comment]
Cannot confirm the memory leak though.

**Comment by emjotde** [comment]
Closing this for now, feel free to reopen if it still bugs you.
