### ISSUE TITLE
Make sqlite shuffling take a seed

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#173]
Currently shuffling is done by `select * from lines order by random()`. The function `random()` does not take a seed and this results in different non-reproducible shuffles. For certain experimental settings this is not great and if we later want to have a pointer to data in order to resume training we need seeds. If I am not wrong this can be solved by creating a new function a la `random()` which will take a seed. It seems the sqlite C/C++ interface allows to add C/C++ functions to the interface which should make this easy.

**Comment by snukky** [comment]
Added with these commits: https://github.com/marian-nmt/marian-dev/compare/dca77499c6c09a07df1cea9d79d0b3f188309dd3...03d9fad5e1cee923a82be25a5fbdb168f71fcc32
