### ISSUE TITLE
Parsing of devices fails under g++ version 4.8.4

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#183]
Parsing of devices fails under g++ version 4.8.4 with a std::regex_error. Works fine for 4.9.2 and above. Should we fix that or change requirements to at least 4.9? Or better >5?

**Comment by snukky** [comment]
`<regex>` is used only for validating the format of `--devices`. We may just display a warning if g++ < 4.9.0, or use regular expressions from Boost.
