### ISSUE TITLE
commit emails

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian-dev#188]
At the moment, only commits from people who have subscribed to the the commit mailing list are sent.

noreply@github.com needs to be a member of the mailing list. Tested with amunmt-commits but I'm not an admin on marian-commits so can't test with current setup

**Comment by emjotde** [comment]
Uhm, so I just should make you an admin of the google group, right?

**Comment by hieuhoang** [comment]
might as well

**Comment by emjotde** [comment]
done.
