### ISSUE TITLE
model iterations files

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian-dev#189]
is keeping all the iteration files (model.iter10000.npz, model.iter20000.npz...) necessary? They take up quite a bit of space, important on rented servers

**Comment by snukky** [comment]
Check the `--overwrite` option.

**Comment by emjotde** [comment]
When validation is enabled with any metric I use that in tandem with `--keep-best`.

```
--valid-metrics perplexity translation 
--valid-set data/valid.src data/valid.trg 
--overwrite 
--keep-best
```

This results in then in one model per validation metric, i.e. `model.npz.best-translation.npz` that is updated whenever the metric improves.

**Comment by emjotde** [comment]
Unless we want to discuss if this should be the default behavior, I am closing this issue.

**Comment by hieuhoang** [comment]
so --overwrite should always be used in tandem with --keep-best when you have a validation set. And we still use the file model.npz once it's trained?

**Comment by kpu** [comment]
Is there a `--keep-best 4` when one wants to do model averaging/ensembling?

**Comment by emjotde** [comment]
@kpu there is not, was pondering to add that but decided against it. `--exponential-smoothing` works usually as good or better than checkpoint averaging in my experience. It basically checkpoint averaging on steroids.
