### ISSUE TITLE
Incompatabilities in Marian's multiplicative wrapper's implementation

### ISSUE THREAD

**Issue by rihardsk** [marian-nmt/marian-dev#193]
Amun and Marian have slightly different implementations for the multiplicative wrapper. [Amun adds an extra bias vector](https://github.com/marian-nmt/marian/blob/8536335da6fbb1c9a5da93409a585f42452303be/src/amun/gpu/dl4mt/multiplicative.h#L32) to the value that's derived from the context vector which would be equivalent doing this:
```c++
auto mstate = (xWm + bias) * sUm;
// instead of this
// auto mstate = xWm * sUm;
```
[here](https://github.com/marian-nmt/marian-dev/blob/3753573d3dea8e432bb10162353f2b3b01f02d65/src/rnn/cells.h#L672).

Can we bring both of the implementations in sync? Amun's implementation is more general (at least that's what I get when expanding these expressions on paper) so I'd prefer doing the above change in Marian while ensuring backward's compatibility in model loading by simply initializing the new `bias` matrix with zeros if it's not present.

After this we could support `mLSTM` and `mGRU` cell types in the `Amun` model type (I'll open a separate issue for this).

**Comment by emjotde** [comment]
I think no-one is using this apart from you guys. Feel free to modify it. I will be happy to accept a PR.

**Comment by hieuhoang** [comment]
yep. as long as the gru-based regression tests passes, do what you like with mLSTM. Noone even has your ttraining scripts
