### ISSUE TITLE
Supporting LSTM, GRU, and mLSTM and mGRU with the Amun model type

### ISSUE THREAD

**Issue by rihardsk** [marian-nmt/marian-dev#194]
Preconditions for this are [marian#161](https://github.com/marian-nmt/marian/issues/161) and #193 but afterwards this should be as simple as adding the multiplicative matrix names to the `Amun` <-> `s2s` mappings in [amun.h](https://github.com/marian-nmt/marian-dev/blob/3753573d3dea8e432bb10162353f2b3b01f02d65/src/models/amun.h#L47).

Does Marian do any kind of configuration yaml generation for Amun or anything else that I'm missing?

**Comment by emjotde** [comment]
It should, haven't looked at it for while. When training with `--type amun` it generates a `model.npz.amun.yml` config for the amun decoder. GRU should be supported by default. 

I am thinking how to approach this. @snukky added modifications to the GRU class in Marian to make it Nematus compatible. If we start adding more modifcations on top of that it will get messy soon. Maybe we should copy the Amun and Nematus specific cell types to their own cells, any thoughts @snukky?

**Comment by rihardsk** [comment]
I updated the mappings and I'm now able to train/save/load mLSTM models with `--type amun`. Translating with Amun spits out garbage though. It seems like [marian#161](https://github.com/marian-nmt/marian/issues/161) and #193 aren't the only incompatibilities.

One thing I found is that [Marian initializes decoder's output and cell states with the same value](https://github.com/marian-nmt/marian-dev/blob/059a45e661fc486d113120e5e601e33acfbe827f/src/models/s2s.h#L281) (am I seeing this right?), as opposed to Amun which sets the cell state to zeros and the output state to the value derived from decoder's outputs. Changing this in Amun didn't help though so there's something more going one there.

Btw, how do you run-time values in Marian to see what data are flowing through?

**Comment by emjotde** [comment]
Surround any expression you want to view with `debug(node, "A message")`. During inference it will show up. The display format can be modified in `src/tensor.h`.

**Comment by emjotde** [comment]
As for cell state init: the opposite actually, it initializes output and cell state to the averaged and mapped encoder state if an encoder is available. The zeros are only used for LMs without an encoder.

**Comment by emjotde** [comment]
Do we have that now?
