### ISSUE TITLE
plain-text vocabulary files

### ISSUE THREAD

**Issue by frankseide** [marian-nmt/marian-dev#200]
Marian uses YML as the format of vocabulary files, while it uses plain text for the corpus data itself. This is causing a problem, since YML requires valid UTF-8 strings, which is only a subset of what can be represented in an 8-bit corpus plain-text file.

I propose to alternatively allow to accept plain-text vocabulary files. This will allow Marian to support corpora encoded in any 8-bit encoding (Latin-1, GB2312, UTF-8 corpora with errors). It also makes it easy to create vocab files with tools external to Marian (`tr ' ' '\n' | sort -u`).

Current tested local implementation:
```
int Vocab::load(const std::string& vocabPath, int max) {
  bool isYaml = std::regex_search(vocabPath, std::regex(".yml$"));
  LOG(info, "[data] Loading vocabulary from {} file {}", isYaml ? "Yaml" : "text", vocabPath);
  ABORT_IF(!boost::filesystem::exists(vocabPath),
           "Vocabulary {} does not exits",
           vocabPath);

  std::map<std::string,Word> vocab;
  if (isYaml) // read from Yaml file
  {
    YAML::Node vocabNode = YAML::Load(InputFileStream(vocabPath));
    for(auto&& pair : vocabNode)
      vocab.insert({ pair.first.as<std::string>(), pair.second.as<Word>() });
  }
  else // read from plain text file
  {
    std::ifstream in(vocabPath);
    std::string line;
    while (std::getline(in, line))
      vocab.insert({ line, vocab.size() });
    ABORT_IF(in.bad(), "Vocabulary file {} could not be read", vocabPath);
  }

  std::unordered_set<Word> seenSpecial;

  for(auto&& pair : vocab) {
    auto str = pair.first;
    auto id = pair.second;
...
```

**Comment by emjotde** [comment]
I am conflicted about this. Apparently there is a way to force yaml-cpp to output pure ASCII and escape anything else. That would work for any encoding, provided the vocabulary was created with Marian or the vocabulary binary. 

```
emitter.SetOutputCharset(YAML::EscapeNonAscii);
```
