### ISSUE TITLE
Synchronous cross entropy is average of averages

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#201]
When configured to average perplexity at the word or sentence level, an average is taken within each GPU.  These averages are then averaged uniformly across GPUs.  It should be weighted by the number of words/sentences on each GPU, so that the entire result is an average over sentences.

**Comment by emjotde** [comment]
The number of sentences is equal for each sub-batch on each GPU, so here it should not matter. The number of words not quite, so here it could.That average of averages is only used during reporting, but it during accumulation of gradients we would see that, so we need to refine that a bit.

**Comment by emjotde** [comment]
out-dated.
