### ISSUE TITLE
Documentation: CPU

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#206]
Update https://marian-nmt.github.io/docs/ regarding what supports CPUs once it's ready.  

"marian-decoder: for GPU translation with models of all types"
"marian-server: a web-socket server providing GPU translation"
"amun: for CPU and GPU translation with Amun and certain Nematus models"

**Comment by kpu** [comment]
Should probably be raised on the website repo.

**Comment by 520jefferson** [comment]
@emjotde will  marian-decoder and marian-server support CPU translation ?  By the way, does marian support to be built under Windows environmen, like Win7？

**Comment by emjotde** [comment]
CPU translation with marian-decoder and server should already work with `--cpu-threads N`. 

Yes, there are plans for a Windows port, but I cannot really say yet when that is going to happen. Two to three months maybe?

**Comment by 520jefferson** [comment]
@emjotde  Considering the computing power of device(Android), how big the dimensions of transformer and word embedding are suitable ? Have you considered the use of half float instead of float training to  reduce the size of the model ?

**Comment by emjotde** [comment]
We do not really need to use it during training, only during inference. And yes, there is already a 16bit CPU matrix multiply in the current version of marian-dev. But as I said, this is so recent that we need to understand things first ourselves.
