### ISSUE TITLE
Neural network exchange formats?

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#207]
There are neural network specifications intended to be cross toolkit: https://onnx.ai/ https://www.khronos.org/nnef (of course there are two standards...).  Support them?

**Comment by emjotde** [comment]
ONNX has strong MS support, so for me the choice is easy. I personally do not have the man-power at the moment, but it is something to consider.

**Comment by emjotde** [comment]
ONNX in its current state does not seem to be RNN-ready, that is supposed to change with version 2.0, we could have some influence on that.

**Comment by emjotde** [comment]
Postponed until further notice.

**Comment by kpu** [comment]
https://github.com/intel/clDNN/ for Intel GPU support has LSTM and accepts ONNX...

**Comment by emjotde** [comment]
When I talked to people at MS who are contributing to the ONNX standard, the consensus was that encoder-decoder models are currently not possible.

**Comment by samru-rai** [comment]
After 2 years, are there any update on this issue?
