### ISSUE TITLE
Can't find the definition of the context vector size in the s2s model

### ISSUE THREAD

**Issue by Avmb** [marian-nmt/marian-dev#209]
In Nematus (and I suppose in the s2s model as well) the context vector produced by the attention has the same size as the encoder state, that is, twice the size of the encoder GRU states.

I want to change the attention mechanism so that it returns a larger context vector, how do I tell the decoder GRU cell the size of this vector?

**Comment by emjotde** [comment]
Hi Antonio.
Seeing your profile picture I want to shout "Look out, scary robot Yoko Ono is behind you!" :)

This is where the encoder state gets passed into the attention mechanism:
https://github.com/marian-nmt/marian-dev/blob/master/src/models/s2s.h#L217

And here inside the attention mechanism it asks for the context dimensions:
https://github.com/marian-nmt/marian-dev/blob/master/src/rnn/attention.h#L50

So you could say that it scales automatically and you do not need to pass an actual size. This should be true anywhere, also later for the output layers where we pass the aligned context vector into the output FFN.

**Comment by Avmb** [comment]
Hi Marcin,
I managed to outrun robot Yoko (not too difficult, since she doesn't walk) :)

Anyway, I'm trying to make GlobalAttention::apply() return an alignedSource with its last dimension larger than dimEncState (e.g. 3 times larger in my experiments)
https://github.com/marian-nmt/marian-dev/blob/master/src/rnn/attention.h#L138

But I get an error downstream:
[2018-03-13 18:22:39] Shapes shape=1x1x100x6144 size=614400 (2457600B) and shape=1x2048 size=2048 (8192B) cannot be broadcasted
Aborted from static marian::Shape marian::Shape::broadcast(const std::vector<_RealType>&) [with T = std::shared_ptr<marian::Chainable<std::shared_ptr<marian::TensorBase> > >] in /fs/meili0/amiceli/marian-multihead/src/common/shape.h: 184

I think that this size 6144 must somehow be passed to the constructor of the GRU cell so it can initialize an input matrix with the proper shape.

Also, how do I pass a command-line option to the constructor of GlobalAttention? I added it to config_parser.cpp but it does not appear in the options_ object.

**Comment by emjotde** [comment]
Can you recompile after `cmake .. -DCMAKE_BUILD_TYPE=Debug` and run a stack trace with gdb? Shape broadcasting is checked during model building, so it should tell us exactly where things fall apart. Will be easier to diagnose.

**Comment by Avmb** [comment]
I figured out what the problem was: I hadn't changed the GlobalAttention::dimOutput() method.

Now I still don't know how to pass a command-line argument to the constructor of GlobalAttention, the option_ object does not contain them.

**Comment by Avmb** [comment]
Never mind, I figured out.

**Comment by emjotde** [comment]
Oh, great, my favorite type of issue.
