### ISSUE TITLE
Can't load model from file

### ISSUE THREAD

**Issue by Avmb** [marian-nmt/marian-dev#211]
I can now train my model with parameter matrices of non-standard sizes, but when the decoder tries to load it I get:

[2018-03-18 17:02:31] Loading model from model/model-drtdec.npz.best-translation.npz
[2018-03-18 17:02:35] Requested shape shape=2048x2048 size=4194304 (16777216B) for existing parameter 'F0::decoder_cell2_W' does not match original shape shape=16384x2048 size=33554432 (134217728B)
Aborted from marian::Expr marian::ExpressionGraph::param(const string&, const marian::Shape&, const NodeInitializer&, bool) in /fs/meili0/amiceli/marian-multihead/src/graph/expression_graph.h: 220

**Comment by emjotde** [comment]
Can you check in python what the actual size of that parameter is inside the model file? Maybe this will tell us more.

**Comment by snukky** [comment]
You can use `/scripts/contrib/model_info.py` for that.

**Comment by Avmb** [comment]
The shape of the parameter in the saved .npz file is correct, the problem is that the decoder does not know the command-line option that I used during training which controls that shape, hence it tries to load a parameter of the default shape.

The original command line option does not appear in model/model-drtdec-multihop.npz.best-translation.npz.decoder.yml but it does appear in model/model-drtdec-multihop.npz.yml

**Comment by emjotde** [comment]
Ah, OK. 
That should be much easier. Can you point to the code that uses the parameter and what the name of the parameter is? Currently the parameter handling is quite messy and we have an issue where we plan to improved that, but there are about three places now where things need to be set correctly to work and propagate through all tools and models.

**Comment by Avmb** [comment]
I sent you an invite to my private repository

**Comment by Avmb** [comment]
I also added it here: https://github.com/marian-nmt/marian-dev/blob/master/src/models/encdec.h#L265
and it seems to be working.
