### ISSUE TITLE
Wrong model saved with exponential smoothing

### ISSUE THREAD

**Issue by spenkale** [marian-nmt/marian-dev#216]
There seems to be a bug when training on a single GPU with  exponential smoothing. This function ignores the argument and just saves the class model: https://github.com/marian-nmt/marian-dev/blob/a5656a7fa048cb1e45c42961e2b9caf5f9027453/src/training/graph_group_singleton.h#L74-L99

This might explain cases where devset output during training is different from decoding with the saved model like in this issue: https://github.com/marian-nmt/marian/issues/154

**Comment by emjotde** [comment]
Uh, that does indeed look suspicious.

**Comment by emjotde** [comment]
Thanks for spotting this.
