### ISSUE TITLE
server compile error

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian-dev#224]
the marian server gives the following compile error (on Ubuntu 16.04, gcc 5.4, boost 1.66, cuda 9.1):
   server_ws.hpp:181:7: error: invalid use of template-name ‘boost::asio::strand’ without an argument list
       asio::strand strand;
I think it's been fixed in marian-dev, but not marian proper. Any chance someone can update marian?

**Comment by emjotde** [comment]
I will take a look at that today. Probably I won't update the whole repo to current marian-dev, but at least fix the server.

**Comment by snukky** [comment]
After releasing v1.5, this should be fixed now, right?

**Comment by hieuhoang** [comment]
yep, looks ok
