### ISSUE TITLE
creating a batch with optimizer delay on sync SGD

### ISSUE THREAD

**Issue by afaji** [marian-nmt/marian-dev#225]
I'm referring to https://github.com/marian-nmt/marian-dev/blob/5ba6c776bb39ad5b3463e2122014bc8bfbc5379e/src/training/graph_group_sync.cpp#L45

So if we set an optimizer delay of T and mini-batch-fit on sync SGD on N GPUs, we will make one big batch and split them into N x T smaller batches, right?

When the delay is big enough, the actual batch sizes are becoming unstable and smaller than the expected, even after I increase the maxi-batch. I suggest instead of generating 1 very large batch and split them afterwards, we should generate T batches and accumulate the result. This should make things more stable. 

Might also apply on multi-GPU without delay. Should we just create N batches right away, instead of one big batch then split them up?

**Comment by emjotde** [comment]
The current way is much easier. It might be worth investigating why the results become unstable. I cannot see a good reason for this with increased maxi-batch size?

**Comment by emjotde** [comment]
Also, the current way gives identical results with a delay of 2 to actually having double the memory. We should aim for that as well.

**Comment by afaji** [comment]
delay of 2 with 4k maxi-batch:
`[2018-04-18 16:44:41] Ep. 1 : Up. 128 : Sen. 471715 : Cost 113.73 : Time 35.87s : 41215.04 words/s`

delay of 4 with 8k maxi-batch:
`[2018-04-20 04:43:45] Ep. 1 : Up. 128 : Sen. 946565 : Cost 144.60 : Time 34.75s : 38027.24 words/s : L.r. 4.5155e-04`

delay of 8 with 16k maxi-batch:
`[2018-04-20 06:06:39] Ep. 1 : Up. 128 : Sen. 1654270 : Cost 193.37 : Time 35.64s : 40021.29 words/s`

all of these was on 4 GPUs with workspace of 10GB (ro->en). Things starts to get unstable after asking a 80GB batch.

**Comment by emjotde** [comment]
I would guess you are running out of sentences you can put in the same bucket. I would try with a larger parallel corpus.

**Comment by afaji** [comment]
Maybe, but interestingly enough, this works on async SGD, 10 GB workspace + delay of 32 (giving the same 320 GB / batch):
`[2018-04-20 05:47:03] Ep. 1 : Up. 128 : Sen. 1865966 : Cost 344.63 : Time 31.41s : 47463.81 words/s`

The only difference is that in async SGD, we actually asked 32 x 10 GB batch size instead of 1 x 320 GB batch size.

**Comment by emjotde** [comment]
Yes, again, it's bucketing. We might do different buckets per GPU for sync sgd then.

**Comment by emjotde** [comment]
If you solve this, please make me reviewer of the pull request. This is important functionality.

**Comment by afaji** [comment]
nope. you can take over
