### ISSUE TITLE
Performance improvment: lazily zero gradient accumulation

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#229]
A little bird told me that changing the first += to = for the gradient summing makes things faster (~30%) for the transformer.

**Comment by emjotde** [comment]
Uhm, care to elaborate? I have no idea what that means :)

**Comment by kpu** [comment]
Which code is faster (in pseudocode)?
grads = 0
grads += a
grads += b

grads = a
grads += b

Add a bool flag to say if it should be zero, then change the first += to a =.

**Comment by emjotde** [comment]
But where in the code? Backwards function in the nodes? Gradient accumulation in sync?

**Comment by emjotde** [comment]
OK. I am starting to understand. Anywhere in the backwards functions (why did that have to be a riddle?). Is this just from leaving out `grads = 0` or is there something sinister about `+=`, too?

**Comment by kpu** [comment]
tensor_operators.cpp

**Comment by emjotde** [comment]
During backwards all the grads are initialized to 0 in one kernel call each. Which I just realized can be done in a single kernel call anyway. I am now wondering whether there is an advantage to not using `+=` .

**Comment by emjotde** [comment]
So. When I switch off `grad = 0` everywhere I get no improvement at all. Where would that come from then? It also cannot be `tensor_operators.cpp` because that's CPU code. There is a `*.cu` version. Can I haz a function name?

**Comment by emjotde** [comment]
Also is this 30% in total or 30% faster for a specific function call that takes up about 2%? :)

**Comment by emjotde** [comment]
OK, if this is CPU I leave it to you guys.
