### ISSUE TITLE
YAML device string parsing issues in multi-node training

### ISSUE THREAD

**Issue by jgwinnup** [marian-nmt/marian-dev#233]
Hi,

I'm attempting to use multi-node training per the notes on the website - we've built head with openmpi v 2.1.2. When specifying devices on command line to run on 4 nodes with 2 GPU each like:

```
--devices 0:0 1 1:0 1 2:0 1 3:0 1
```
I get a 'YAML::TypedBadConversion<unsigned long>'  error. I've also tried dumping out the config with the above flag and I get this in the device section:

```
devices:
  - 0:0
  - 1
  - 1:0
  - 1
  - 2:0
  - 1
  - 3:0
  - 1

```
When attempting to run with this dumped config, the parser complains about the colon in ' - 0:0'. Are there any hidden gotchas I'm missing?

**Comment by snukky** [comment]
Probably not tested after GPU and CPU backends were separated. Let me check.

**Comment by snukky** [comment]
Should be fixed now. Please feel free to open if it doesn't.

**Comment by ZJaume** [comment]
Could it be broken on version 1.8.0? I run myself this:
`--devices 0:0 1 1:0`
and obtained this:
```
devices:
  - 0:0
  - 1
  - 1:0
```

**Comment by snukky** [comment]
I guess this format is no longer supported since `--num-devices` has been introduced specifically for multi-node training.

**Comment by ZJaume** [comment]
So, how can I specifiy which gpus to be used in each node?
