### ISSUE TITLE
Running the python interface from example.py

### ISSUE THREAD

**Issue by StanczakDominik** [marian-nmt/marian-dev#246]
Hello!

I'm trying to run `scripts/python/example.py` from the current master to look into Marian's Python interface. As I understand it, the compilation process is supposed to produce something like a `libmariannmt.so` file to be imported here:

https://github.com/marian-nmt/marian-dev/blob/8fbfa6560f10fff295f1f1b53372e15ae3549fa4/scripts/python/example.py#L7

However, I dug through the CMakes and found nothing related to generating this file, except for a commented out portion:

https://github.com/marian-nmt/marian-dev/blob/8fbfa6560f10fff295f1f1b53372e15ae3549fa4/src/CMakeLists.txt#L149-L151

Interestingly, in marian-nmt/marian, there are some Python related lines in CMakes, for example here:

https://github.com/marian-nmt/marian/blob/8b4e705a38f53d0ebb721eb1161a2e456ebf3455/CMakeLists.txt#L106-L113

But I can't seem to find those here, in marian-dev.

Thus, the question: is this `example.py` script still possible to run somehow? Is it left-over legacy code? Am I missing something silly and obvious with respect to compilation?

Thank you for your time!

**Comment by snukky** [comment]
We used to have python bindings in Marian, but it was half-baked and required extra dependencies. Since we have C++ server, we decided to remove it. We just forgot to remove `example.py`, sorry.

Why do you need python bindings for?

**Comment by StanczakDominik** [comment]
I was looking into calling Marian from within Python and having an importable interface seemed really, really nice. It's a shame that it's gone, but I completely understand and agree with the point about keeping dependency numbers on the low end and having maintainable code. Thanks for your quick response!

**Comment by emjotde** [comment]
There never really was a proper Python interface. We rely on C++ as a iron principle :)
