### ISSUE TITLE
Adding Marian version to models

### ISSUE THREAD

**Issue by tomekd** [marian-nmt/marian-dev#25]
It's worth to keep Marian version in model files. This will be helpful in future when a model will be run on different version of Marian than it was trained.

**Comment by emjotde** [comment]
@tomekd @snukky @hieuhoang 
Should this just be a numeric value that we increase manually whenever a breaking change gets implemented?

**Comment by tomekd** [comment]
I can add git commit hash to the model.

**Comment by geovedi** [comment]
i'm suggesting the use of [semantic versioning](http://semver.org/) integrated with release tag so people can create distro package.

**Comment by snukky** [comment]
I also think that git commit hash won't work as a version number in that case. A better option would be adding a global versioning in CMake.

**Comment by snukky** [comment]
Project version is now available with `PROJECT_VERSION`. It uses tag versions if available.

**Comment by snukky** [comment]
Done.
