### ISSUE TITLE
CUDA memory access error

### ISSUE THREAD

**Issue by Avmb** [marian-nmt/marian-dev#250]
I'm implementing transformer-like log-bilinear attention heads in the s2s model [here](https://github.com/EdinburghNLP/marian-dev/blob/log-bilinear-attenton/src/rnn/attention.h), but I'm getting this error:

Error: an illegal memory access was encountered - /fs/meili0/amiceli/marian-multihead/src/tensors/gpu/algorithm.cu:41

the error occurs randomly either when the system is collecting minibatch statistics or within a couple minutes into training. It occurs both on one gpu or four. I can't reproduce it on cpu because I get a not implemented error.

It only occurs when I enable log-bilinear attention: [attentionBilinearLookup_](https://github.com/EdinburghNLP/marian-dev/blob/log-bilinear-attenton/src/rnn/attention.h#L68) set to true, possibly it is caused by this [bdot](https://github.com/EdinburghNLP/marian-dev/blob/log-bilinear-attenton/src/rnn/attention.h#L234) or the tensor manipulations around it (though the tensor shapes seem right).

Any idea what it is?

**Comment by Avmb** [comment]
ping @emjotde

**Comment by Avmb** [comment]
compiling with the -G flag given to NVCC and running with cuda-memcheck finds multiple errors all equal to this:

========= CUDA-MEMCHECK
========= Invalid __global__ read of size 4
=========     at 0x00001ba8 in /fs/meili0/amiceli/marian-multiheaded-merging/src/tensors/gpu/tensor_operators.cu:250:marian::gpu::gTransposeND(marian::functional::Tensor<float>, marian::functional::Tensor<float>, marian::functional::Array<int, unsigned long=4>)
=========     by thread (63,0,0) in block (6,0,0)
=========     Address 0x7ff4983d9380 is out of bounds

which is [here](https://github.com/marian-nmt/marian-dev/blob/master/src/tensors/gpu/tensor_operators.cu#L250)

**Comment by emjotde** [comment]
Might be indeed easier to debug on CPU. The not implemented error is due to missing MKL I think. Can you install MKL, recompile and try on the CPU? 

Did you implemented custom kernels?

**Comment by Avmb** [comment]
> Might be indeed easier to debug on CPU. The not implemented error is due to missing MKL I think. Can you install MKL, recompile and try on the CPU?

I managed to compile it and run it, but it seems to be taking forever to even get past the "Collecting statistics for batch fitting" phase. Any suggestions on how to use marian on cpu? I've just added  --cpu-threads 22 to the command line.

> Did you implemented custom kernels?

No.

**Comment by emjotde** [comment]
Oh right, don't use mini-batch-fit, set a constant mini-batch size, like 10 or even 1, just for debugging. It will skip the statistics phase and go into training. Maybe also reduce the model size and disp-freq to something smaller. It would try with a single CPU thread first. The multiple threads currently only do model replicas, similar to multi-gpu training.

**Comment by Avmb** [comment]
it doesn't seem to generate any error on cpu, but I'm not sure it's actually executing my code, because I have LOG macros in my code that should print something at each step, but I don't see these messages while I'm running on cpu, even though training is indeed progressing since I see the progress displays.

Does LOG work differently on cpu? Maybe it needs to be flushed somehow?

**Comment by Avmb** [comment]
Nope, LOG works, I running the wrong binary :) . Anyway, it still doesn't generate any error. I think there may be a bug in the gpu code, or if there is a bug in my code for some reason it only shows up on the gpu.

**Comment by snukky** [comment]
This is an old issue. Closing.
