### ISSUE TITLE
Getting rid of Boost?

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#251]
We could try to get rid of Boost entirely. In this issue we should maybe collect potential alternatives for selected boost libraries. The goal would be to find small libraries that can be shipped inside Marian for easier building. 

* https://github.com/badaix/popl -- a candidate to eliminate boost_program_options. Seems reasonably advanced, header-only, MIT license. 

Feel free to add more. We also use `system timer iostreams filesystem chrono thread`. Out of these `filesystem` is probably the most critical now. Unsure why we need `boost::thread`, scoped locks maybe (C++17 cannot come quickly enough). The rest seems manageable.

**Comment by snukky** [comment]
I'm not sure if `popl` supports multiple-argument options.
Other candidates to replace `boost::program_options`:
* https://github.com/jarro2783/cxxopts
* https://github.com/Taywee/args

**Comment by emjotde** [comment]
The first one looks good, nearly a drop-in replacement?

**Comment by snukky** [comment]
Yes, cxxopts looks promising. 

Instead of `boost::filesystem` we can use one of the following:
* https://github.com/cginternals/cppfs
* https://github.com/wjakob/filesystem

**Comment by snukky** [comment]
A general resource, worth taking a look into it: https://github.com/fffaraz/awesome-cpp

**Comment by emjotde** [comment]
We should be on that list!

**Comment by emjotde** [comment]
We should also just include zlib in the 3rd party folder. The zlib-license seems to be compatible with MIT.

**Comment by emjotde** [comment]
We could actually get to a point where the 16-bit CPU version of Marian would be completely free of dependencies other than a C++11 compiler.

**Comment by snukky** [comment]
For future reference, there is a relevant issue on better command line options handling: #60

**Comment by emjotde** [comment]
Done :)
