### ISSUE TITLE
logging writes double CR at line end on Windows

### ISSUE THREAD

**Issue by frankseide** [marian-nmt/marian-dev#255]
Hi, I observe that when compiled under Windows, the log output generated by Marian contains two CR characters at each line end, resulting in malformed text files. For example,

    0001140 65 6e 63 65 *0d 0d 0a* 5b 32 30 31 38 2d 30 36 2d

A correct text file should either end its lines in LF (even under Windows, most text editors will accept this format), or with CRLF (the standard Windows format), with a slight preference for the latter for full compatibility with standard Windows tools like Notepad, FWIW.

(I suspect the logger tries to be pro-active and insert the CR at each line end, but also configures the CRT to automatically insert one.)

**Comment by emjotde** [comment]
@snukky might be worth checking out if spdlog has any updates or if they can fix that for us.

**Comment by emjotde** [comment]
@frankseide Did we ever do something with that?

**Comment by frankseide** [comment]
I think I fixed that.

Trying it just now, the Windows build writes logs that have no CRs at all. For example, they won't show correctly in Notepad. Not sure if that's what we want. On the other hand, Notepad supposedly will learn how to handle LFs soon, so maybe just leave it as is.

**Comment by snukky** [comment]
Old issue. It seems to be fixed now. Closing.
