### ISSUE TITLE
ThreadPools not used in sync SGD

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-dev#258]
To the attention of @snukky and @marcinjd 

ThreadPools in sync SGD are created on the stack and discarded all the time:
https://github.com/marian-nmt/marian-dev/blob/master/src/training/graph_group_sync.cpp#L61
https://github.com/marian-nmt/marian-dev/blob/master/src/training/graph_group_sync.cpp#L138
https://github.com/marian-nmt/marian-dev/blob/master/src/training/graph_group_sync.cpp#L182

This occurs once in async: 
https://github.com/marian-nmt/marian-dev/blob/master/src/training/graph_group_async.cpp#L87 
but it's not a big deal, because the majority of the work is done by the reusable threadPool: 
https://github.com/marian-nmt/marian-dev/blob/master/src/training/graph_group_async.cpp#L277

Is there any reason for that? Why not just create simple threads if we are not going to make use of the pool functionality?

Could be of interest to @kpu and @afaji

**Comment by emjotde** [comment]
seems like over-optimization too me. Is it worth in any way to change this?

**Comment by XapaJIaMnu** [comment]
If we have millions of thread creation and destructions the proper thing to do is to use a threadpool and there is no reason to create one on the stack every time "execute" runs. If we would rather not use threadpools for simplicity sake, we should just enqueue normal threads and get rid of pools.

At any rate what happens currently is really not proper and is a bit confusing to someone reading the codebase. In terms of cost, creation and destruction of threads requires context switch to kernel space which is rather expensive. How much in this case, I don't know, it's too late at night/early in the morning for me to write a benchmark. At any rate there is no reason not to use our threadpool properly if we have it.

**Comment by emjotde** [comment]
My bet, you won't even be able to measure that.

**Comment by emjotde** [comment]
Also, I will refactor this soon. Want to try NCCL.

**Comment by emjotde** [comment]
Closing this as I have a version of sync sgd without the pool and with optional NCCL. Will update soon.
