### ISSUE TITLE
Training char-s2s models

### ISSUE THREAD

**Issue by murhafh** [marian-nmt/marian-dev#260]
I'm trying to train a character level model and I couldn't find any document on how to set that option, I tried setting the type as in:

--type char-s2s

But that throws an unknown model type error. 

Thanks in advance for your help

**Comment by snukky** [comment]
The CNN character-level model probably doesn't work with the most recent version of Marian. We plan to fix this in a near future. You may try with branch `charS2S` and take a look into this regression test (which is now disabled): https://github.com/marian-nmt/marian-regression-tests/tree/master/tests/models/char-s2s

**Comment by emjotde** [comment]
It also won't be compiled into Marian unless CUDNN is available.

**Comment by snukky** [comment]
The trained model from the regression test can be downloaded with this script: https://github.com/marian-nmt/marian-regression-tests/blob/master/models/download-char-s2s.sh

**Comment by murhafh** [comment]
Thanks for the info, I'm trying to run the training from charS2S branch but getting the following error. I got CUDNN installed, any idea why this could be happening?
`Aborted from marian::CUDNNWrapper::CUDNNWrapper() in /home/murhaf/microsoft/marian-dev/src/kernels/cudnn_wrappers.cu: 320
Aborted (core dumped)`

**Comment by snukky** [comment]
Few months ago, I have been successfully training the `char-s2s` model using the branch `selu` and commit 5f41e40. According to `ldd`, I had Marian compiled with CUDA 8.0 and CUDNN v7.
