### ISSUE TITLE
how big the value of warmup  should be

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#261]
When i train zh-kr about 8 million parallel  corpus with marian-dev-1.2, the learning rate and warmup as follows:
--learn-rate 0.0003 --lr-warmup 16000 --lr-decay-inv-sqrt 16000 

the curve which reflect the relation of bleu iter in the attach file, should i set the warmup bigger？ or decrease the learn-rate?
![c2k bleu](https://user-images.githubusercontent.com/5691554/42076805-3c327c60-7ba9-11e8-8831-3efdd6f3780d.png)

**Comment by 520jefferson** [comment]
![c2k bleu](https://user-images.githubusercontent.com/5691554/42076768-1594de22-7ba9-11e8-8c8a-5a3c4f0ac57c.png)

**Comment by emjotde** [comment]
Try a lower learning rate, maybe 0.0001. I also recommend updating, training should be a good deal faster with 1.5 and it will be again faster with 1.6 soon.
