### ISSUE TITLE
PoolingWrapper dependency

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#262]
It looks like you're trying to not depend on tensors/gpu/cudnn_wrappers.h in https://github.com/marian-nmt/marian-dev/blob/master/src/graph/node_operators_unary.h#L10

But https://github.com/marian-nmt/marian-dev/blob/master/src/graph/node_operators_unary.h#L1102 uses PoolingWrapper which is defined in tensors/gpu/cudnn_wrappers.h.  So files that include "graph/node_operators_unary.h" don't compile.

**Comment by emjotde** [comment]
That should be handled by ifdefs. @snukky can you take a look?
