### ISSUE TITLE
"select" op causes "illegal memory access"

### ISSUE THREAD

**Issue by llysuda** [marian-nmt/marian-dev#265]
A line like "a = select(expr, axis, indices);" causes the following error msg: 
Error: an illegal memory access was encountered - /home/xxx/marian/src/marian/src/tensors/gpu/cuda_helpers.h:29

Could you help to solve this problem?  Many thanks.

**Comment by emjotde** [comment]
Hi,
yes, that operator is currently broken. What are you trying to achieve? I can try to fix it over the weekend, having someone who actually needs it, might be a good motivation.

**Comment by llysuda** [comment]
That's great, many thanks.

I'm trying to select values from multi-head attention weights along the head axis in Transformer.  Of course, there are other ways, such as by masking, to achieve this. However, I think using the select op would be more straightforward and efficient.

Another usage I'm thinking recently is selecting alive sentences for future decoding steps during beam search. Removing finished sentences from computation will improve speed as mentioned in fairseq's twits.

**Comment by emjotde** [comment]
Just a heads up on the second problem, I'm actually working on that. Just need to make the beam search less convoluted first. 

For now, a combination of `flatten_2d` and `rows` might be useful for you.

**Comment by emjotde** [comment]
Just to show that this was not only Facebook's idea, here's the issue from February: https://github.com/marian-nmt/marian-dev/issues/175

It's high on my TODO list. I will now be busy for the next two weeks with ACL, but hope to finish this soon enough.

**Comment by emjotde** [comment]
I think the select operator is fixed now.

**Comment by llysuda** [comment]
Great. Many thanks.
