### ISSUE TITLE
Corpus restoration takes forever

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#269]
Corpus restoration 4 epochs in on a dataset of about 30M sentences seems to take forever. After 20 min training has still not started. This is something we might want to look into.

**Comment by snukky** [comment]
I guess it happens for `--sqlite`?

**Comment by emjotde** [comment]
No, plain text actually. This also uses `--mini-batch-fit --mini-batch 1000 --maxi-batch 1000`

**Comment by emjotde** [comment]
Seems to be fine now, maybe it was some filesystem glitch. Closing.
