### ISSUE TITLE
Make marian-decoder translate line-by-line without buffering

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#274]
It seems that with --mini-batch 1 --maxi-batch 1 marian-decoder will translate with one sentences delay when translating from stdin. Might be worth to take a look.

**Comment by snukky** [comment]
Batch generator was a culprit as it consumed one sentence in advance when filling maxi batches.

**Comment by oraveczcsaba** [comment]
Let me note here that output buffering is still there if marian-decoder is called as a subprocess from some wrapper script. This can be circumvented however with using 'stdbuf -o 0 marian-decoder ...' in the call.

**Comment by emjotde** [comment]
Thanks, just to clarify, that's the wrapping script doing the buffering though?

**Comment by oraveczcsaba** [comment]
I don't think so. We use subprocess.Popen in python to launch various decoders. With amun it works but marian-decoder still hangs. It only works if we launch marian-decoder through the stdbuf utility as above.

**Comment by emjotde** [comment]
OK, we'll take another look. Thanks.

**Comment by snukky** [comment]
@oraveczcsaba Could you provide the fragment from your script, which shows how you call marian-decoder and amun in Python?

BTW. If you need line-by-line translation, why not marian-server? If you don't need line-by-line translation, why not `--input`?

**Comment by emjotde** [comment]
@snukky unbuffered reading from stdin would still be a good idea, regardless of other options.

**Comment by snukky** [comment]
Of course, I agree. marian-server or `--input` are just alternatives. Sometimes overlooked. Often better.

**Comment by oraveczcsaba** [comment]
something very basic like this:
```
 from subprocess import Popen, PIPE
...
 worker=Popen(args, stdin=PIPE, stdout=PIPE, ...
```
``args`` contains ``amun`` and its standard command line arguments or currently ``stdbuf -o0 marian-decoder`` and command line arguments if we want to use marian-decoder.
This is just a part of a pretty old and complex line-by-line processing framework developed some time ago, which does a lot of pre and postprocessing on segments, and is capable of running various decoders provided that they do not buffer input/output. Not the most efficient for sure and it will be reworked sooner or later.

**Comment by frankseide** [comment]
If we support line-by-line reading, we must also support line-by-line writing, that is, unbuffered writing. Don't we already have special-casing for reading line by line? How about when in line-by-line mode we also set stdout to unbuffered? `setvbuf(stdout, NULL, _IONBF, 0));`

**Comment by emjotde** [comment]
Ah right. I forgot about that type of buffering. I think @snukky only fixed the programmatic error we had where we were reading ahead by one line. 

I guess we can just set this globally in marian-decoder? I don't think there is a use case where this would be harmful, right?

**Comment by kpu** [comment]
@emjotde Which scenario are you asking about?
Harmful: always unbuffered.  
Good: if the user asks for unbuffered, it should also apply to stdout as @frankseide suggests.

**Comment by emjotde** [comment]
I don't expect though that we are fast enough at translation to make buffering matter?

**Comment by snukky** [comment]
Yes, I've fixed only the obvious bug with translation output delayed by one line. I vote for adding a command-line option to set stdout to unbuffered.

**Comment by frankseide** [comment]
It matters in an interactive setting, where a client process runs Marian as a pipeline and sends it one sentence at a time and then reads back the translation. If buffering is enabled, then the reading process will not receive the resulting translation since it is still sitting in the CRT buffer. It will thus deadlock.

**Comment by emjotde** [comment]
Yes yes. I am asking about the inverse case. Are we ever going to be in a situation where we would prefer it to be buffered at all?

**Comment by frankseide** [comment]
Thinking about it, we may want to consider *line* buffering, so that lines are written atomically to the pipe, which may make it a little easier for some consuming code.

Beyond that, I see no use case of buffering at all.

**Comment by emjotde** [comment]
Or maybe let's to this, when --mini-batch 1 --maxi-batch 1 then switch off buffering?

**Comment by frankseide** [comment]
Even simpler: How about do `std::cout << std::flush` after writing each *batch* to stdout. If batch size is 1, then this will give us line-buffered behaviour. If batch sizes are larger, then it gets close to normal buffering.

**Comment by emjotde** [comment]
So, switch off stdin buffering + std::flush on stdout.

**Comment by hieuhoang** [comment]
you also want do this if you use std::cin
  https://github.com/marian-nmt/marian/commit/1582f9982312ae8740c893a5eeeab24463617496

**Comment by frankseide** [comment]
Re the `stdin` buffering, our internal C++ specialists confirmed that reading from a pipe will not stall until the buffer is filled, but rather only fill the buffer with as many characters as are available in the pipe. Hence, the buffered read will not block as long as data is present in the pipeline. This was a confirmation for the Windows CRT (Visual Studio), but it should be the same for Linux.

So for `stdin`, we should keep buffered mode.

**Comment by emjotde** [comment]
@snukky ping

**Comment by emjotde** [comment]
Works fine for me, closing.
