### ISSUE TITLE
Validation on dev set with BLEU scorer

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#28]
Framework for validation every `n` steps. For instance it should be possible to specify `--metric perplexity bleu` and it should then calculate these values on the dev set. It would be good to have this as a skeleton. How the individual scoring methods are implemented would be a separate issue. 

Perplexity can be evaluated just by running forward steps on dev set batches and could be done as a first example how to extend the skeletons. Validation results should be logged to separate files using a specific logger. 

For bleu we need of course a translator and a bleu scorer.

**Comment by emjotde** [comment]
Works now for cross-entropy and perplexity. Leaving it open, as it does not do BLEU yet.

**Comment by hieuhoang** [comment]
you mean there's already a framework that works for cross-entropy & perplexity, and we just have to do another 1 for bleu? Or we should still create a framework?

**Comment by emjotde** [comment]
Same framework can be used. Just needs a working translator and bleu scorer. Will work on the first thing this week.

**Comment by snukky** [comment]
We already have a validating translator. Next step is to use scorers from https://github.com/marian-nmt/moses-scorers

**Comment by emjotde** [comment]
We have "bleu" validation metric now, does BLEU on the batch content, so no preprocessing, but probably correlates well with actual BLEU, just overestimated due to oversegmentation with BPE.
