### ISSUE TITLE
how can i decode faster without adding more gpus

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#280]
May i use the tool of fast_align to limit the target vocabulary to a small size ?

Or are there  same skill to speed up , now i just limit the vocabs to 30000.

**Comment by emjotde** [comment]
What are your current settings for decoding?

**Comment by 520jefferson** [comment]
I just set devices 6,beam-size: 6 with one model and two different vocabs, and i find the gpu-theads doesn't work when i decode with transformer.

**Comment by emjotde** [comment]
Please post your full command.

**Comment by 520jefferson** [comment]
I decode like this ./marian-decoder --type transformer -d  4  -m $model  -v $PATH1/res.ch.src .pkl.json   $PATH1/res.kr.tar.pkl.json  -b 6  - -i test.in.bpe

**Comment by emjotde** [comment]
Try this:

```
./marian-decoder -d 4 -m $model -v $PATH1/res.ch.src .pkl.json $PATH1/res.kr.tar.pkl.json \
 -b 6 --mini-batch 64 --maxi-batch 100 --maxi-batch-sort src -i test.in.bpe
```

**Comment by 520jefferson** [comment]
I know batch translation can speed up, but if i use marian-server, most time the input is a single sentence. Could  this speed up also ?

**Comment by emjotde** [comment]
What's the speed you need? 

You can use `--transformer-decoder-autoreg average` during training, this will train a model with a different self-attention layer that can be about 2-4 times faster on the GPU. Using a vocabulary filter does not do much on the GPU, maybe about 10%. 

You can also experiment with teacher-student training and decoder with beam-size 1 like here https://arxiv.org/abs/1606.07947 and in our work http://www.aclweb.org/anthology/W18-2716

**Comment by 520jefferson** [comment]
How about a sentence like this "The orchestra is one of the finest things people can do to get together and it is a flower of culture and art, an observer of history, and a laboratory that creates the future" can be decode in a second with 20 accesses.

**Comment by emjotde** [comment]
What do you mean?

**Comment by 520jefferson** [comment]
I mean when using marian-server to decode a sentence will cost about 500ms with one user, but in the multi thread environment, the decoder will take more than 2000ms with the same sentence.

**Comment by emjotde** [comment]
You need to give me more information about your scenario. Are you trying to translate multiple sentences at once on a single GPU? I do not think there is a good way to make that faster.

**Comment by 520jefferson** [comment]
The scenario is about client and server . In the client, many users input sentences (randomly,maybe many sentence in the same time ) by browser,and the sever(which provide translation like marian-server)  will supply translation service, after translation the server return the result to client.
when testing  I find in the server , when multi threads access are apply,the decoder will be slower, and i already limit the vocabs to 30000. Maybe i can use ANN which you tell me to retrain and test again.

**Comment by emjotde** [comment]
All the mentioned method will make things faster, however, running multiple calculations on a single GPU will always slow down latency by a lot. Not sure you can do much with that.

**Comment by 520jefferson** [comment]
Maybe adding the function of  gpu-threads like amun has will speeed up when decoding with type of transformer ,because when decoding 1100MiB memory will be consumed but a single gpu has 22000MiB ,with multi gpu-threads will be more efficient？

**Comment by emjotde** [comment]
I think each sentence has its own thread already, @snukky?

**Comment by snukky** [comment]
Yes, it does. `marian-server` might be not optimized for multi-thread batched translation as this is a basic tool. If you need more efficient communication between clients and a server, for example by providing translations back to the client on the fly, you need to implement your own tool.

**Comment by 520jefferson** [comment]
Thanks a lot, i see roughly. Although each sentence has its own thread, but it seams cannot be translate the same time using a single gpu which maybe exclusive in a decoding period (i thought multi-threads will process in the same time in one single gpu without disturb others). Then, I will optimize the model, then try to dome optimization in my scenario.

**Comment by emjotde** [comment]
The problem with multiple processes on a single GPU is not only computation, but also memory transfer etc. There is a lot of things going on that get into each others way.

**Comment by 520jefferson** [comment]
@kpu Sorry for reply late. I already  use the tools of  XMLRPC to communicate for server and client. I just wonder if i start the server with max-conn 10 (max-conn is XMLRPC's paramter to limit the access) and test with JMeter, when testing if i use one thread to access, the decoding time is normal about 800ms, as long as we start 10 threads in JMeter to access the decoding time of one sentence obviously increase serveral times  . So i'm curious about decoding under multi threads.
As to Naggle, i think the user to access the server randomly, if the amount of access is huge in the same time, maybe i should consider this. But now i care  more  about decodeing mechanism in multi threads, and how to elevate it.

**Comment by 520jefferson** [comment]
@emjotde  indeed, using the short-list to reduce the vocabs when decoding won't help a lot.
