### ISSUE TITLE
Resuming training with corpus pointer very slow for large batch offset

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#288]
If the batches are huge (`--mini-batch-fit --workspace 10000 --sync-sgd`) on 8 GPUs resuming training seems to take forever when it tries to get to through many batches in an epoch. I saw 40 mins wait time for 75M sentences. This is worth investigating.

**Comment by snukky** [comment]
I've checked and even for the default `--mini-batch 64 --maxi-batch 100`, rewinding to ~40M sentence in an epoch (~600000 batches) takes ca. 38 min: 4 mins is shuffling, 34 mins is generating batches.

Batches are generated (and dropped) for the entire last epoch. One solution might be  "jumping" to the second to last maxi-batch, but I'm not sure if this might work with `--mini-batch-fit`. And we would need to consider sentences longer than max-length.

**Comment by emjotde** [comment]
Or we find out what it taking so long and optimize that.

**Comment by emjotde** [comment]
Seems to be not too bad now, closing.
