### ISSUE TITLE
--dump-config not working with config files with relative paths

### ISSUE THREAD

**Issue by Proyag** [marian-nmt/marian-dev#291]
If I run `marian-decoder -c path/config.yml --dump-config` and my config file is using `relative-paths`, it dies in [validateOptions in config_parser.cpp](https://github.com/marian-nmt/marian-dev/blob/8856ae9c890b3789c11a873bace571e92b130382/src/common/config_parser.cpp#L1049) with the following message:
```
Error: /data/smt/distTapta/marian-dev/src/common/config_parser.cpp:92 in void marian::ConfigParser::validateOptions() const threw util::Exception because `!boost::filesystem::exists(modelPath)'.
Model file does not exist: model.npz.best-translation.npz
```

This is because the relative paths aren't changed to absolute paths [here](https://github.com/marian-nmt/marian-dev/blob/8856ae9c890b3789c11a873bace571e92b130382/src/common/config_parser.cpp#L1018). Is there a good reason for the `!vm_["dump-config"].as<bool>()` condition there? Just removing it fixes this particular problem for me.

**Comment by snukky** [comment]
Hi, yes, it's a known issue and it will be solved after merging my branch with a new command-line interface into the master. We'll do this after MT Marathon.

**Comment by snukky** [comment]
It works now with new CLI. I also added a regression test.
