### ISSUE TITLE
Better error message on CPU when compiled without MKL

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#293]
When one attempts to use the CPU version but MKL was not found at compile time, the resulting binary does ABORT("Not Implemented").  A better message would say to install MKL and recompile.  cc @bhaddow

**Comment by emjotde** [comment]
True. Where's the PR?

**Comment by bhaddow** [comment]
#294

**Comment by snukky** [comment]
It's been already merged.
