### ISSUE TITLE
std::bad_alloc when Saving Adam parameters to model.npz.optimizer.npz

### ISSUE THREAD

**Issue by obo** [marian-nmt/marian-dev#299]
Hi, I got this segfault:

```
[2018-09-10 03:36:14] Ep. 2 : Up. 50000 : Sen. 245942 : Cost 17.42 : Time 4855.67s : 2590.33 words/s
[2018-09-10 03:36:14] Saving model weights and runtime parameters to model.npz.orig.npz
[2018-09-10 03:36:24] Saving model weights and runtime parameters to model.iter50000.npz
[2018-09-10 03:36:33] Saving model weights and runtime parameters to model.npz
[2018-09-10 03:36:42] Saving Adam parameters to model.npz.optimizer.npz
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./marian: line 37: 20201 Aborted                 $MARIAN "$@"
```

with these training flags:

```
--type s2s --enc-depth 4 --enc-type alternating --enc-cell lstm --enc-cell-depth 2 --dec-depth 4 --dec-cell lstm --dec-cell-base-depth 4 --dec-cell-high-depth 2 --tied-embeddings --skip --exponential-smoothing --sync-sgd --mini-batch-fit --layer-normalization --dropout-rnn 0.2 --dropout-src 0.1 --dropout-trg 0.1 --early-stopping 5 --save-freq 50000 --disp-freq 5000 --valid-freq 50000 --valid-metrics cross-entropy translation --valid-sets dev.src.gz dev.tgt.gz --valid-script-path ./validate.sh
```

I haven't used marian-dev yet, so I may be using the parameters wrongly.
(I am not even sure I am using Adam, which may be the reason of the segfault.)

The parameters for validation seem however OK, validation works for me with transformer training (in a different directory, not that I would mix the two):
```
--type transformer --exponential-smoothing --sync-sgd --mini-batch-fit --layer-normalization --early-stopping 5 --save-freq 50000 --disp-freq 5000 --valid-freq 50000 --valid-metrics cross-entropy translation --valid-sets dev.src.gz dev.tgt.gz --valid-script-path ./validate.sh
```

**Comment by obo** [comment]
The job was scheduled with up to 20 GB RAM limit (the transformer training runs have the same limit and survive).
Cluster usage says: vmem=16.781M, maxvmem=10.101G

I had another job like that, running with a smaller workspace (so not using the GPUs RAM fully), that also died (on a different machine and at a different time). This other job reported usage: vmem=3.734G, maxvmem=3.939G

...so it doesn't really look like reaching the CPU RAM limit of 20 GB and it is also rather unlikely that someone else would kill that machine.

**Comment by emjotde** [comment]
Does the other job die at the same time in the log? I really hate your cluster, it's weird :)

**Comment by obo** [comment]
Yep, exactly the same situation:
```
[2018-09-10 08:44:57] Saving Adam parameters to model.npz.optimizer.npz
terminate called after throwing an instance of 'std::bad_alloc'
```
My best virtue is ...unfortunately... betatesting... ;-)

**Comment by emjotde** [comment]
It's really weird, there is nothing model specific about the optimizer parameters. Can you send me both logs by mail?

**Comment by emjotde** [comment]
Also, you wrote that you did not see problems in peak memory, take into account that you wouldn't see a sudden failed large allocation in the logs. Because allocation failed it would not show up as used memory, right?

**Comment by obo** [comment]
I'll try.
Yes, you are right and I forgot to mention this: sudden allocation beyond the limit may not appear in the reported usage.

**Comment by obo** [comment]
So yes, indeed memory limits!

30GB:
```
[2018-09-10 11:55:26] Saving Adam parameters to model.npz.optimizer.npz
[2018-09-10 11:55:50] Training finished
[2018-09-10 11:55:53] [valid] Ep. 1 : Up. 50 : cross-entropy : 146.678 : new best
[2018-09-10 11:55:53] Translating validation set...
[2018-09-10 11:55:54] Best translation 0 : 
[2018-09-10 11:55:54] Best translation 1 : 
[2018-09-10 11:55:54] Best translation 2 : 
```
At first, I got worried for seeing the empty outputs [this used to be also an artifact of insufficient CPU memory as I reported in one of the older issues; I am not sure about its status] but given that the model has trained just for 10 batches, this is OK. The s2s model from the original run delivers some outputs.

So thanks for finding the reason!

**Comment by emjotde** [comment]
Great. Closing.
