### ISSUE TITLE
Cannot overwrite a npz file on Windows

### ISSUE THREAD

**Issue by cedrou** [marian-nmt/marian-dev#301]
The commit 2f8b093a6d9255ee0d7204c61c03a1fc79f9e136 breaks the training on Windows when saving the intermediate model.

Before the commit, the target file was first removed then recreated from scratch.
Now, the content is first saved in a temp file which is then renamed with the target's file name. Unfortunately, the `rename` implementation on Windows fails if the target file already exists.

A rollback of this commit fixes the issue.

**Comment by emjotde** [comment]
Deepest respect for running this on Windows already; this is highly experimental. 

@frankseide can you take a look at that?

**Comment by emjotde** [comment]
@cedrou Out of curiosity, can you comment a bit how you build this under windows and how you use it? Don't worry if you cannot.

**Comment by emjotde** [comment]
Great. Looking forward to it.

**Comment by frankseide** [comment]
Can you try if adding an `unlink()` call fixes it?

        // move to final location (atomically)
        unlink(zipname.c_str());
        bad =  bad || (rename(tmpname.c_str(), zipname.c_str()) == -1);

**Comment by frankseide** [comment]
BTW the current Visual Studio project in `https://github.com/marian-nmt/marian-dev/tree/master/vs` requires setting certain environment variables manually for the depedencies. This is based on the manual setup for building CNTK, and not ideal. With Visual Studio 2017, there is a better way to get at least some of the libs (e.g. Boost) and integrate them into VS, via Nuget packages. My colleague has experimented with that, but not yet sent a PR. If you add a new library, can you try to follow that route if possible?

**Comment by cedrou** [comment]
Thanks Frank. I'm in the middle of the training of the basic example, so I'll try your fix just after, probably tomorrow. I'm pretty sure this will work as intended.

Concerning the project, I have not used your VS project files because I started this 2 months ago, before seeing that you already worked on that. I have modified the CMake configuration files that create them with the right flags. I choose to use the CMake scripts to share most of the build configuration files and avoid adding complexity in the maintenance.

For the dependencies, I use vcpkg because it's the package manager I know the best for MSVC, but I guess Nuget will also do the job.

Please take a look at the building scripts (configure.bat and build.bat) I wrote in https://github.com/cedrou/marian-dev/tree/build_on_win/vs

**Comment by frankseide** [comment]
`vcpkg`, yes, that's the one, not Nuget. my mistake. Great!

I created the VS Project because in my experience, VS is absolutely a far superior dev environment compared to e.g. VSCode, esp. for debugging. I presently have my Linux repo folder SMB-shared to Windows, and open the VS Solution in the Linux folder. I edit code, compile, and debug on Windows with VS. Once done, I type "make" in the Linux shell and run the main job on Linux or submit to our Linux farm. I feel that the benefits of using VS far outweigh the benefits of CMake's automatism, and hence, we opted to spend the extra effort to manually maintain a VS Project in parallel.

As for CMake, is there a way to make it create a project file that displays the files in a meaningful folder hierarchy; and to not generate absolute pathnames? These are the two main reasons I don't use it for Windows. I cannot work if I am presented with a flat list of 200 source files. But I'd be happy to reconsider if those issues can be resolved.

**Comment by cedrou** [comment]
I’m also a big fan of VS and it’s debugging experience. And I also agree that the format of the projects created by cmake is far from being ideal. I know that the latest versions of vs 2017 have made a good progress in cmake integration, in particular you can open a directory (not only a solution) and use the cmake tool gain to build. However I haven’t tested that yet. I just used the created projects to do some debugging. I’ll take a look at that and come back to you.

**Comment by cedrou** [comment]
This now works as intended with your fix.
I have protected the line with `#ifdef __MSC_VER … #endif` to restrict it to VS build toolset and to keep the atomicity of the rename operation for other platforms.

I have run the `training-basics` example with success. I interrupted the training after 24 hours and 12 epochs, and finished the script successfully.

I also created the required file (`CMakeSettings.json`) to enable CMake integration into VS. This allows to use VS as the editor/debugger, while keeping CMake configure and build features.

I now need to update my repo with latest commits before providing my PR.

Thanks for your help.

**Comment by frankseide** [comment]
Great! Thanks so much!

Would it also be possible to include the setup instructions? E.g. a copy-pasteable sequence of vcpkg calls?

**Comment by cedrou** [comment]
Sure. There is already a batch file that does all the job ([configure.bat](https://github.com/cedrou/marian-dev/blob/build_on_win/vs/configure.bat)). I will eventually modify it to optionally handle CMake integration in VS.

**Comment by emjotde** [comment]
I gues that will be fixed with the PR #308
