### ISSUE TITLE
Allow to choose training unit and epoch defined in terms of units.

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#304]
For instance, it should be possible define an epoch as 1 billion source tokens, randomly sampled (with repititon?) from the training data.

Epochs as data sweeps are difficult to compare across training sets. 

Epoch-unit could be: `[sentence, token]. `
Epoch could be: `[data, N * epoch-unit]`

Current behavior is `epoch-unit: sentence`, `epoch: data`.

**Comment by snukky** [comment]
I think logical epochs added recently implement this, closing.
https://github.com/marian-nmt/marian-dev/blob/542be2f909ff58412a87cec7f80f3f0c3a422b14/src/common/config_parser.cpp#L402
