### ISSUE TITLE
Switch to Python-like documentation and add useful documentation.

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#306]
Dump Doxygen (nothing good comes out of Java) and try to use Sphinx as a documentation system instead. Also add proper documentation. 

@snukky can you try to add an example use case?

**Comment by snukky** [comment]
The Breathe extension to Sphinx requires doxygen for parsing C++ code and/or documentation comments.

I'll check this: https://github.com/foonathan/standardese as it seems to be a real replacement for doxygen.

**Comment by snukky** [comment]
Initial work has been done in https://github.com/marian-nmt/marian-dev/tree/docs. We are reactivating this task in one of the projects in Edinburgh.

**Comment by snukky** [comment]
Closing after merging #803.
