### ISSUE TITLE
Make asynchronous SGD scale linearly

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#31]
We have synchronous and async SGD now. Currently all gradient updates are communicated to the central parameters. There would be two (orthogonal) ways to handle that: Alham's work and introducing a delayed update by `tau` steps. The second option requires some accumulation and possibly choosing optimizers per worker below the main SGD variant (Adagrad, Adam). Currently on the Titan X scaling is sublinear for a typicial WMT-grade DL4MT model, though not tragically so:

1 GPU: 4100 w/s
2 GPU: 6500 w/s
3 GPU: 9200 w/s

Would be great to get to >12000 w/s on 3 GPUs.

**Comment by emjotde** [comment]
@kpu @afaji Is true hogwild! realistic?

**Comment by dr-alan-turing** [comment]
Currently the GPUs do the computation and communication one after the other. Removing the lock_guards in sparse/pushGrads() and sparse/fetchParams() speeds up things and is more similar to hogwild!. Overlapping computation and communication should further speed up the words/sec but the resulting delayed updates can negatively impact convergence rate. I'm working on a Multi-Node AsyncGraphGroup for my MSc dissertation (supervised by Kenneth) where I'm implementing this overlapping behaviour + sparse communication (communication between nodes is much slower than the computations). I'm happy to try this out on the AsyncGraphGroup as well after my deadline.

**Comment by emjotde** [comment]
Sync sgd seems to be better, so closing this.
