### ISSUE TITLE
marian-decode batch translation generate different result 

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#311]
input: ##NUM##0 年 …@@ … ##NUM##1 年 过去 了 …@@ … 居然 听    他们 听 了 ##NUM##2 年 啦 …@@ … 光@@ 匆匆 呀 …@@ …

when mini-batch=1,i get best1:
##NUM##0 . . . ##NUM##1 years . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

when mini-batch=512,i get best1:
##NUM##0 years . . . ##NUM##1 years . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . , and , and , and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and ##NUM##2 years and ##NUM##2 years and ##NUM##2 years and ##NUM##2 years and ##NUM##2 years and ##NUM##2 and ##NUM##2 and ##NUM##2 and ##NUM##2 and ##NUM##2 and ##NUM##2 and ##NUM##2 and ##NUM##2 and ##NUM##2 and ##NUM##2 ##NUM##2 ##NUM##2 and ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 and ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 to ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 ##NUM##2 to the to the to the to the to the to the to the to the to the to the to the to the to the to the

is there something wrong?

**Comment by emjotde** [comment]
Probably!

**Comment by 520jefferson** [comment]
@emjotde  is there some problem in batch translation? i think the batch data will be loaded in gpus, and process one by one ,meanwhile  sentences won't affect each, or maybe sentences can be processed in Parallel  and won't be given to one processor.

**Comment by emjotde** [comment]
Ah. The difference is the length limit. The translation is fundamentally corrupted (bad model?), but since the decode stops decoding at 3x times the maximum length of a sentence in a batch, the translations for batched translation maybe longer if they produce garbage. It's not really a problem with the decoder. Your model should not be producing this kind of translations in the first place.

**Comment by 520jefferson** [comment]
maybe i should set mini-batch smaller from 512 to 64 , it will limit the maximum length help to reduce the garbage length.

**Comment by emjotde** [comment]
Garbage is garbage, it does not seem to be worth to care? Rather try to get rid of the garbage in general.

**Comment by 520jefferson** [comment]
@emjotde  Yes, we should care more about corpus. but garbage we cannot avoid completely, but we can alleviate.

**Comment by 520jefferson** [comment]
@emjotde it's weird. i used batch translation i get the result use " 1>result 2>nohup "  , i translate more than  6 million sentences, but result only get 551561 items， than result don't increase but nohup increase normally.
