### ISSUE TITLE
marian-scorer error

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#314]
1, i  use this as the https://marian-nmt.github.io/docs/ says: 
./build/marian-scorer -m model.npz -v vocab.{en,de} \
    -t file.en.txt file.de.nbest --n-best --n-best-features F0

and i get this : 
 Error: unrecognised option '--n-best-features'

if i remove '--n-best-features F0' ,then i get the Score:

2,how can i use the score to get the best result?  should i extract the highest Score sentences? it seems the  Score is nearly equal to F0.

**Comment by 520jefferson** [comment]
@emjotde  As for the second question. i cannot figure out  how can I use maria-scorer  to improve the translation result.

**Comment by emjotde** [comment]
The scorer will only report model scores. You could use it for rescoring with other models (for instance language models or right-to-left models), but you still need to do the selection yourself later. There is no universal recipe. 

The https://github.com/marian-nmt/marian-examples/tree/master/wmt2017-transformer example has rescoring with right-to-left models, for instance.

**Comment by snukky** [comment]
The typo is fixed in the source code branch. I'll re-generate the website when I have access to a machine with Jekyll installed. The issue can be closed for now.
