### ISSUE TITLE
Compile MKL in parallel mode

### ISSUE THREAD

**Issue by rihardsk** [marian-nmt/marian-dev#324]
When compiling the CPU version, why is MKL compiled in _sequential mode_ instead of _parallel mode_? In [cmake/FindMKL.cmake#41](https://github.com/marian-nmt/marian-dev/blob/6c9b4a4639b10a4b92abf75527f8b731811058f9/cmake/FindMKL.cmake#L41) there's a mention of `mkl_intel_thread.lib` but it seems that it's never used afterwards.

Currently there's a `--cpu-threads` option available in `marian-decoder` which decodes with multiple instances of the same model in parallel but it has no benefit when doing online decoding. So parallelizing MKL ops would be super useful in this setting.

**Comment by emjotde** [comment]
You would think so, but the benefits are nearly non-existent. MKL seems to be doing really badly when multi-threading for single sentences. You get maybe 20% faster for 2-4 threads, then it gets slower and slower until it slower than single thread.

**Comment by rihardsk** [comment]
Oh. It makes sense that translating a single sentences isn't as good as batch translation but i didn't expect the gain to be that low.

Is there maybe some git branch/commit with a cmake configuration for the parallel mode build, in case we wanted to do some benchmarking ourselves?
