### ISSUE TITLE
Only apply relative-paths to paths that actually appear in a config file

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#325]
1) Only apply relative-paths to paths that actually appear in a config file. These should not be applied to paths that are specified at the command line as these are already relative to the CWD (or they should be absolutized wrt the CWD). 

2) We support multiple config files in a vector, relative-paths needs to be applied to them relative to each config which may be in different locations. 

3) Add "input" and "output" to path checking when above works.

**Comment by frankseide** [comment]
Let me take this opportunity to voice my objection to the special pathnames `stdin` and `stdout`. The correct names for both in UNIX is `-`.
