### ISSUE TITLE
Implement shortlist script in python

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#326]
Implement python version of this perl script:

https://github.com/marian-nmt/amun/blob/master/scripts/train_vocab_filter.pl

**Comment by emjotde** [comment]
Maybe also create a repo for fast_align, atool and extract for submodule.

**Comment by snukky** [comment]
There wouldn't be many benefits from reimplementing the Perl script, so we have added an updated version of it in the repo (https://github.com/marian-nmt/marian-dev/tree/master/scripts/shortlist), and a short instruction how to generate lexical shortlists has been added on our web page. 

"extract-lex" has been extracted to a separate repository within the marian-nmt organization.
