### ISSUE TITLE
end-to-end pipeline

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian-dev#332]
is there an end-to-end pipeline that people are using, like the EMS for moses? I'm thinking of creating 1 if not

**Comment by snukky** [comment]
Moses-like pipeline is adopted in Marian examples, and there is an ongoing work on including sentencepiece in Marian.

**Comment by emjotde** [comment]
With sentencepiece (https://github.com/google/sentencepiece) and later better aliases we will be able to train on raw text, e.g.:

```
~/marian/build/marian -t corpus.src corpus.tgt  -v dev.src dev.tgt --alias WMT18-en-de
```

@hieuhoang How about Tensorboard support?

**Comment by emjotde** [comment]
@snukky @hieuhoang do downloading capabilities make sense?

**Comment by hieuhoang** [comment]
sentencepiece looks good but it's tangental to what i'm looking for, which is a declarative system that takes corpus and gives you a bleu score. For reliability and reproducebility 'cos I can't be picking over other people's script anymore.

Sounds like you don't have it so i've started
   https://github.com/paracrawl/Malign/blob/master/crawl/nmt/Snakefile

**Comment by emjotde** [comment]
`--valid-metrics bleu` :)
