### ISSUE TITLE
Writing files to a directory

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian-dev#338]
is there a way to tell marian to write model and intermediate files to a directory other than the current directory? I tried
   -m model/hieu
but it eventually segfaults

**Comment by emjotde** [comment]
Hm. That should work. Is "hieu" a directory? Does it exist?

**Comment by frankseide** [comment]
I use that all the time. E.g. this is an excerpt from my current config:

    "interpolate-env-vars": true,
    "model": "${PHILLY_MODEL_DIR}/CHS.ENU.generalnn_1.model.npz",

If a missing target directory causes a seg fault, then that must be fixed. This is possible if e.g. one uses `f = fopen(.., "w")` to write the file, but it fails with an invalid path, and the subsequent code misses the error check and uses `f` blindly, which is `NULL` in this case. Do we still have `fopen()` in there?

**Comment by emjotde** [comment]
It might also be the missing suffix in the model name. @hieu, can you provide a complete minimal example?

**Comment by hieuhoang** [comment]
-m model/hieu.npz works
-m model/hieu segfaults

The --model argument is correct, but the description of it being a 'path prefix' is incorrect imo

**Comment by frankseide** [comment]
Let's keep this open as a reminder for us to fix this.

**Comment by emjotde** [comment]
Does this segfault right away or during a first saving attempt?

**Comment by hieuhoang** [comment]
When it tries to write

**Comment by snukky** [comment]
No, it wasn't assigned to me.
