### ISSUE TITLE
Tied-layers cannot be overwritten with empty vector from command line

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#343]
Tied-layers cannot be overwritten with empty vector from command line when specified in config.

**Comment by frankseide** [comment]
Example:

 * in config file:
 `transformer-tied-layers: [1,1,1,1,1,1]`
 * on command line:
  `--config ... --transformer-tied-layers  --no-shuffle ...`

leads to `tiedLayers` variable to contain `{1, 1, 1, 1, 1, 1}`.

**Comment by snukky** [comment]
This is somehow related to setting boolean flags to `false` via command line if they are `true` in a config file.

**Comment by frankseide** [comment]
And also to the problem that some variables can have the value "not set." For example, to not use guided alignments, one should not define `--guided-alignment`. But if it is already defined in a config file, it cannot be overwritten to "unset". For now, I use a hack in that if it is set to the filename "none", it is treated as if unset, which has the same problem as naming stdin "stdin"--what if that's the actual filename?

We would either need an "unset" or "undefined" value, or not give "unset" any other meaning than "default", consistently for all parameters.

**Comment by emjotde** [comment]
OK. Using '[]' works, but what is weird now is that you can provide empty vector arguments that have no effect. That seems wrong. Either they should overwrite with [] too (preferred) or there should be an abort.

For instance `--optimizer-params` with no value is completely ignored at the moment, which is fine if it has never been set, but problematic if there is a value in the config. What is technically possible here? 

It seems that the call-back function is not being called for empty vectors?
