### ISSUE TITLE
how should i finetune  with bleu best model

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#344]
if i trained the model  update to 110000, but  the model 55000 if the BLEU best model.
so i want to finetune in model 55000,  did i just mv  model55000.npz to model.npz ？ but i found i can't recover the model.optimizer.npz to the model of 55000.

**Comment by snukky** [comment]
`model.npz.optimizer.npz` and `model.npz.progress.yml` can be removed if the model will be fine tuned on different training data.

**Comment by 520jefferson** [comment]
@snukky  i do what as you said, firstly i  remove model.npz.optimizer.npz and model.npz.progress.yml ,then cp model55000.npz  model.npz, then i start finetune program , after several Ep, then i found the BLEU score drop from 44.12 to 34.66, did I make a mistake?
