### ISSUE TITLE
display of git hash of build should be improved

### ISSUE THREAD

**Issue by frankseide** [marian-nmt/marian-dev#355]
We should improve logging of the git hash of the version. This currently has some problems:

* `version.h` is not reliably updated (i.e. it is not accurate)
* The log message is specifically talking about model creation, which is confusing.
* (Grammar error: should be "was created", not "has been created".)

Expected behaviour:

* `PROJECT_VERSION_FULL` should be up-to-date for every build.
* At startup, Marian should say something like `Marian v1.6.2+a80d102+, build date 2018-10-22`.
  * The '+' after the hash indicates that there are uncommitted changes.
  * We should include a build date because that is easier to understand than the hash.

Implementation considerations:

* The auto-generated source code should not be a header file, since any update will cause a rebuild of everything that depends on it. Better create `version.cpp` with `extern std::string g_projectVersionFull = "..."; extern std::string g_buildDate = "..."`.
* The auto-generation should first create a tmp file, compare that with the existing one, and only overwrite it if its content has changed. This avoids compiling it if nothing has changed. We should avoid that, because a `make` if nothing has changed must not run any `gcc` or linker, so that one can easily see whether anything has changed since the last build by just typing `make`.
* While we should include a build-date stamp, we should not include a time stamp, because otherwise, each `make` would see a different `version.cpp` file. Unless there is a way to get the time of the last change to any source file (which is what we really want here).

Here is a current output example. `git log` shows a latest commit of `723d2e` of this morning, and I just compiled that version. The hash shown in the message, however, is about 18 hours out of date. It is unclear under which circumstances it picks up a new hash.
```
[2018-10-24 11:38:01 17275] [config] Model is being created with Marian v1.6.2+15345a1
```

Example after reload from checkpoint (notice the grammar error, and confusing message that makes one ask what my current Marian version is)
```
[2018-10-24 03:13:14 118] [config] Loaded model has been created with Marian v1.6.2+a80d102
```

**Comment by frankseide** [comment]
I will give this a shot now

**Comment by emjotde** [comment]
I guess this is done now?

**Comment by frankseide** [comment]
Yes. It now reliably logs the git hash of the last commit. Example startup message:

    [2018-11-06 20:03:14 117] [marian] Marian v1.6.2 344bf53 2018-11-06 19:59:23 -0800

It works reliably. It has changed my work process a bit: I am no longer afraid of running multiple parallel jobs that differ in source code only, since I can now reliably refer back to the correct source code if needed (I did a few times).

What is missing is the change indicator (whether the source has been further modified compared to the last committed version). I work around by just committing every time before I submit a job.

Do you feel that is an additional useful feature to have, or should we decide to punt on it?

**Comment by emjotde** [comment]
A diff that's not reflected in commit history yet? Personally, I can survive without that if you can.

**Comment by frankseide** [comment]
It indicates that the commit hash in the log is not the full story, that information is missing. Unfortunately, the simple mechanism I use to get the git hash does not provide this change indicator, it seems more complex.

So we can punt on it for now.
