### ISSUE TITLE
bugs in check-pointing (SyncGraphGroup)

### ISSUE THREAD

**Issue by frankseide** [marian-nmt/marian-dev#356]
`SyncGraphGroup` has the following bugs in related to check-pointing:

* `SyncGraphGroup::load()` does not load the exponentially-smoothed model (`paramsAvg_`). If smoothing is enabled, the code would probably have to look like this:
```
// load main model file
for(size_t i = 0; i < graphs_.size(); i++)
  builders_[i]->load(graphs_[i], name);
// handle case of exponential smoothing
if (smoothing enabled) {
  // When smoothing, the main model file contains the smoothed parameters.
  // These must be swapped into the smoothed model which is sharded across MPI processes
  swapParamsAvg();
  // load non-smoothed model into the graphs
  for(size_t i = 0; i < graphs_.size(); i++)
    builders_[i]->load(graphs_[i], name + ".orig.npz");
}
```
* The `first_` flag should not be set when restarting from an existing model. Note that, due to the lazy initialization at places, it is not immediately obvious whether it is sufficient to simply add `first_ = false;` inside `load()`.

I also suggest to rename `load()` to `restore()`, to avoid future confusion as to what its purpose is.

**Comment by emjotde** [comment]
I just looked at the code, and it seems to me it gets reloaded in initializeAvg. 

```
  std::string name = options_->get<std::string>("model");
  if(filesystem::exists(name + ".orig.npz")) {
    // Load the averaged parameters into a temporary graph
    graphAvg = New<ExpressionGraph>();
    graphAvg->setDevice({0, DeviceType::cpu});
    graphAvg->load(name, false);
    graphAvg->forward(); // initialize parameters if needed
  }
```

**Comment by frankseide** [comment]
OK, so the main change needed here is to add a comment to `load()`:

// This function loads the main parameters in the graphs.
// In case of exponential smoothing, we also need to restore paramsAvg_.
// That is done lazily inside initializeAvg(), see there.

**Comment by emjotde** [comment]
Done
