### ISSUE TITLE
Is there a way yet to have CPU "devices" share models? 

### ISSUE THREAD

**Issue by ugermann** [marian-nmt/marian-dev#358]
I'm currently using binary models (converted with marian-conv) in a CPU-based marian server with multiple cpu threads. Out of the box, each device loads its own model, resulting in overall memory use for models of num_devices * model_size (each CPU counting as  device). At the MT Marathon in Prague Marcin mentioned that he was working on having devices share the same memory-mapped models (faster loading, less memory use). Is this available / working yet?

Also, model loading with binary files still seems to take on the order of several seconds per device. Is that to be expected, or is this a sign that I'm doing something wrong?

**Comment by emjotde** [comment]
It works and well. It's present in the code, but isn't exposed anywhere. We are using this internally in a custom server setting. I guess you will be at EMNLP/WMT and we can take a look at that then?

**Comment by emjotde** [comment]
You can take a look here:
https://github.com/marian-nmt/marian-dev/blob/master/src/microsoft/quicksand.cpp#L66
https://github.com/marian-nmt/marian-dev/blob/master/src/microsoft/quicksand.cpp#L80

The trick is to either map or preload into a common buffer a raw copy of the model and pass the pointer to the scorers. You can also reuse externally allocated workspace as shown here:

https://github.com/marian-nmt/marian-dev/blob/master/src/microsoft/quicksand.cpp#L93

You would just allocate the required memory (say 256MB) and assign to free workers. The reason this is not in normal Marian code, is that we do not have a portable memory-mapping implementation and do not want to introduce dependencies on boost. This also only works for CPU.

**Comment by ugermann** [comment]
Working on it, that's why I asked. Let's stick our heads together in Brussels about this.

I just googled around a bit: https://github.com/mandreyel/mio looks interesting, but I haven't played around with it yet.

**Comment by emjotde** [comment]
Oooh, shiny.

**Comment by kpu** [comment]
I could rip out https://github.com/kpu/kenlm/blob/master/util/mmap.cc which works on Linux, OS X, and Windows with `CreateFileMapping`.  Especially if you only care about the read-only bits.

**Comment by emjotde** [comment]
Have integrated mio for debugging. There is an #ifdef now in `translator.h` that can show how to use it. Closing this for now.
