### ISSUE TITLE
Incorrect use of ThreadPool

### ISSUE THREAD

**Issue by frankseide** [marian-nmt/marian-dev#359]
Various places misuse `ThreadPool` in that the pool is created and torn down right after. The point of a thread pool is to be kept around.

This causes issues with one configuration that runs out of thread ids (after many updates, validation fails with `Resource temporarily unavailable` (`EAGAIN`)). The main training (`SyncGraphGroup`) has already been fixed (at least in a branch), but not the scoring and translation functions.

* `Rescorer::run()` (why not just keep reusing the `ThreadPool` created in the constructor)
* `Validator` (five methods)
* `Translator::run()`
* `TranslateService::run()`

**Comment by emjotde** [comment]
I understand your internal PR solves this. So I am closing this issue and this will be resolved with the next merge.

**Comment by frankseide** [comment]
This has been addressed (and just merged) for `Validator` in our internal master, and therefore should go out on next sync.

I have not addressed it for the other cases, so let me reopen this so that it does not get lost.

**Comment by emjotde** [comment]
If I am not wrong, any of the `*::run()` functions is executed exactly once per process in which case the current usage of thread pool would be actually correct?

**Comment by frankseide** [comment]
Not for validate, which is called repeatedly during training (and was the one causing the problem). If the others are not, then the code should be fine, and we can close this.

**Comment by emjotde** [comment]
That's what I meant. Validate was called once per validation metric per validation step. The rest should just be called once from the main function of the binary. Closing then.
