### ISSUE TITLE
Reducing disk space usage

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian-dev#374]
How do I prevent model.iter100000.npz, model.iter200000.npz etc from being created during training? --overwrite ?

**Comment by emjotde** [comment]
Yes. I always use the `--overwrite --keep-best --valid-metrics perplexity` combo.

**Comment by hieuhoang** [comment]
ta

**Comment by emjotde** [comment]
Documentation is un clear, I assume:
```
--overwrite                                          Overwrite model with following checkpoints
```

**Comment by hieuhoang** [comment]
ya, it sounds like it  would affect the model
   Don't keep intermediate model files, overwrite as new models files are created. Reduces disk usage
