### ISSUE TITLE
Getting rid of boost in file_stream.h for temporary file handling

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#375]
We are trying to get rid of the last remaining pieces of boost. We are a bit stuck in this piece of code:
https://github.com/marian-nmt/marian-dev/blob/c1205c8c1dc0f1f491172879893082e8200b44b6/src/common/file_stream.h#L158
and
https://github.com/marian-nmt/marian-dev/blob/c1205c8c1dc0f1f491172879893082e8200b44b6/src/common/file_stream.h#L264

Boost knows how to create a stream from a file descriptor without closing the handle at destruction. We want to be able to keep the temporary file around for multiple reads and writes with our file streams. 

@kpu Do you have an idea how to get rid of boost calls here?

**Comment by kpu** [comment]
Sure one can fix temporary files, but the bigger problem is using Boost iostream to do gzip decompression in the same class.  Are you using `operator>>` for a lot of types or just a few?  

If it's few types then just implementing those types directly and bypassing istream will be a lot faster.  If if it needs to be generic then we do it with a `streambuf` override.

**Comment by emjotde** [comment]
Would be nice to be generic. The gzip compression is not too tragic, that's why I did not mention it. I started replacing this with a different library, but then hit the roadblock with those file descriptors. 

I think I looked at this lib for gzip: https://github.com/geromueller/zstream-cpp

**Comment by emjotde** [comment]
@kpu In branch `pathie` we now have this:

https://github.com/marian-nmt/marian-dev/blob/f8cc2a4677bcfdba8507b7a9ff480c0c7fc2d014/src/common/file_stream.h#L204

and

https://github.com/marian-nmt/marian-dev/blob/f8cc2a4677bcfdba8507b7a9ff480c0c7fc2d014/src/common/file_stream.h#L250

I got rid of the filtering_stream, what's left is descriptor handling and boost stream buffers for temporary files. Any hints?

**Comment by kpu** [comment]
I'm writing a simple streambuffer backed by an integer file descriptor.

**Comment by emjotde** [comment]
Great!

**Comment by emjotde** [comment]
You can use the `pathie` branch.

**Comment by snukky** [comment]
This issues is related to #251

**Comment by emjotde** [comment]
Actually done, nice.
