### ISSUE TITLE
Let's add a submodule reference to marian-regression-tests

### ISSUE THREAD

**Issue by frankseide** [marian-nmt/marian-dev#379]
Let's add a submodule reference to `marian-regression-tests`. The goal is that each branch has an associated version of the test suite.

For example, our internal master is a little behind the public master, but the test suite tests the changes made there. As a consequence, my work that branched off that internal master fails our test suite.

If we use a version-controlled submodule reference, updates to the tests won't negatively affect work on branches that are slightly out of date, while any merge from `master` would automatically pull in the appropriate up-to-date test suite.

**Comment by frankseide** [comment]
Is this done?

**Comment by emjotde** [comment]
yes
