### ISSUE TITLE
premature stopping

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian-dev#382]
This command seems to always terminate after 11 epoch/1 validation loop so BLEU is pretty crap
   marian -d 0 --mini-batch-fit -w 2000 --optimizer-delay 2 --mini-batch 1000 --maxi-batch 1000 --overwrite --keep-best --valid-metrics perplexity --valid-log valid.log --after-epochs 10 --log train.log -t train.clean-bpe.en train.clean-bpe.so --valid-sets dev.bpe.en dev.bpe.so --vocabs vocab.yml vocab.yml --early-stopping 10 -m model.npz

The training is pretty small (22k sentences). Also tried using --valid-script-path, and without --overwrite --keep-best but still stops too early. Also tried some previous versions of marian too. The settings are pretty similar to Barry's experiments on the same dataset which had respectable results

Can anyone spot an obvious error?

**Comment by emjotde** [comment]
You don't seem to use any type of regularization. Try experimenting with dropout.

**Comment by emjotde** [comment]
Not quite sure about this part either: ` -w 2000 --optimizer-delay 2`. What's the motivation?

**Comment by hieuhoang** [comment]
just copying an old run that seemed to work.

the problem arg seems to be  --after-epochs 10. I've replaced it with 
   --valid-freq 100u --early-stopping 20

**Comment by emjotde** [comment]
It guarantee you that regularization will help you. And the workspace/delay settings are cancelling each other out.

**Comment by hieuhoang** [comment]
ya, I've added dropout and killed the delay setting. It seems to be working for both large and small training runs, perplexity is steadily decreasing

I don't understand why workspace and delay are opposites, I thought workspace was just about GPU memory

  marian -d 0 -w 2000 --optimizer-delay 1 --mini-batch-fit --mini-batch 1000 --maxi-batch 1000 --overwrite --keep-best --valid-metrics perplexity --valid-log valid.log --log train.log --dropout-rnn 0.1 --dropout-src 0.1 --dropout-trg 0.1 --valid-freq 100u --early-stopping 20 -t train.clean-bpe.en train.clean-bpe.so --valid-sets dev.bpe.en dev.bpe.so --vocabs vocab.yml vocab.yml -m model.npz

**Comment by frankseide** [comment]
They are not. If you increase your workspace such that the minibatch size doubles, you can achieve the same thing by doubling the delay.

This assumes that you use ce-sum. Once you use averages, I cannot guarantee that there are no random factors that have slipped in, as with averages, it is impossible to keep things straight in the head. If you find a bug there, please do file it.

**Comment by hieuhoang** [comment]
cheers. It doesn't look like there's a bug, just didn't know how to choose a stopping criteria. Closing
