### ISSUE TITLE
Adding a --best-practice option

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#394]
I would like to add a `--best-practice` option to Marian which should serve as a short-cut to certain settings. For instance one value would be 
```
marian --best-practice transformer-big
```
which would correspond to
```
marian --model transformer \
--dim-emb 1024 --transformer-dim-ffn 4096 --transformer-heads 16 \
--enc-depth 6 --dec-depth 6 \
--transformer-postprocess dan --transformer-preprocess d \
--transformer-ffn-activation relu \
--transformer-dropout 0.1 --transformer-attention-dropout 0.1 --transformer-ffn-dropout 0.1 \
--learn-rate 0.0002 --lr-decay-sqrt-inv 8000 --lr-warmup 8000 --label-smoothing 0.1 \
```

Other values for best-practice might be combinations of the following and more:
```
- (rnn|transformer|rnn|lm|tranformer-lm)-(base|big)(-(low_resource|multi_source|...))?
- WMT17-en-de
- WMT18-en-de
- ...
```

Thoughts?

**Comment by hieuhoang** [comment]
It's a good idea. Our maybe a little program that asks done questions and gives you the command you can run. Then people can see exactly what they're getting

**Comment by emjotde** [comment]
ah, that's clever. `./marian-expert`

**Comment by kpu** [comment]
Presumably this would be tweaked over time.  So make it clear that it's not going to behave consistently across versions.

**Comment by frankseide** [comment]
An alternative would be to ship config files with these things. If you store them right next to the executable, then we can allow --config to find them, or a different option.

Baking these into the compiled binary feels opaque. On the other hand, explicit human-readable config files are a good basis for modification.

**Comment by emjotde** [comment]
@frankseide that's a good idea too.

**Comment by emjotde** [comment]
These options could be generated via `marian --best-practice=blabla --dump-config=minimal > myconfig.yml`

**Comment by emjotde** [comment]
@snukky What do other toolkits call these kind of options?

**Comment by snukky** [comment]
T2T calls it `--problem` (https://github.com/tensorflow/tensor2tensor#translation). Sockeye has an autopilot that uses `--model` (https://github.com/awslabs/sockeye/tree/master/sockeye_contrib/autopilot) . Fairseq seems to use `--arch` that stands for "architecture".

**Comment by emjotde** [comment]
Out of these I kinda like `--problem` best, the others don't mean anything.

**Comment by emjotde** [comment]
Ah, sockeye pulls this apart into two options, `--task` and `--model`, so it's rather `task` which is similar to T2T's `problem`.

**Comment by emjotde** [comment]
So, let's say we use `--problem`. @snukky can you prepare an example for me with the above option set?

**Comment by snukky** [comment]
We've finally added `--task`.
