### ISSUE TITLE
Don't output translation to stderr

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian-dev#396]
is there a way to stop the output
   [2018-11-30 13:20:29] Best translation 998:.....
I tried these args but no luck
   --quiet-translation --quiet --log-level off
Don't really need it to fill up the log when I have the translation in  stdout already

**Comment by emjotde** [comment]
Can pull the current version and try again? These options should actually do just that. I think there is one commit which has a bug that outputs stuff to stdout regardless, but I fixed that recently. 

Also, please post a full command where this happens for you.

**Comment by hieuhoang** [comment]
ah yes, pulling works
