### ISSUE TITLE
Add one-line installation instructions for all required packages for Ubuntu 14.04, 16.04, 18.04 to Readme

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#398]
Assuming a fresh Ubuntu LTS install, what are the required packages to get Marian to compile. This should be listed in a single apt-get command. Let's add this to the Readme.

**Comment by emjotde** [comment]
I am going to put a number of remarks here concerning the installation instructions. The "custom boost" section in written in imperatives. That looks as if custom boost was required. Instead we should make sure that the shipped default packages are probably fine, especially for Ubuntu 16.04 and 14.04. Have not tested 18.04.

**Comment by emjotde** [comment]
Similar with "Non-default CUDA". If the package that comes with Ubuntu is fine, we should not send people into installation hell. The current section again looks like a recommended section.

**Comment by emjotde** [comment]
In general the instructions are a bit to minimalist and therefore misleading.

**Comment by frankseide** [comment]
Looks this is what I need to install, besides CUDA and MPI:

`sudo apt-get install -y build-essential cmake libgoogle-perftools-dev zlib1g-dev libprotobuf9v5 protobuf-compiler libprotobuf-dev libboost-all-dev libssl-dev`

**Comment by emjotde** [comment]
@snukky what do we need libssl for?

**Comment by frankseide** [comment]
marian-server

**Comment by emjotde** [comment]
OK. OpenSSL is already optional. Should work without it.

**Comment by snukky** [comment]
This should be lists of recommended or required packages, or both? We may also publish our Dockerfiles.

BTW. We don't need `libboost-all-dev`, just some libraries.

**Comment by emjotde** [comment]
Let's go with libbost-all-dev for the moment, we will remove it soon anyway. For the moment, we can skip the docker files, we should get the basics right first. Currently that page is highly misleading. We are doing ourselves no favor.

**Comment by snukky** [comment]
Where do you want to have those lists of packages? README, marian-nmt.github.io/quickstart, marian-nmt.github.io/docs, or all of them?

**Comment by frankseide** [comment]
Let us get a single apt-get command that installs everything needed (the union of all configs). No ifs, no conditional installation if at all possible; rather install something that is not harmful but maybe not used in a specific configuration (e.g. if someone disables sentence piece).

CMake claims that if openSSL is not there, it won't build marian-server. If that CMake message is truthful, we either remove marian-server, or install openSLL in the default command.

**Comment by frankseide** [comment]
@snukky, let's not just list the packages, but rather give the exact command to copy-paste (assuming Ubuntu).

**Comment by emjotde** [comment]
We have slightly conflicting goals here. On one hand we want to have a minimal version that can run anywhere without install packages, then we have the defaults, which need some, but not all packages and the full tool which needs protobuf (for SentencePiece) and ssl (for server). The last ones are optional. 

This will take a while to get right.

**Comment by snukky** [comment]
Tested using Marian v1.7.4+3d8beb6 on nvidia/cuda dockers with pre-installed CUDA. A _minimal_ command compiles Marian without `marian-server`, SentencePiece, and TCMalloc. Default gcc and Boost versions provided in brackets. 

### Ubuntu 18.04 + CUDA 9.2 (gcc 7.3.0, Boost 1.65)

minimal:

    sudo apt-get install git cmake build-essential libboost-all-dev

full:

    sudo apt-get install libprotobuf10 protobuf-compiler libprotobuf-dev openssl libssl-dev libgoogle-perftools-dev 

### Ubuntu 16.04 + CUDA 9.2 (gcc 5.4.0, Boost 1.58)

minimal:

    sudo apt-get install git cmake build-essential libboost-all-dev zlib1g-dev

full:

    sudo apt-get install libprotobuf9v5 protobuf-compiler libprotobuf-dev openssl libssl-dev libgoogle-perftools-dev 

### Ubuntu 14.04 + CUDA 8.0 (gcc 4.8.4, Boost 1.54)

minimal:

    sudo apt-get install git cmake3 build-essential libboost-all-dev

full:

    sudo apt-get install libprotobuf8 protobuf-compiler libprotobuf-dev openssl libssl-dev libgoogle-perftools-dev

**Comment by emjotde** [comment]
We would probably need to comment on dist-specific default packages for CUDA too.

**Comment by erip** [comment]
Is the goal to catalog and minimize deps for use in Docker? It would be great to have a a docker image to use instead of trying to remember all the C++ I've forgotten, but having the above commands is helpful, too.

**Comment by snukky** [comment]
We have the instructions added on the website for some time, including Ubuntu 20.04. Closing
