### ISSUE TITLE
Resuming training seems broken at the moment. 

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#402]
Resuming training from a checkpoint seems broken at the moment. It seems the mechanism that checks for unexpected options in config files is choking on the "version" entry and aborts. 

Also the abort message does not inform which option is unknown, this needs to be changed.

How did that get through the regression tests?

**Comment by emjotde** [comment]
OK. It's a very specific situation where this happens, which means that normal training is unlikely to be affected:

* Train model until saving, no `version` entry in model.npz.yml, 
* Interrupt training
* Remove model.npz.yml, keep all other files, resume training with the same command line options as above.
* Train model until saving, `version` now appears in model.npz.yml !
* Interrupt training
* Resume training fails now because of `version` entry.

**Comment by snukky** [comment]
This should be fixed now: https://github.com/marian-nmt/marian-dev/blob/master/src/common/cli_wrapper.cpp#L184
