### ISSUE TITLE
Some regression tests seem to fail when Marian is compiled with g++-7

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#408]
Weird issue happening. When Marian is compiled with g++-7 (using CUDA 9.2 and 10.0) a number of regression tests is failing on Maxwell GPUs. Not confirmation for other GPUs yet. Not sure what is going on here. g++ 4.9, 5.3 and 6.4 are fine. 

Among them the following: 
tests/training/cost-functions/test_ce-mean.sh

**Comment by snukky** [comment]
There were small differences for some regression tests between Marian compiled with gcc7+ and with lower versions. We have switched to tests compiled with gcc8, so closing this issue.
