### ISSUE TITLE
marian-dev 1.7.0 build error

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#412]
Because i download the V1.7.0 zip file, i don't use git to clone.
when i extract the zip, and make build && cmake .. && make  ,then i get this as follows:
make[2]: *** No rule to make target '../.git/logs/HEAD', needed by '../src/common/git_revision.h'.  Stop.
CMakeFiles/Makefile2:102: recipe for target 'src/CMakeFiles/marian_version.dir/all' failed
make[1]: *** [src/CMakeFiles/marian_version.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

then i try git init, but i cann't figure out the problem if i download the zip and build .

**Comment by snukky** [comment]
Compilation from release .zip/.tar.gz assets doesn't work at the moment, please clone the repository specifying a version tag instead:

    git clone https://github.com/marian-nmt/marian-dev -b 1.7.0

A related issue: https://github.com/marian-nmt/marian/issues/177

**Comment by frankseide** [comment]
`git_version.h` is created as part of the build process (`make`, not `cmake`), to reflect the current git commit. Since it is dynamically generated, the file is not version-controlled.

**Comment by 520jefferson** [comment]
@frankseide  yes, but not everyone download marian throught git, in this case the git_revision.h won't be generated, so i think it's the problem.
