### ISSUE TITLE
Marian decoder produces garbage when the input file is a FIFO pipe

### ISSUE THREAD

**Issue by ugermann** [marian-nmt/marian-dev#425]
In bash, 
```
marian-decoder -c config.yml -i <(cat file)
```
should produce the same result as 
```
marian-decoder -c config.yml < file
```
(Let's just assume that the user has a good reason to do the former rather than the latter.)

Marian does not handle the first variant properly and produces garbage. The input reader should check (e.g. via S_ISFIFO(m) from sys/stat.h) if the input is  a regular file or a pipe.

**Comment by kpu** [comment]
It shouldn't check if the input is a pipe.  It should handle short reads correctly.

**Comment by frankseide** [comment]
I am curious what the log says as the input pathname.

**Comment by ugermann** [comment]
@frankseide /dev/fd/63
Explanation here: https://en.wikipedia.org/wiki/Process_substitution#Anonymous_named_pipe

**Comment by frankseide** [comment]
Thanks. @kpu, what do you mean? If we can read from stdin, why can't we read from any other pipe? Is it related to buffering? Or are we handling stdin in some special way?

**Comment by kpu** [comment]
Maybe this relates to what @fiqas has been seeing with validation BLEU resulting in short files on CSD3?

**Comment by ugermann** [comment]
I believe that aforementioned pull request solves the problem. Closing this issue for the time being, until there's evidence that said pull request doesn't solve the problem.
