### ISSUE TITLE
Error compiling cpu version on macOS

### ISSUE THREAD

**Issue by rbawden** [marian-nmt/marian-dev#430]
Hi! I've been trying to compile the CPU version of Marian on macOS (High Sierra), and have been getting errors involving pathie:

```
/Users/me/Documents/tools/marian-dev/src/3rd_party/pathie-cpp/src/pathie.cpp:150:5:` error: no matching function for call to 'libiconv'
    iconv(converter, const_cast<const char**>(&inbuf), &inbytes_left, &outbuf, &outbytes_left); // sets outbytes_left to 0 or very low values if not enough space (E2BIG)
    ^~~~~
/Users/me/anaconda3/include/iconv.h:81:15: note: expanded from macro 'iconv'
#define iconv libiconv
              ^~~~~~~~
/Users/me/anaconda3/include/iconv.h:83:15: note: candidate function not viable: no known conversion from 'const char *' to 'char *' for 2nd argument
extern size_t iconv (iconv_t cd,  char* * inbuf, size_t inbytesleft, char * outbuf, size_t *outbytesleft);
              ^
/Users/me/anaconda3/include/iconv.h:81:15: note: expanded from macro 'iconv'
#define iconv libiconv
              ^
/Users/me/Documents/tools/marian-dev/src/3rd_party/pathie-cpp/src/pathie.cpp:199:37: error: use of undeclared identifier 'fsencoding'
  return convert_encodings("UTF-8", fsencoding, utf8);
                                    ^
/Users/me/Documents/tools/marian-dev/src/3rd_party/pathie-cpp/src/pathie.cpp:224:28: error: use of undeclared identifier 'fsencoding'
  return convert_encodings(fsencoding, "UTF-8", native_filename);
```

Is there any way of providing support for Mac?

Thank you for you help!

**Comment by emjotde** [comment]
Good god. I will try to have a look... @hieuhoang are you still using Macs these days?

**Comment by kpu** [comment]
My understanding is @hieuhoang is not.

**Comment by emjotde** [comment]
```c++
#ifdef BSD
    // What the heck. FreeBSD violates POSIX.1-2008: it declares iconv()
    // differently than mandated by POSIX: http://pubs.opengroup.org/onlinepubs/9699919799/functions/iconv.html
    // (it declares a `const' where it must not be).
    iconv(converter, const_cast<const char**>(&inbuf), &inbytes_left, &outbuf, &outbytes_left); // sets outbytes_left to 0 or very low values if not enough space (E2BIG)
#else
    iconv(converter, &inbuf, &inbytes_left, &outbuf, &outbytes_left); // sets outbytes_left to 0 or very low values if not enough space (E2BIG)
#endif
```
This is happening in some seriously weird code. What happens if you set 
```#ifdef BSD```
to
```#if 0```

**Comment by emjotde** [comment]
Might be the author of Pathie didn't know that the BSD flag gets defined on Macs, he does seem to have a special APPLE flag. Let's see what happens here.

**Comment by hieuhoang** [comment]
Gave my mac paperweight away for a gpu laptop

Usually have to fiddle with the code to make it work

Hieu Hoang
Sent while bumping into things

**Comment by XapaJIaMnu** [comment]
I took a stab at fixing the compile errors in pathie to make it compile on mac one by one but eventually you get to the function: https://github.com/Quintus/pathie-cpp/blob/master/src/path.cpp#L906 which will just not work on mac and i have no idea what it attempts to do. Even after hacking it up, there's a further compilation issue with cmake link flags not available on Mac.

**Comment by rbawden** [comment]
So we had a go at commenting out some stuff to see whether it still might possible work...

In pathie.cpp, commenting out the ifdef BSD as follows:

```//#ifdef BSD
    // What the heck. FreeBSD violates POSIX.1-2008: it declares iconv()
    // differently than mandated by POSIX: http://pubs.opengroup.org/onlinepubs/9699919799/functions/iconv.html
    // (it declares a `const' where it must not be).
	// iconv(converter, const_cast<const char**>(&inbuf), &inbytes_left, &outbuf, &outbytes_left); // sets outbytes_left to 0 or very low values if not enough space (E2BIG)
	// #else
    iconv(converter, &inbuf, &inbytes_left, &outbuf, &outbytes_left); // sets outbytes_left to 0 or very low values if not enough space (E2BIG)
	// #endif
    errsav = errno;```

After doing this, we get 'Unsupported system' error from line 46 in entry_iterator.cpp. 
Commenting out this line (you never know), gave another  'Unsupported platform' error from line 936 in path.cpp i.e. in Path Path::exe()).

**Comment by XapaJIaMnu** [comment]
I added the necessary bits for Mac support in the pathie-cpp library here: https://github.com/XapaJIaMnu/pathie-cpp
I also added a pull request to master. Feel free to try my version.

Cheers,

Nick

**Comment by emjotde** [comment]
I guess I will merge with your fork first and then figure out what else they did in the normal repo. We might have small changes in our code for warnings etc.

**Comment by XapaJIaMnu** [comment]
This is not the only thing necessary to make it compile on Mac though. I'm not quite sure what other errors there are, as I don't have enough disk space on the ancient 2012 macbook air I am using to install all dependencies and compile marian. We can look into it with @rbawden

**Comment by emjotde** [comment]
Ah. In that case I would then prefer a full PR from you guys handling all of these.

**Comment by XapaJIaMnu** [comment]
Could you open a pull request with your fixes against pathie-cpp? The author seems to be fairly responsive about getting them into master and as far as i can see you do have a few. The current pathie code contains things such as: 

https://github.com/marian-nmt/marian-dev/blob/master/src/3rd_party/pathie-cpp/src/pathie.cpp#L181

Which result in a compile failiure on a modern compiler if the apple flag is ever set, due to `char* fsencoding = NULL;` being only ever declared in the windows codepath.

**Comment by lkluo** [comment]
any update?

**Comment by XapaJIaMnu** [comment]
Fixed in master
