### ISSUE TITLE
marian-scorer takes a "-train-set" as an argument for the file that needs to be scored.

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-dev#436]
When using LM rescoring, marian-scorer takes as an input `-train-set`, which is really confusing for anyone trying to figure out how to use it.  It should accept STDIN like marian-decoder or at least have an option `--input`.

**Comment by emjotde** [comment]
`stdin` is not trivial for multiple files. We should maybe be able to consume `*.tsv` files. That would be useful. We can add an alias, so scorer will accept `--input` and and `--train-set` for back-comp.

**Comment by emjotde** [comment]
@snukky wanna take a short at reading `*.tsv` files?

**Comment by snukky** [comment]
Closing. We have support for TSV files now, and the issue covers the same topic as #540
