### ISSUE TITLE
question: the result of translation contain poor words

### ISSUE THREAD

**Issue by wingsyuan** [marian-nmt/marian-dev#440]
Hi,
when I use the command : 
./build/marian-decoder -m model.npz -v vocab.en vocab.zh < input.txt
some src sentences from test file are translated as follow:
第十一
第十二
第十四

but the reference contents are as follow:
第十一 条 向 大气 排放 污染物 的 单位 ， 超过 规定 的 排放 标准 的 ， 应当 采取 有效 措施 进行 治理 ， 并 按照国家 规定 缴纳 超标准排污费 。 征收 的 超标准排污费 必须 用于 污染 防治 。
第十二 条 在 国务院 和 省 、 自治区 、 直辖市人民政府 划定 的 风景名胜区 、 自然保护区 和其他 需要 特别 保护 的 区域 内 ， 不 得 建设 污染 环境 的 工业 生产 设施 ； 建设 其他 设施 ， 其 污染物 排放 不 得 超过 规定 的 排放 标准 。 在 本法 施行 前 企业事业单位 已经 建成 的 设施 ， 其 污染物 排放 超过 规定 的 排放 标准 的 ， 限期 治理 。
第十四 条 因 发生 事故 或者其他 突然性 事件 ， 排放 和 泄漏 有毒 有害 气体 和 放射性物质 ， 造成 或者 可能 造成 大气 污染 事故 、 危害 人体健康 的 单位 ， 必须立即 采取 防治 大气 污染 危害 的 应急 措施 ， 通报 可能 受到 大气 污染 危害 的 单位 和 居民 ， 并 报告 当地环境 保护 部门 ， 接受 调查 处理 。

the marian may choose the shortest result for the best result, but  if I want  not the shortest result but sentence contain more information , what should I do ?
thanks very much!!!

**Comment by snukky** [comment]
I would recommend first checking the length of input sentences or if there are some iffy examples in the training corpus that might have misguided the model.

There are two parameters in Marian that may **slightly** impact the length of output sentences: `--max-length-factor`: larger values allows longer hypotheses are created in beam search, and `--normalize`: larger values >1.0 promote slightly longer sentences.

**Comment by wingsyuan** [comment]
@snukky  thanks very much!

**Comment by wingsyuan** [comment]
Hi,
@snukky 
when using marian-decoder I add the parameter --normalize with larger values >1.0 , the bleu score rise from  4.86 to 12.38, can you tell me what is the use of the parameter --normalize?
Thanks very much!

**Comment by snukky** [comment]
Such a low BLEU score usually indicates that a model is not trained properly. The option normalizes the scores w.r.t. to the length of the output sentence and using it sometimes improves BLEU a bit, but not so much.
