### ISSUE TITLE
What is the use of option "--seed"

### ISSUE THREAD

**Issue by wingsyuan** [marian-nmt/marian-dev#444]
Hi,
in wmt2017-transformer example, one of the options is as follow:
--seed $i$i$i$i

I know that four different models are trained , given different seed , and  can you tell me what is the role of the seed? if I  want to train only one model , can I exclude the seed option instead of giving it value? 
also  if I want to train one model with many epoches and every epoch base on different train-set as follows,  can I exclude the seed option? 

for i in $(seq 1 $k)  #k mean different epoches
do
    marian training
done

thanks very much!!!

**Comment by XapaJIaMnu** [comment]
This sets the random seed that is used to initialize the model. Using different random seeds is useful when training multiple ensembles. If you exclude the -seed option, a default random seed will be used.
