### ISSUE TITLE
ReLU not vectorizing on CPU

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#452]
@mateuszchudyk claims ReLU isn't vectorizing on CPU.  Probably the other Element operators are not either.  Should be a very simple `_mm512_max_ps` though it will need CPU model dispatch.  We've already got most of the stuff in `intgemm` to make that short to code.  

https://github.com/marian-nmt/marian-dev/blob/7c7f94c416dea09df1285bdd0614bea34de456e4/src/graph/node_operators_unary.h#L258

**Comment by emjotde** [comment]
I am in the process of doing a merge with our MS internal branch and my type-related things. A lot of things should vectorize there as I have specialized operators for tensors with sizes that are multiples of 4, 8, 16. ReLU probably still does not vectorize, anything else that has trivial float intrinsic should. 

I hope to finish the merge by next week. I will then publish.

**Comment by emjotde** [comment]
This should be done by now.
