### ISSUE TITLE
Model yaml files do not have relative paths

### ISSUE THREAD

**Issue by noe** [marian-nmt/marian-dev#460]
When training a model, the generated yaml files (e.g. `model.npz.decoder.yml`) do not contain relative paths, despite invoking `marian` with `--relative-paths`. The `relative-paths` entry in those yaml files is also `false`.

The version used is the newest master in marian-dev (84063a8475e51c2fedd604a2aecf0e79c528963e). It did not work either with an older version I was using (`v1.7.6 b6d7c56 2018-12-12 17:30:18 -0800`)

Note that `--relative-paths` was observed in the config file generated with `marian --relative-paths --dump-config ...` but not in the model yaml files generated by the training with the previously generated configuration file with `marian -c config.yml --relative-paths ...`.

**Comment by emjotde** [comment]
Oh yes. Good catch. Will add that soon.
