### ISSUE TITLE
Move sigmoid and weight in SSRU from applyState to applyInput

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#461]
In
https://github.com/marian-nmt/marian-dev/blob/master/src/rnn/cells.h#L1068
we are computing sigmoid(f) * cellState + (1-sigmoid(f)) * x.  But x and f are known in advance during `applyInput`.  Instead we should compute sigmoid(f) and (1-sigmoid(f)) * x in `applyInput`.  Then `applyState` turns into:
1. cellState elementwise multiply by pre-computed sigmoid(f)
2. Add pre-computed (1-sigmoid(f)) * x
3. ReLU

Which can probably be inlined into one kernel.

**Comment by emjotde** [comment]
Did anyone do anything here?

**Comment by kpu** [comment]
I think @mateuszchudyk  implemented in that way in the integer version but nothing has been done with floats.

**Comment by emjotde** [comment]
OK, then let's keep this open.

**Comment by mateuszchudyk** [comment]
https://github.com/marian-nmt/marian-dev/compare/ssru-precompute-sigmoid-and-part-of-highway

**Comment by emjotde** [comment]
Trying to remember, did wee establish in personal communication that is was in fact not an issue?

**Comment by kpu** [comment]
I think you should merge the change from @mateuszchudyk

**Comment by emjotde** [comment]
No PR?

**Comment by emjotde** [comment]
Ah, just that simple change, will take a look.

**Comment by emjotde** [comment]
I think we established in personal communication that this actually works as expected.
