### ISSUE TITLE
Marian produces empty translation 

### ISSUE THREAD

**Issue by ugermann** [marian-nmt/marian-dev#462]
When run marian-decoder with this model: 
http://data.statmt.org/germann/wmt19/models/de-en/tuned.iter3000.best-ce-mean-words.tar

on this input:
`
Auch Akademiker und Angestellte sind von Konjunkturschwäche und Digitalisierung betroffen.
`

the top translation is an empty string. I'm puzzled, because the rest of the n-best list looks reasonable. Does anyone have a good explanation what's happening here? I'm using the latest version of the master branch (84063a8475e51c2fedd604a2aecf0e79c528963e)

```
echo 'Auch Akademiker und Angestellte sind von Konjunkturschwäche und Digitalisierung betroffen.' | ./marian-decoder -c model/decoder.yml --n-best --log-level critical
0 |||  ||| F0= -1.18324 ||| -1.18324
0 ||| Even academics and employees are affected by economic slowdown and digitalization. ||| F0= -8.15704 ||| -1.54547
0 ||| Even academics and employees are affected by economic slowdown and digitization. ||| F0= -8.58838 ||| -1.56907
0 ||| Even academics and employees are affected by economic weakness and digitalization. ||| F0= -8.23043 ||| -1.62094
0 ||| Even academics and employees are affected by economic weakness and digitization. ||| F0= -8.64039 ||| -1.63705
0 ||| Academics and employees are also affected by economic slowdown and digitalization. ||| F0= -9.01087 ||| -1.64626
0 ||| Even academics and employees are affected by slowdown and digitalization. ||| F0= -8.3941 ||| -1.65318
0 ||| Academics and employees are also affected by economic slowdown and digitization. ||| F0= -9.40875 ||| -1.66099
0 ||| Even academics and employees are affected by slowdown and digitization. ||| F0= -8.82843 ||| -1.67267
0 ||| Also academics and employees are affected by economic slowdown and digitalization. ||| F0= -8.9353 ||| -1.69292
0 ||| Also academics and employees are affected by economic slowdown and digitization. ||| F0= -9.34116 ||| -1.7066
0 ||| Even academics and employees are affected by weakness and digitalization. ||| F0= -8.7538 ||| -1.79688
```

**Comment by emjotde** [comment]
Try tuning length normalization with e.g. `--normalize 1`. This looks like a not particularly well-trained model where the empty string is an acceptable output. When you use length normalization it will divide the score by number of words produced (1 => eos) to the power of the normalization factor. It will then sort by this new score. In that case the per symbol probability of the empty sequence should be quite a bit lower than in the other cases.

**Comment by ugermann** [comment]
Thanks, @emjotde. That indeed pushes the empty string down in the ranking. Glad to see that it's a model error rather than a bug in the decoder.
