### ISSUE TITLE
Used "-USE-MPI=ON" but Compiled without MPI support

### ISSUE THREAD

**Issue by leiguo2018** [marian-nmt/marian-dev#463]
I  compiled Marian as follows:

`cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_SENTENCEPIECE=ON -USE_MPI=ON`

Then I got the following information:

> -- The CXX compiler identification is GNU 5.4.0
> -- The C compiler identification is GNU 5.4.0
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Project name: marian
> -- Project version: v1.7.6+1d4ba73
> -- Checking support for CPU intrinsics
> -- SSE2 support found
> -- SSE3 support found
> -- SSE4.1 support found
> -- AVX support found
> -- AVX2 support found
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "8.0") 
> -- Found CUDA libraries: /usr/local/cuda/lib64/libcurand.so /usr/local/cuda/lib64/libcusparse.so /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
> -- Found Tcmalloc: /usr/lib/libtcmalloc_minimal.so
> -- Found MKL: /opt/intel/mkl/lib/intel64/libmkl_intel_ilp64.a;/opt/intel/mkl/lib/intel64/libmkl_sequential.a;/opt/intel/mkl/lib/intel64/libmkl_core.a  
> -- Using std::regex
> -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")  
> -- Found OpenSSL
> -- Found Boost: /usr/local/include (found version "1.65.1") found components:  timer iostreams filesystem system chrono regex 
> -- VERSION: 0.1.6
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "2.6.1") 
> -- Found TCMalloc: /usr/lib/libtcmalloc_minimal.a
> -- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.16") found components:  doxygen dot 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /mnt/data/home/gl/marian/build

I didn't find information about MPI, which I don't know if this is wrong.
Then I run:

`make -j 8`

Compiled successfully.
When I tried the following command line:

```
mpirun -n 1 --hostfile $SCRIPTS/hosts_mpi -tag-output \
    $ROOT/marian/build/marian --type transformer \
        --devices  0:0 1:0 \
        --multi-node --multi-node-overlap 0 \
        --model $MODEL/t1.npz \
        ...
        --mini-batch-fit -w 10000 --mini-batch 1000 --maxi-batch 1000 --sync-sgd --optimizer-delay 2 \
```

I got errors:

> [1,0]<stderr>:[2019-07-10 10:48:19] Compiled without MPI support. Falling back to FakeMPIWrapper
> [1,0]<stderr>:[2019-07-10 10:48:19] Error: mal-formed device config array??
> [1,0]<stderr>:[2019-07-10 10:48:19] Error: Aborted from void marian::MultiNodeGraphGroupBase::loadDeviceConfig(std::vector<long unsigned int>) in /data/work/marian/src/training/graph_group.h:179
> [1,0]<stderr>:
> [1,0]<stderr>:[CALL STACK]
> [1,0]<stderr>:[0x65a061]          marian::MultiNodeGraphGroupBase::  loadDeviceConfig  (std::vector<unsigned long,std::allocator<unsigned long>>) + 0x671
> [1,0]<stderr>:[0x65b9be]          marian::MultiNodeGraphGroupBase::  MultiNodeGraphGroupBase  (std::shared_ptr<marian::Options>) + 0x38e
> [1,0]<stderr>:[0x65e433]          std::shared_ptr<marian::MultiNodeGraphGroupSync> marian::  New  <marian::MultiNodeGraphGroupSync,std::shared_ptr<marian::Options>&>(std::shared_ptr<marian::Options>&) + 0x53
> [1,0]<stderr>:[0x662697]          marian::Train<marian::MultiNodeGraphGroupSync>::  run  () + 0x227
> [1,0]<stderr>:[0x59de26]          mainTrainer  (int,  char**)                        + 0x1b6
> [1,0]<stderr>:[0x57c1da]          main                                               + 0x8a
> [1,0]<stderr>:[0x7eff63cdd830]    __libc_start_main                                  + 0xf0
> [1,0]<stderr>:[0x59b4b9]          _start                                             + 0x29
> [1,0]<stderr>:
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun noticed that process rank 0 with PID 4513 on node node1 exited on signal 6 (Aborted).

I installed openmpi-4.0.1 on my machine. And my host file is:

> $ cat hosts_mpi
> node1
> node2

How can I successfully compiled Marian with openMPI? 
What did I do wrong about this error?
> Error: mal-formed device config array??

**Comment by snukky** [comment]
Please try `-DUSE_MPI=ON`.

**Comment by leiguo2018** [comment]
> Please try `-DUSE_MPI=ON`.

I run `cmake -LH -N` from the build directory and I saw this:

> // Use CUDNN library
> USE_CUDNN:BOOL=OFF
> 
> // Use MPI library
> USE_MPI:BOOL=OFF
> 
> // Use NCCL library
> USE_NCCL:BOOL=ON
> 
> // Download and compile SentencePiece
> USE_SENTENCEPIECE:BOOL=ON
> 
> // Link statically against non-system libs
> USE_STATIC_LIBS:BOOL=OFF

which made me simply copy `USE_MPI` from what I saw. I look stupid. And I still can't find a way to make the format of deviceConfig right. Change
`--devices  0:0 1:0`
to
`--num-devices 1`
works.

**Comment by lkfo415579** [comment]
@leiguo2018  i met the same question. (mal-formed device config array??)
is the MPI training not completed yet?
i tried only using `--num-devices 1` parameter but it pops `Error: the argument '0' for option '--devices' is invalid. Supported format for multi-node setting: '0:0 1 2 3 1:0 1 2 3'`

can someone tell me how to use mpi-trianing correctly?

**Comment by leiguo2018** [comment]
> @leiguo2018 i met the same question. (mal-formed device config array??)
> is the MPI training not completed yet?
> i tried only using `--num-devices 1` parameter but it pops `Error: the argument '0' for option '--devices' is invalid. Supported format for multi-node setting: '0:0 1 2 3 1:0 1 2 3'`
> 
> can someone tell me how to use mpi-trianing correctly?

@lkfo415579 Did you follow this [instructions](https://marian-nmt.github.io/docs/#multi-node-training)? Try this. 
I have successfully implemented multi-node training on two servers using MPI. However, the training speed on two servers with one GPU separately is even slower than on one server with only one GPU. I gave up using multi-node training and finished my training using one server with two GPUs.

**Comment by frankseide** [comment]
I think `--multi-node` is not really supported anymore, it is a legacy implementation that we have not run for a while.

Without NCCL/Infiniband, I would not expect multi-node training to give you much speed-up.

**Comment by kpu** [comment]
You could action the pull request https://github.com/marian-nmt/marian-dev/pull/420
