### ISSUE TITLE
Marian not replacing back the URL-0

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#464]
Previously models trained decoded the URL as they are but later models trained were returning the `URL-0`. Is that the expected behavior of the latest marian? 

E.g. source:

```
プレスリリース : https://corp.rakuten.co.jp/news/press/2017/1213_02.html
```

Target:

```
Press Release: URL-0
```

**Comment by emjotde** [comment]
Hi,
Marian has no functionality that would cause that. Rather check your training data.

**Comment by emjotde** [comment]
No mention of "URL" in any C++ code :)
https://github.com/marian-nmt/marian-dev/search?q=URL&unscoped_q=URL

**Comment by alvations** [comment]
Thanks @emjotde! 

I think I know where that awkward `URL-0` data is coming from already (*cough lisbon people) =)

**Comment by emjotde** [comment]
Those guys are the worst! :P

**Comment by alvations** [comment]
Just in case anyone else is using data from the Lisbon people, other than the `URL-0` and `URL-*` bugs, note the following:

 - They annotated within the text most probably for QE work or something but they didn't remove it when they returned the translations, e.g. `<span class="uannot dict" data-uannot-id="5asdeabcded18a4386fdfbf7" data-original="stories`

 - Also they joint split up the sentences in a paragraph/doc for translations but when they join up, they didn't pad the translations with spaces -_-, e.g. `This is a first sentence.This is the next`. 

 - The source-target alignments sometimes messed up big time, the translations are there but they are not in the order of the source file =(

Just putting it out, just in case anyone else is getting data from the Lisbon people's to train their models and see weird translations in their model...
