### ISSUE TITLE
How to train an transformer-based language model

### ISSUE THREAD

**Issue by wingsyuan** [marian-nmt/marian-dev#465]
Hi,
How can I train an transformer-based language model and use this language model to calculate the perplexity of each sentence of the test set? Can you provide some examples?

Thanks a lot!

**Comment by snukky** [comment]
Here is an example from our regression tests for training and scoring with a Transformer-based LM:
* https://github.com/marian-nmt/marian-regression-tests/blob/master/tests/training/models/lm/test_lm-transformer.sh#L10
* https://github.com/marian-nmt/marian-regression-tests/blob/master/tests/training/models/lm/test_lm-transformer.sh#L27

**Comment by wingsyuan** [comment]
@snukky 
Thanks a lot!!!

**Comment by emjotde** [comment]
Seems this can be closed.
