### ISSUE TITLE
How to represent each source sentence as a vector with fixed-lenth with marian-decoder ?

### ISSUE THREAD

**Issue by wingsyuan** [marian-nmt/marian-dev#468]
Hi,

in an attentional NMT system includes a bidirectional  recurrent neural network as an encoder and a forward recurrent neural network as a decoder ,each source sentence is represented as the annotationsH = {h1, . . . , hTx}, Tx is the length of a source sentence,so after training one epoch,each input/source sentence can be represent as a vector with  fixed-length, the initial hidden state in the decoding layer, whose length is fixed.

here is my question:
how to represent each source sentence as a vector with fixed-lenth with marian-decoder after training some epoches?
or Can marian output each sentence embedding like bert after training some epoches?

thanks a lot!!!

**Comment by emjotde** [comment]
Hi,
This is not something we support at the moment. You would need to hack this yourself if this is required. I think marian-scorer might be the better tool to modify for that if only need the states and not the translations.
