### ISSUE TITLE
spm_train built with marian compilation crashes

### ISSUE THREAD

**Issue by ugermann** [marian-nmt/marian-dev#477]
```
git clone https://github.com/marian-dev 
cd marian-dev
mkdir build
cd build
cmake -DUSE_SENTENCEPIECE=on ..
make -j
./spm_train -h
```
results in a segmentation fault.

If I build sentencepiece directly from the submodule like so:
```
mkdir build.sp
cd build.sp
cmake ../src/3rd_party/sentencepiece
make -j
src/spm_train -h
```

spm_train works as expected.

So something is wrong with the way the marian cmake setup compiles sentencepiece.

**Comment by emjotde** [comment]
Fascinating. Looking.

**Comment by emjotde** [comment]
#478 fixes this case of shared linking (default). With `cmake .. -DUSE_STATIC_LIBS=on` we will have the bug occuring again, but it seems to be some issue in SentencePiece or even more likely Protobuf?
