### ISSUE TITLE
Separate GPU code from CPU code

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#49]
Refactor code in order to separate GPU code from CPU code as far as this is painlessly possible without major rewrites. One way would be to hide includes to cuda code in *.cu files that really require this. For instance anything that include ExpressionGraph needs to be a *.cu file now when compiling into executable code. Would be good if it could remain a *.cpp file. 

This would be a first step towards different back-ends which would require more extensive rewrites. This should be more of a clean-up.

**Comment by AngusL** [comment]
I'm not sure how urgently you want to make this change, but @sidkashyap and I have a patch which does this, at least partially. I'm currently updating it with your latest additions, but can probably share it with you later this week (although it can't hit GitHub until it passes an internal review, which should be mostly straightforward but might encounter a couple snags).

**Comment by emjotde** [comment]
Oh, that's cool. How about a private github repo?
