### ISSUE TITLE
marian-dev 1.7 training log error 

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#504]
![image](https://user-images.githubusercontent.com/5691554/65209109-a69b7b80-dac9-11e9-8a34-a61286c7def5.png)
 
when i train with v1.6, epoch 1 just read 668w data, then epoch 2 will shuffle again. but the total data is 7300w+. is there anything wrong with this ?

![image](https://user-images.githubusercontent.com/5691554/65209176-e19daf00-dac9-11e9-92cd-b74bd2562175.png)

**Comment by emjotde** [comment]
You probably have sentences in there that are longer than what you have set for `--max-length` or there are empty lines. Both will be omitted during training, but not during shuffling. Maybe you want to increase your `--max-length`.

**Comment by 520jefferson** [comment]
@emjotde  i set max-length is 100, and i find the total sentences less than 100 are 72910224 bitexts.
(cat input  | awk '{n=split($0,a," ");if(n<100) print n}' |wc -l)
i use the training setting of v1.6, is there any difference between v1.6 and v1.7?

**Comment by emjotde** [comment]
No, that should be the same behavior forever. What about both sides of the corpus? How about empty lines?

**Comment by 520jefferson** [comment]
no, the empty lines have been deleted. is there anything willl interrupt the training process.

**Comment by emjotde** [comment]
Too small temp space maybe? But that should throw warnings. Which version exactly are you using?

**Comment by 520jefferson** [comment]
i use v1.6, i can train in a single linux server with 6gpus and output log is normal,  but i can train in a sgi gpu server i get these error. 

i try with v1.7 in sgi server but i get error below:

 562 [2019-09-18 17:19:03] Training started
 563 [2019-09-18 17:19:03] [data] Shuffling data
 564 [2019-09-18 17:19:36] [data] Done reading 73013205 sentences
 565 [2019-09-18 17:20:02] Error: Error writing to file '.'
 566 [2019-09-18 17:20:02] Error: Aborted from marian::io::OutputFileStream& marian::io::operator<<(marian::io::OutputFileStream&, std::ostream& (*)(std::ostream&)) i     n marian-dev-1.7.0/src/common/file_stream.h:283
 567
 568 [CALL STACK]
 569 [0x731e81]          marian::data::Corpus::  shuffleData  (std::vector<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>,std::allocator     <std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>>> const&) + 0x1a21
 570 [0x663368]          marian::Train<marian::SyncGraphGroup>::  run  ()   + 0xf68
 571 [0x5933ea]          mainTrainer  (int,  char**)                        + 0x2ca
 572 [0x570f0a]          main                                               + 0x8a
 573 [0x7f44beecc830]    __libc_start_main                                  + 0xf0
 574 [0x590c09]          _start                                             + 0x29

**Comment by emjotde** [comment]
Yes, that's a new check, I think you temp space is too small and the previous version did not check that. Try setting tempspace to a drive/folder that has more space via `-T path/to/folder`

**Comment by 520jefferson** [comment]
Okay, i will try that. Is there anything like lower speed to much if i use -T path/to/folder

**Comment by emjotde** [comment]
Don't think so. You can also shuffle in RAM, that will be faster `--shuffle-in-ram`
