### ISSUE TITLE
[Question] Non-autoregressive decoder

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#506]
Just to check, is anyone working on non-autoregressive decoder in Marian?

E.g. https://arxiv.org/pdf/1802.06901.pdf or https://openreview.net/pdf?id=B1l8BtlCb ?

And now: https://github.com/zomux/lanmt =)

**Comment by emjotde** [comment]
We looked at that whole non-autoregressive craze. Not convinced for now.

**Comment by emjotde** [comment]
The paper from openreview is godawful.

**Comment by alvations** [comment]
O(1) beats O(n) any time =)

I guess I'll take it as no one is working on that in Marian?

**Comment by emjotde** [comment]
It really doesn't. I am half convinced we are as fast with O(n) as they report for O(1). Without the castastrophic BLEU losses. Their model is ridiculously tiny.

**Comment by emjotde** [comment]
We are looking at it. Not even remotely deployable in my opionion.

**Comment by alvations** [comment]
Part of the reason why we're asking is because we're getting 145 secs to decode 130 lines (with 2768 reference tokens in total) with 30 CPU threads and with 1 GPUs 8 secs to decode the same, and 4 secs to decode with 4 GPU. Using a transformer base with beam 6. 

Anything to slice that time 145 secs by a factor would be considered, throwing about BLEU is much a problem if that 145 secs is beyond deployable hahaha.. Already resorting to beam size 1 and it cuts down to 32 seconds. 

That's why in that case, as long as it goes below 32 seconds and BLEU remains or is higher than beam size 1, it already beats "deployable" model, lol.

**Comment by emjotde** [comment]
Our submission to the WNGT shared task is going to be online soon. We do a whole WMT test set with a transformer-base dimensioned model in less than 50s on a single CPU thread.

**Comment by emjotde** [comment]
Closing.
