### ISSUE TITLE
Custom dictionary for lexical shortlist 

### ISSUE THREAD

**Issue by okgrammer** [marian-nmt/marian-dev#507]
Is it possible to provide a custom dictionary for the lexical shortlist feature (instead of word alignment from fast_align)? For example, I may have a dictionary of named entities and their translations and want to put a constraint in decoding according to this dictionary.

**Comment by emjotde** [comment]
Hi, 
not really, this short list will then only allow to output your named entities, nothing else. This could only be used for black-listing by removing certain words from it.

**Comment by okgrammer** [comment]
Hello, thanks for your reply. In that case, how would you recommend to put translation constraints for named entities during decoding? That is, if I have an entity X in the source sentence, I want it to be forcefully translated to Y (according to some dictionary), regardless of the context.

I was trying the placeholder feature in xml-merge branch in marian-dev, but it seems that this feature doesn't guarantee that the specified translation (`<ne translation="xxx">`) will get picked during decoding. For example, if the word is not in the target dictionary or the word receives low score, then it will not appear in the translation output.

**Comment by emjotde** [comment]
We currently do not have that option. We use placeholder symbols which we then replace outside of Marian. 

There is a nice paper: https://www.aclweb.org/anthology/P19-1294/
This is likely superior to hard contraints and I would apply this method. Good thing, doesn't not require and code changes. 

Closing.
