### ISSUE TITLE
C++17 support

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#509]
NVCC doesn't officially support C++17 but modern cmake shipped with Ubuntu/Debian does. 

When building NCCL, building with C++17 seems to work but when marian tries to compiles NVCC  with c++17, it's not supported thus the break. 

Would it be okay if we start a branch that can support C++17? 

**Motivation:** We did find some speed ups (though not heavily/properly benchmark) when using C++ 17 optionals queue functions during inference

**Comment by emjotde** [comment]
Hi, can you clarify or edit the issue? It seems you are mixing up NVCC and NCCL?

**Comment by alvations** [comment]
Hmmm, maybe a PR on our "modified" cmake might help. 

We use C++17 features in `src/translator/history.h` and it showed some gains in a version sometime from March 2019. Then when we try to sync our fork the a bleeding edge the CMake files structure changed and it looks like it's building NCCL, then tried to build NVCC later too. 

Which in March's version there isn't an NVCC build, it was using whatever was available native to the machine.

Perhaps a PR would help =)

**Comment by emjotde** [comment]
You are building custom NVCC?

**Comment by alvations** [comment]
Turns out, yes, my messup cmake did that! 

Clean it up and patched that part by not propagating the `-std=c++17` everywhere, it works now and still we have some contributions for a PR =)

In a minute.
