### ISSUE TITLE
[Question] Is layer normalization used when decoding for the `--type transformer` models?

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#518]
When checking our yml during decoding and training, we find `layer-normalization: false`.

But within the trained model, we find `*_ln_bias_pre` and `*_ln_scale_pre` vectors that are non-zeros or non-ones. 

But the default behavior of the dense layers seems to be also leave the layer un-normalized at https://github.com/marian-nmt/marian-dev/blob/master/src/layers/generic.h#L176

In the transformer, the layer norm seems to be applied regardless of the arguments set in the CLI for `--layer-normalization`, https://github.com/marian-nmt/marian-dev/blob/master/src/models/transformer.h#L191 

Does the `--layer-normalization` only affect the `s2s` and `amun` and `nematus` models?

**Comment by emjotde** [comment]
Last comment is correct. Layer-norm in transformer is addressed via --transformer-post-process dan (dropout - add - normalize). This follows other implementations. Wondering if we should clean this up somehow.
