### ISSUE TITLE
Dropping support for CUDA 8.0?

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#552]
Hi,
I would like to drop support for CUDA 8.0 and make CUDA 9.0 the new minimal requirement. Any objections?

The reason is that CUDA 9.0 introduced quite a bit of syntactic sugar for kernel primitives. If we want to use these we would need to maintain a parallel kernel version for out-of-date CUDA 8.0 which is not doable. The new primitives are really nice though.

**Comment by tomekd** [comment]
We could assume that marian-nmt officially supports the last two major versions of CUDA (it is 10.X and 9.X now).

**Comment by emjotde** [comment]
@tomekd that's a really good story.

**Comment by emjotde** [comment]
Since no one complained I am considering it dropped. Update coming.
