### ISSUE TITLE
Marian won't compile on older CPUs (up to and including westmere)

### ISSUE THREAD

**Issue by ugermann** [marian-nmt/marian-dev#559]
... apparently that's because those architectures don't support -mavx.

@snukky try compiling on hel. Won't work with
```
cmake -DCOMPILE_CUDA=off ..
```

**Comment by emjotde** [comment]
Is Cmake determining it should support avx?

**Comment by snukky** [comment]
From hel:

```
-- Checking support for CPU intrinsics
-- Could not find hardware support for AVX on this machine.
-- Could not find hardware support for AVX2 on this machine.
-- Could not find hardware support for AVX512 on this machine.
-- SSE2 support found
-- SSE3 support found
-- SSE4.1 support found
-- SSE4.2 support found
```

```
cat /proc/cpuinfo | grep 'model name' | uniq
model name      : Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz
```

**Comment by emjotde** [comment]
Huh, so, where is `-mavx` coming from?

**Comment by ugermann** [comment]
The point is that the code won't compile UNLESS the CPU supports AVX.
I get a lot of this: 

```
...
/home/germann/marian-dev.master/src/3rd_party/avx_mathfun.h: In function ‘v8si avx2_mm256_slli_epi32(v8si, int)’:
/home/germann/marian-dev.master/src/3rd_party/avx_mathfun.h:129:55: error: AVX vector return without AVX enabled changes the ABI [-Werror=psabi]
...
```

**Comment by ugermann** [comment]
This may turn into a problem for Bergamot, as some cheaper Intel CPUs apparently don't support AVX.

**Comment by emjotde** [comment]
Ah. the right #ifdefs should solve this.

**Comment by emjotde** [comment]
Is it compiling with -DCOMPILE_CPU=off ?

**Comment by ugermann** [comment]
Nope. Can't test directly on any of our westmere machines, because those don't have GPUs and therefore no CUDA libraries installed, so -DCOMPILE_CUDA=off -DCOMPILE_CPU=off is probably a non-starter on them.

Tested instead on snotra (sandybridge) with 
```
-DBUILD_ARCH=westmere -DCOMPILE_CPU=off
```

Logs are attached. 

[cmake.log](https://github.com/marian-nmt/marian-dev/files/3917962/cmake.log)
[make.log](https://github.com/marian-nmt/marian-dev/files/3917959/make.log)

**Comment by emjotde** [comment]
I don't have access to that kind of hardware. You should be able to cook something up looking at the COMPILE_CPU and cOMPILE_CUDA ifdefs. I suspect most of what's needed is already there.

**Comment by ugermann** [comment]
Your account on Valhalla is still valid, so you do have access to that kind of hardware.
Also, do you really need it, shouldn't -DBUILD_ARCH=... do the trick?

**Comment by emjotde** [comment]
Tell that to Nvidia :)

**Comment by ugermann** [comment]
Why is Nvidia involved when Marian is compiled without CUDA?

**Comment by emjotde** [comment]
Oh, you mean I can simulate that environment, I misunderstand. 

And they are involved because of all the compile guards I have to add to not clash with intrinsics that nvcc doesn't like. It just becomes a mess.

Anyway, happy to accept a PR though.

**Comment by ugermann** [comment]
Lack of AVX support is not just a legacy issue. The Intel Celeron N4000 (from late 2017) still doesn't support AVX apparenty (https://www.notebookcheck.net/N4000-vs-7130U_9426_9178.247596.0.html).

I'm not going to fix this. @kpu may want to chime in on this, as it might break Marian for Bergamot.

**Comment by kpu** [comment]
Bergamot does need to support older CPUs.  I would like to point out that this could be turned into a fat binary ala intgemm.
```
   AVX implementation of sin, cos, sincos, exp and log

   Based on "sse_mathfun.h", by Julien Pommier
   http://gruntthepeon.free.fr/ssemath/
```

**Comment by kpu** [comment]
I also doubt we need that accurate of an approximation @mateuszchudyk feel like doing some operator wrapping?

**Comment by emjotde** [comment]
Shouldn't be too hard to fix. I am not wrong this is only used for forced vectorization in element-wise kernels. Seems like these ifdefs need some more protection:

https://github.com/marian-nmt/marian-dev/blob/f007772a496e7aca5b2a91407534314f606a7e40/src/functional/operators.h#L196

**Comment by emjotde** [comment]
Also here:
https://github.com/marian-nmt/marian-dev/blob/f007772a496e7aca5b2a91407534314f606a7e40/src/tensors/cpu/element.h#L84

We are already protecting against compiling this with nvcc that doesn't understand the intrinsics in some cuda versions. Should be enough to turn this into some global macro that evaluates if intrisics should be compiled or not.

**Comment by XapaJIaMnu** [comment]
GCC 9.2 Works with Cuda 10.2 Tested on my machine

Cheers,

Nick

**Comment by ugermann** [comment]
Sorry, still doesn't work for me. @XapaJIaMnu: try this on elli
```
cmake -DBUILD_ARCH=westmere /path/to/marian/master/checkout
make 
```
Works with sandybridge (which supports AVX) but not with westmere (which doesn't).

**Comment by XapaJIaMnu** [comment]
> Sorry, still doesn't work for me. @XapaJIaMnu: try this on elli
> 
> ```
> cmake -DBUILD_ARCH=westmere /path/to/marian/master/checkout
> make 
> ```
> 
> Works with sandybridge (which supports AVX) but not with westmere (which doesn't).

Yes, that will not work. I have added the AVX switch here: https://github.com/marian-nmt/marian-dev/blob/master/CMakeLists.txt#L121

This will only be triggered if the CPU you are compiling on does not support AVX.  E.G. Try compiling on hel with `-DCOMPILE_CUDA=OFF` and it will work. For elli, you probably want to pass `-DNO_AVX` directly. I am not sure if we want to spend the time to refactor the codebase so that there is dynamic CPU dispatch for every single vector instruction.

**Comment by kpu** [comment]
GCC, clang, and even visual studio define `__AVX__` and `__AVX2__` if they're compiling in a way that supports those instructions.  Just use those macros.  There's no need to roll your own.

**Comment by ugermann** [comment]
Compiles with BUIILD_ARCH=westmere and even BUILD_ARCH=x86-64 now. Good for the time being, but in the long run it would be nice for the code path to be chosen at run time rather than compile time, but that's a separate (though related issue).

**Comment by XapaJIaMnu** [comment]
> Compiles with BUIILD_ARCH=westmere and even BUILD_ARCH=x86-64 now. Good for the time being, but in the long run it would be nice for the code path to be chosen at run time rather than compile time, but that's a separate (though related issue).

@ugermann this is likely impossible without a veeery major refactoring. And a change in how we are compiling.

At the moment, we are compiling with `--march=native` which means that we are very likely to have things vectorised even in non performance critical parts and if we run on a different CPU from the one that the code was compiled for, we'd get an illegal instruction. To get around that we need to compile with something like `march=sse2` or `sse4.1` and annotate performance critical function with the proper architecture... 

BUT, the correct way to do that (function multiversioning) is buggy on all the compilers, so the only way to make sure it works, would be to use function pointers to initiate with CPU specific version of the function at runtime. I don't think anybody would be willing to do the refactoring necessary...
