### ISSUE TITLE
SSRU and documentation for Marian 2019 

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#572]
From https://www.aclweb.org/anthology/D19-5632.pdf , there are implementation of `ssru` and all-layers tied (from Figure 3). 

Is there some official/informal documentation of how to train such the `(0) Base` model from Figure 3?

**Comment by emjotde** [comment]
Normal transformer-base model with these options on-top:

```
--transformer-decoder-autoreg rnn --dec-cell ssru --tied-layers 1 1 1 1 1 1
```
This model doesn't work particularly well when trained from scratch, but does well as a student model.

**Comment by alvations** [comment]
Thanks @emjotde!! 

Just to check again, Do we need to initialize the learner/student model with `--pretrained-model` of the teacher in the Marian 2019?

**Comment by emjotde** [comment]
No, usually they are of different sizes anyway. Forward translate your data with the teacher and train on the teacher's output. See Kim and Rush's excellent paper: https://arxiv.org/abs/1606.07947

I recommend to also forward-translate unseen data with the teacher. That was not allowed for the shared task.

**Comment by emjotde** [comment]
BTW, if your student has the same embeddings/filter sizes, initialization with the teacher might actually be a good idea, I have to try that.
