### ISSUE TITLE
Beam size in WNGT 2019

### ISSUE THREAD

**Issue by maydaygmail** [marian-nmt/marian-dev#574]
The beam size in WNGT 2018 is 1, but cannot find the beam size value in WNGT 2019

**Comment by emjotde** [comment]
Huh, good point! 
It's 1 as well, I am working on a corrected version, will add the beam size. Thank you for reporting.

**Comment by maydaygmail** [comment]
Thanks~
Does  marian-dev have all the features in the paper "From research to production and back"?
As listed in Figure 1 of the paper, SSRU, SSRU-Tied, FBGEMM,SIMD & Profiling and Batch pruning.

**Comment by emjotde** [comment]
Yes, the benefits from profiling and batch-pruning are all implemented and enabled by default, so nothing special to for these. I will write a small tutorial on how to get configure everything for the rest.

**Comment by maydaygmail** [comment]
Thanks~

**Comment by ykim362** [comment]
@maydaygmail , also, please don't forget to add '--skip-cost' for your decoder command to replicate WNGT 2019 results. This make your decoding skip the last softmax (which is useless for the beam size 1 greedy decoding). Softmax matters when the other operations are quite fast.

**Comment by emjotde** [comment]
Answered, I guess. Closing.
