### ISSUE TITLE
[Question] CPU profiling for Marian

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#589]
Are there any guide or previous study on how to profile `marian-decoder` on CPU for any or some of these metrics? https://software.intel.com/en-us/vtune-help-cpu-metrics-reference

**Comment by emjotde** [comment]
Hi,
what exactly is your goal? I like to use Google's pprof from google-perftools as it works quite well with Marian compiled in Release mode. Also all that is needed is to link the shared library at runtime as described here:

https://gperftools.github.io/gperftools/cpuprofile.html

**Comment by alvations** [comment]
I was curious how and which components performs on CPU and whether there are places that can be optimized but hasn't been yet =)

Thanks for the pointer to perftools!!

**Comment by emjotde** [comment]
My prediction is that you will have a hard time finding one specific place where things are slow, they might be globally slow, but in a sneaky way. We already went down to the custom memory allocator and custom smart-pointer level. However, it's always possible to optimize things. For instance, we still do not have fused multi-head attention. Looking at that now, for instance. There maybe spurious transpose operations that should be refactored etc. 

Most likely the best way to optimize is not algorithmic, but simplifying the math.

**Comment by emjotde** [comment]
When you find something interesting, coordinate with us please. There is a good chance we are working on it, too, or might give more pointers.

**Comment by alvations** [comment]
Thanks in advance for the pointers!! Yes, we'll share if we find something interesting (when we can).

Up till now, it looks like "choice of hardware" (CPU) affects response time and throughput for inference kind of significantly. But beyond that, I am not sure if I can share publicly (for now).

**Comment by alvations** [comment]
One more note, seems like sentencepiece (without pre-tokenization) is taking ~10% of the response time in inference for sending one sentence at a time. 

P/S: 10% might look trivial but it adds up =)

**Comment by emjotde** [comment]
That would be something to be taken up with the SentencePiece people tho :)

**Comment by emjotde** [comment]
Closing this. Feel free to reopen if you have something to share.
