### ISSUE TITLE
Questions about reusing marian's back-end codes

### ISSUE THREAD

**Issue by initial-d** [marian-nmt/marian-dev#593]
I want to reuse marian's  back-end to build other models. I only found examples about iris and mnist. Dose marian have a document about how to use the back-end computation graph? Thanks very much!

**Comment by snukky** [comment]
Sorry, currently there is not much more than the code, sparse comments in the code, the mentioned examples and unit tests. There is a project which aims to develop better documentation for Marian, but it is future work.
