### ISSUE TITLE
Correlation between marian and marian-dev repo

### ISSUE THREAD

**Issue by frzme** [marian-nmt/marian-dev#594]
It seems that in the past the "stable" version of marian was available in the `marian` repo while development happened in the `marian-dev` repo. 

Lately not much has happened in the `marian` repo and the 1.8.0 version is only present in `marian-dev`. What are your plans on how to proceed? Are releases in `marian-dev` considered stable? Is the `marian` repo still maintained?

**Comment by emjotde** [comment]
Hi,
going to update the main repo likely this week with a skip ahead to 1.9. We omitted 1.8 as a stable release as there were many internal changes that were less stable than desired. Now with 1.9 that should be all fixed.

**Comment by frzme** [comment]
Thank you for the explanation! I'm closing this issue
