### ISSUE TITLE
Better command line options handling

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#60]
Better command line options handling, maybe via tighter integration of boost program options and YAMLcpp.

**Comment by snukky** [comment]
Some progress with 439ca79262825fd9ed99884dbf699e0d20ea5248 and d12077ccc157fb23fdb0c6b8dbf3d13da4748c6d.

**Comment by emjotde** [comment]
@snukky BTW, have you maybe looked at compact alternatives to boost program options? If we managed to get rid of that it would be a large step towards getting rid of boost dependencies altogether.

**Comment by snukky** [comment]
@emjotde I thought about that. So far, I wanted to separate the creation of marian options from the config storage object.

**Comment by emjotde** [comment]
Anyone knows an alternative to boost program_options? Might be a good idea to get rid of that and reduce the dependency on boost.

**Comment by mjpost** [comment]
Lurking...Python’s argparse is great, and it looks like there are at least three implementations for C++ on github, at least one of which claims to be “nearly feature complete”. I haven’t tried any of them though so I can’t vouch for them.

**Comment by andre-martins** [comment]
There's also google gflags which I've used in some of my old projects.

**Comment by emjotde** [comment]
This is done
