### ISSUE TITLE
[FBGEMM] PackedRequantizeAcc16Test fails on VNNI

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-dev#607]
Hey,
At the attention of @ykim362 Marian's fork of fbgemm fails the `PackedRequantizeAcc16Test` on an avx512vnni machine. The upstream version of fbgemm doesn't have that problem. Potentially, this could be an issue. Here's part of the output logs:
```
...
GEMM results differ at (3, 5908) reference: 255, FBGEMM: 221
FBGEMM/test/TestUtils.cc:25: Failure
Expected equality of these values:
  ref[i * ld + j]
    Which is: '\xFF' (255)
  test[i * ld + j]
    Which is: '\xEC' (236)
GEMM results differ at (3, 5910) reference: 255, FBGEMM: 236
FBGEMM/test/TestUtils.cc:25: Failure
Expected equality of these values:
  ref[i * ld + j]
    Which is: '\xFF' (255)
  test[i * ld + j]
    Which is: '\xF2' (242)
...
```
For the record, the same test passes on an avx512f machine.

Cheers,

Nick

**Comment by ykim362** [comment]
Thanks, @XapaJIaMnu !
I will look into it.

**Comment by snukky** [comment]
This test has been disabled for VNNI CPUs. Closing.

**Comment by kpu** [comment]
You could not ship buggy code...

**Comment by ykim362** [comment]
@kpu  Actually, skipping is the fix of the bug. On VNNI machines, 16 bit accumulation is not used. The test is skipped in the public FBGEMM as well. https://github.com/pytorch/FBGEMM/blob/master/test/PackedRequantizeAcc16Test.cc#L112
