### ISSUE TITLE
Refactor and clean up AsyncGraphGroup

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#61]
It's a mess :)
My goal is to be able to remove cuda-specific code from this so I can turn marian into a library.

**Comment by afaji** [comment]
memory is now optimized. cuda-specific code separation is incoming

**Comment by emjotde** [comment]
Great, to what effect?

**Comment by afaji** [comment]
not much. Saving memory around 1x model size + some additional optimization for the sparse tensor.

**Comment by emjotde** [comment]
So it's still 5x model size? Where does this come from?

**Comment by kpu** [comment]
@XapaJIaMnu will likely be in this area.  And Intel has their own version for CPU which will require appropriate factorization.  In order to help @XapaJIaMnu, can you please please work on #5?

**Comment by emjotde** [comment]
@snukky Did you document the examples you did so far?

**Comment by emjotde** [comment]
I suppose @XapaJIaMnu will need to have deeply hidden stuff documented?

**Comment by XapaJIaMnu** [comment]
Ideally... I've been reading the code starting yesterday and I'm getting somewhat familiar with what's happening, but any documentation would be much appreciated.

**Comment by emjotde** [comment]
I am currently writing a new GPU memory allocator. I will start with documenting this (lowest level), as I am working on it right now. I suppose I will finish it this weekend. 

Which parts of the code are you most interested in?

**Comment by XapaJIaMnu** [comment]
I will probably not be doing much work on the GPU side and will probably spend most of the time optimizing either general to both CPU and GPU backends (meaning the construction of the computational graph... or basically anything related to the computational graph, other potentially shareable code (like parallel SGD), as well as CPU specifc matrix operations.

I would say for me most useful would be good documentation on the graph and what is currently available for parallel SGD/communications.

**Comment by afaji** [comment]
@emjotde as I said:

 - 1x model size memory to store parameter's error feedback on pushing
 - 1/Dx model size memory to store parameter's error feedback on fetching, for each GPU
 - 1x model size memory to execute gradient dropping on pushing
 - 1/Dx model size memory to execute gradient dropping on fetching, for each GPU
 - 1.5x model size memory to store parameter history
 - additional memory to store sparse tensors. this one depends on dropping ratio.

**Comment by emjotde** [comment]
Actually. I never got this information before, or lost it somehow. Thanks for the write-up. 
Naive question, could this be partially held in CPU memory?

**Comment by emjotde** [comment]
Hi,
for the moment I have done the following:
* I backed-up the current version of graph_group_asnyc.h
* I removed the gradient code for now.

This happend in the `nematus-dynamic` branch which we will soon merge into master. 
I would like to keep that file more or less clean. You are invited to add gradient dropping back in a cleaner way, maybe by inheriting from AsyncGraphGroup?

**Comment by emjotde** [comment]
Closing this for now. Feel free to re-open if required.
