### ISSUE TITLE
Marian server denies cross-domain AJAX requests

### ISSUE THREAD

**Issue by michnov** [marian-nmt/marian-dev#614]
### Bug description
If dockerized Marian server (and most likely Marian server in general) is queried for translation from a different domain, it fails due to: _Access to XMLHttpRequest at 'https://XXX/api/bergamot/v1' from origin 'https://YYY' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource._

When sending a cross-origin request with JSON content via POST method, browsers usually issue a prefligted request -- a special OPTIONS request prior the POST request itself to determine if the request is safe to send (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests). Marian server seems to be denying the OPTIONS requests with a 404 response, though.
![image](https://user-images.githubusercontent.com/11574860/77995518-39945880-732c-11ea-9899-4f8f95e4a566.png)

### How to reproduce
Build a dockerized Marian as MT service following the instructions [here](https://github.com/ugermann/marian-docker). In my case, I built it with [English-Estonian student model](https://github.com/browsermt/nmt-students/tree/master/eten/enet.student.tiny11) and run it listening on port 18080 (the error is most likely also reproducible if you run Marian server without Docker):
`$> docker run --rm -p 18080:18080 -d __my-dockerized-marian__`

Create the following HTML page with AJAX call to the runining server:
```html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
      $("button").click(function(){
              $.ajax({
                    url: "http://localhost:18080/api/bergamot/v1",
                    type: "POST",
                    contentType: "application/json",
                    crossDomain: true,
                    data: {text : "Hello world", options: { "inputFormat": "paragraph"}},
                    async: true,
                    success: function(result) { $("#transl").html(result); },
              });
      });
});
</script>
<body>

<button>Translate "Hello world"!</button>
<div id="transl"></div>

</body>
</html>
```
No result is returned if the button is clicked.

At the same time, the following curl command returns the result, since it does not depend on successful result of the OPTIONS request:
```
$> curl --header "Content-Type: application/json" --request POST --data '{"text": "Hello world!", "options": {"inputFormat": "paragraph"}}' http://localhost:18080/api/bergamot/v1
{"text":"Tere maailm! ","options":{"inputFormat":"paragraph"}}
```
The OPTIONS request sent by browsers may be simulated in curl as follows:
```
$> curl -H "Origin: http://example.com"   -H "Access-Control-Request-Method: POST"   -H "Access-Control-Request-Headers: X-Requested-With"   -X OPTIONS --verbose   http://localhost:18080/api/bergamot/v1
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 18080 (#0)
> OPTIONS /api/bergamot/v1 HTTP/1.1
> Host: localhost:18080
> User-Agent: curl/7.58.0
> Accept: */*
> Origin: http://example.com
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: X-Requested-With
> 
< HTTP/1.1 404 Not Found
< Content-Length: 15
< Server: Crow/0.1
< Date: Mon, 30 Mar 2020 00:22:07 GMT
< 
404 Not Found
* Connection #0 to host localhost left intact
```

### Context
* Marian version: marian-mt-service built on top of the mariannmt/marian-rest-server:latest (digest: 902e5371e28a)

**Comment by emjotde** [comment]
Hi,
This is unlikely due to a bug in Marian, but rather your setup or whoever is responsible for bergamot which is not us.

**Comment by kpu** [comment]
This is in a branch so fair enough. Paging @ugermann

**Comment by emjotde** [comment]
Oh, is that Uli's server? I was wondering what that even means. Not sure though if this should be the issue page for Bergamot?

**Comment by kpu** [comment]
This is @ugermann 's server in a branch of marian-dev for @browsermt .  @michnov you can raise this in the internal coordination repo.

**Comment by michnov** [comment]
In Uli's dockerized version of Marian here (https://github.com/ugermann/marian-docker) a specific commit of marian-dev is linked. I didn't realize that the server is not in the master, though. Sorry, my fault!
https://github.com/marian-nmt/marian-dev/blob/2bbe33d1a6f37d7474449ac4a3f16e8ae94915a9/src/server/rest_server.cpp
