### ISSUE TITLE
Update python scripts to python3

### ISSUE THREAD

**Issue by kdavis-mozilla** [marian-nmt/marian-dev#620]
### Bug description
Please add a clear and concise description of the bug, including observed and if possible expected behavior.

The tests under `regression-tests` use python3 as a result of the use of `pip3` in the `pip` target of `regression-tests/Makefile`. Thus the python scripts `scripts/*/*.py` should also use python3. However, not all of them do.

A patch to change this is as follows
```bash
diff --git a/scripts/checkpoints/average.py b/scripts/checkpoints/average.py
index 53bff186..da1ca252 100755
--- a/scripts/checkpoints/average.py
+++ b/scripts/checkpoints/average.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 """
 This script takes multiple Marian *.npz model files and outputs an elementwise average of the model,
 meant to do check-point averaging from: 
diff --git a/scripts/contrib/inject_ctt.py b/scripts/contrib/inject_ctt.py
index 751ee1c6..620c3152 100755
--- a/scripts/contrib/inject_ctt.py
+++ b/scripts/contrib/inject_ctt.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 
 from __future__ import print_function
 
diff --git a/scripts/contrib/inject_model_params.py b/scripts/contrib/inject_model_params.py
index 46096eb8..a0e637a3 100755
--- a/scripts/contrib/inject_model_params.py
+++ b/scripts/contrib/inject_model_params.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 
 from __future__ import print_function
 
diff --git a/scripts/embeddings/prepare_corpus.py b/scripts/embeddings/prepare_corpus.py
index 98326218..0c54be5d 100755
--- a/scripts/embeddings/prepare_corpus.py
+++ b/scripts/embeddings/prepare_corpus.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 # -*- coding: utf-8 -*-
 
 from __future__ import print_function
diff --git a/scripts/embeddings/process_word2vec.py b/scripts/embeddings/process_word2vec.py
index 4f5ba493..685f8d23 100755
--- a/scripts/embeddings/process_word2vec.py
+++ b/scripts/embeddings/process_word2vec.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 # -*- coding: utf-8 -*-
 
 from __future__ import print_function
diff --git a/scripts/server/client_example.py b/scripts/server/client_example.py
index 7f9e0ae3..4c194d74 100755
--- a/scripts/server/client_example.py
+++ b/scripts/server/client_example.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 
 from __future__ import print_function, unicode_literals, division
```

### How to reproduce
Describe steps or include command to reproduce the behavior.

Run the regression tests as described in the [marian-regression-tests](https://github.com/marian-nmt/marian-regression-tests) repo.

### Context
* Marian version: Paste the output of `--version` here
> The VERSION file contains v1.9.1

* CMake command: Type the cmake command you used and attach the output of `--build-info all`
> cmake .. \
>       -DCOMPILE_CUDA=off \
>       -DBUILD_ARCH=${BUILD_ARCH} \
>       -DCMAKE_BUILD_TYPE=Release \
>       -DUSE_STATIC_LIBS=on \
>       -DUSE_SENTENCEPIECE=on \
>       -DCOMPILE_SERVER=on \
>       -DCOMPILE_EXAMPLES=on

* Log file: Attach your training/decoding logs
> I currently do not have access to the produced log

**Comment by kpu** [comment]
Let's convert this to a pull request?
