### ISSUE TITLE
When marian supports saving only last N checkpoints?

### ISSUE THREAD

**Issue by lkfo415579** [marian-nmt/marian-dev#636]
Because averaging the last 10 checkpoints models can improve **BLEU** a little bit, marian usually saves every valid step model into disk but it is storage consuming. I look though the option list, there is no a option about only saving the last N checkpoints.

I hope this feature can be present in new version.

**Comment by emjotde** [comment]
For now, I recommend using `--keep-best --overwrite --exponential-smoothing`. That keeps the best checkpoint according to the valid metrics and averages all running parameters with an exponential average. In my experience that works as well or better than manual checkpoint averaging. The saved checkpoint are already averages at that point.

`--keep-best N` or `--overwrite N` is something to think about.
