### ISSUE TITLE
[Question] Is the sentencepiece alpha in Marian CLI the one used for BPE dropout?

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#658]
Is the `--sentencepiece-alphas` in Marian CLI the same as the alpha on https://github.com/google/sentencepiece/blob/master/src/bpe_model.h#L43 to support BPE dropout when called at https://github.com/marian-nmt/marian-dev/blob/master/src/data/sentencepiece_vocab.cpp#L214 ?

If so, why is there more than 1 alpha?

**Comment by emjotde** [comment]
We haven't updated to newer SentencePiece for a while. If that concerns BPE dropout then likely not.

**Comment by alvations** [comment]
Thanks for the clarification! I'll play around the `--sentencepiece-alphas` in Marian and see what it does during training then =)

**Comment by emjotde** [comment]
Didn't do anything for me. Hence my skepticism towards BPE dropout as well.

**Comment by alvations** [comment]
Thanks again for checking! Seems like didn't do much to my .spm models too... Maybe it has to be used with some order mechanisms. 

Lol, maybe it's better to just create the `.spm` with the latest dev branch in sentencepiece =)

**Comment by emjotde** [comment]
Don't think the algorithms actually changed.

**Comment by alvations** [comment]
I think the features and the SampleEncode overridden functions did. 

For context, just got to just figure out how to use the BPE dropout there to "replicate" someone else's experiment that uses https://github.com/VKCOM/YouTokenToMe 's (sentencepice's unigram entropy algorithm with BPE dropout).

**Comment by alvations** [comment]
Going to close this issue. Thanks for the explanations! I'll just check back when the new sentencepiece is updated in Marian =)

**Comment by emjotde** [comment]
A remark for clarity, the unigram method isn't BPE, hence no BPE dropout there. I guess you just mean the segmentation sampling?

**Comment by alvations** [comment]
yes the "BPE dropout" here refers to the segmentation sampling, i.e. for the same word, segment it into different ways.  https://github.com/google/sentencepiece#subword-regularization-and-bpe-dropout =)
