### ISSUE TITLE
Translate and output SGML files 

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#664]
# Feature description

The SGML format is often used for certain shared tasks. E.g. http://www.statmt.org/wmt20/translation-task.html

Although there's no indication which other application uses SGML, it might be good to support it in the marian decoder binary, since the shared tasks are rather popular in the MT community.

# Current Usage
Before decoding, one has to remove the xml markup to get to a plaintext, e.g.

```python
from bs4 import BeautifulSoup

en_sgm = 'wmt20-test-src/sgm/newstest2020-enja-src-ts.en.sgm'
ja_sgm = 'wmt20-test-src/sgm/newstest2020-jaen-src-ts.ja.sgm'

with open(en_sgm) as fin:
    bsoup = BeautifulSoup(fin)
    en_src = [s.text for s in bsoup.find_all('seg')]
    
with open(ja_sgm) as fin:
    bsoup = BeautifulSoup(fin)
    ja_src = [s.text for s in bsoup.find_all('seg')]
    
with open('wmt20-ja2en.ja', 'w') as fout:
    fout.write('\n'.join(ja_src))
    
with open('wmt20-en2ja.en', 'w') as fout:
    fout.write('\n'.join(en_src))
```

After decoding, 

```
cat wmt20-en2ja.en | marian-decoder -m model.en2ja.npz -v ... > wmt20-en2ja.en.translated.ja
```

We have to use the wrap-xml.perl, http://www.statmt.org/wmt11/wrap-xml.perl:

```
wrap-xml.perl ja newstest2020-enja-src-ts.en.sgm MarianModel < wmt20-en2ja.en.translated.ja > decoder-output.sgm
```

Then we get the `decoder-output.sgm` for shared task submission. 

# Proposed usage:

```
cat wmt20-test-src/sgm/newstest2020-enja-src-ts.en.sgm | 
  marian-decoder -m model.en2ja.npz -v ... \ 
    --sgml-system-name MarianModel  --sgml-src-lang ja > decoder-output.sgm
```

**Comment by emjotde** [comment]
I would say that it's rather the sgm format that needs to die?

**Comment by XapaJIaMnu** [comment]
@alvations , the WMT test sets are actually not valid `SGM` syntax and trying to parse them with anything but the `wrap-xml.perl` results in a crash. Instead of propagating this madness, we should just move away from it.

**Comment by bhaddow** [comment]
This year, ocelot immediately strips off the sgm before evaluating with sacrebleu. I agree that it's a bad format and this should be the last year we use it.

**Comment by emjotde** [comment]
Hosanna! :) 
Closed due to mutual hatred on the SGM format.

**Comment by alvations** [comment]
@bhaddow BTW, the ocelot deployed seems to be buggy at escape vs unescape tokens. The SGM needed the tokens to be escaped but actually removing the tokens that needs to be escaped seem to increase sacrebleu score!! I suspect either sacrebleu or the sgm parsing in ocelot didn't perform a full deescape as per the https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/deescape-special-chars.perl but users are expected to use https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/escape-special-chars.perl to avoid the -1 result errors =)

**Comment by emjotde** [comment]
@alvations 
https://github.com/AppraiseDev/OCELoT/issues
