### ISSUE TITLE
 Error: Error writing to file '.'  version=1.5.0

### ISSUE THREAD

**Issue by zll0000** [marian-nmt/marian-dev#665]
### Bug description
Please add a clear and concise description of the bug, including observed and if possible expected behavior.

### How to reproduce
Describe steps or include command to reproduce the behavior.

### Context
* Marian version: Paste the output of `--version` here
* CMake command: Type the cmake command you used and attach the output of `--build-info all`
* Log file: Attach your training/decoding logs

Add any other information about the problem here.

**Comment by emjotde** [comment]
Uhm, could you describe your issue in the issue text box?

**Comment by zll0000** [comment]
I have solved the problem by setting --tmpdir
