### ISSUE TITLE
set_property can not be used on an ALIAS target

### ISSUE THREAD

**Issue by kdavis-mozilla** [marian-nmt/marian-dev#668]
### Bug description
Compiling on macOS fails on lines 71 and 73 of src/3rd_party/CMakeLists.txt due to set_property in  being called on an ALIAS target.

### How to reproduce
``` bash
git clone https://github.com/marian-nmt/marian-dev
cd marian-dev
mkdir build
cmake -DCMAKE_BUILD_TYPE=Release -DUSE_STATIC_LIBS=on -DUSE_SENTENCEPIECE=on -DCOMPILE_CUDA=off ..
```

### Context
* Marian version: Commit 5b93079 of marian-dev
* CMake command: cmake command is above and I don't think think the --build-info all info is required.
* Log file: NA

Add any other information about the problem here.

**Comment by snukky** [comment]
This is not a commit from the master branch. Does the issue occur in master too? If so, and you have a solution, please feel free to open a PR to master.

**Comment by kdavis-mozilla** [comment]
It's in master too [CMakeLists.txt#L71](https://github.com/marian-nmt/marian-dev/blob/master/src/3rd_party/CMakeLists.txt#L71) and [CMakeLists.txt#L73](https://github.com/marian-nmt/marian-dev/blob/master/src/3rd_party/CMakeLists.txt#L73)

I'm currently testing a PR.

**Comment by snukky** [comment]
Closing, PR was merged into master. Thanks @kdavis-mozilla
