### ISSUE TITLE
Introduce new model type "Nematus" to keep full compatibillity

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#67]
Introduce new model type "Nematus" to keep full compatibillity with the new options, maybe to the point where we reuse options names etc. 

This should maybe also somehow coordinate with Amun. For basic options, `--type amun` already does that, but there are new things like deep transition networks (more or less done in marian as well) and factors. 

This should be a close mirror. Options other than present in nematus should be in S2S. Not sure about the alternating encoders, though.

**Comment by rsennrich** [comment]
for what it's worth, we used DRT and not the alternating decoder for most WMT17 systems, but in follow-up experiments, we got best results by combining DRT and (alternating) stack RNNs (by having a stack of 4 RNNs, each layer consisting of 2 GRU transitions).

**Comment by emjotde** [comment]
Thanks @rsennrich, what does the acronym DRT stand for? I am getting confused by the multitude of options. Also, if I wanted to replicate sen model, what would be the correct set of Nematus options?

**Comment by tomekd** [comment]
Deep recurrent transition?

**Comment by rsennrich** [comment]
sorry, DRT stands for 'deep recurrent transition', and is the same as 'deep transition network'.

here's a configuration for a stack of 4, each layer with 2 GRUs (4 for the base decoder layer, since that already has 2 in the baseline).

    --layer_normalisation \
    --enc_depth 4 \
    --dec_depth 4 \
    --dec_deep_context \
    --enc_recurrence_transition_depth 2 \
    --dec_base_recurrence_transition_depth 4 \
    --dec_high_recurrence_transition_depth 2

**Comment by emjotde** [comment]
So the encoder would be still BiUnidirectional? 
In terms of GRU cells : (2|2)+2+2+2
Any skip connections here?

**Comment by rsennrich** [comment]
no, the stack encoder is alternating by default.

There's residual connections between layers in the stack (the first 
layer has no residual input).

**Comment by emjotde** [comment]
OK, I am starting to see clearer now. There are no residuals within the transitional cells?

**Comment by tomekd** [comment]
No, there is no residual connections between transitions. Residual connections are between "whole" layers.

**Comment by emjotde** [comment]
@rsennrich BTW, did you do something with that inconsistent bias in reset gate of the DL4MT GRU?

**Comment by rsennrich** [comment]
no, we didn't touch the biases - this would either break backward 
compatibility or add complexity.

**Comment by emjotde** [comment]
It adds complexity now, IMO :)

**Comment by emjotde** [comment]
@rsennrich Coming back to that wretched bias, in the CGRU, you have GRU_1 ATT GRU_2 where GRU_2 has that weird bias, while GRU_1 does not. What do you in deeper cells in the following layers?

**Comment by emjotde** [comment]
Aaannd works (apparently). Thank you, @rsennrich. Now I need to make it backwards compatible and look up Nematus matrix names, figure out the biases. If anyone is curious, it's in branch `refactor-rnn`, enabled with `--nematus-wmt2017`, which sets a bunch of other options. It should also works with the LSTM cell. 

This still needs some refactoring, but is not too bad:
https://github.com/marian-nmt/marian-train/blob/refactor-rnn/src/models/s2s.h

Current speed on a TitanX GPU is 3550 words/s, with 4 TitanX GPUs about 9960 words/s with an average dynamic batch size of ~85.

**Comment by emjotde** [comment]
Ah, wait, I think my alternating stack is missing it's second half, duh.

**Comment by emjotde** [comment]
Ooh, the full alternating stack in the encoder is expensive computation-wise! Now with a dynamic batch-size of ~68, it makes 2030 words/s on a Titan X and about 5850 words/s on 4 of them. Memory usage about 9.5G, keeping 2.5G free for translation with sharded parameters across 4 GPUs. If that memory is used too, it gets up to a batch size of ~91 and 7300 words/s on 4 GPUs.

Need to integrate translation into the same process to get hold of that additional memory.

**Comment by rsennrich** [comment]
in the CGRU deep transition network, additional GRUs are modelled after 
GRU_2, so they do have the bias.

**Comment by emjotde** [comment]
@rsennrich do you have a repo for replicating your experiments?

**Comment by rsennrich** [comment]
Hopefully next week.

**Comment by emjotde** [comment]
Current master has now a lot of new options for depth. I will put some documentation on the page soon. Currently this is not yet compatible with Nematus.

**Comment by rsennrich** [comment]
a repo with the configs for our experiments is now online: https://github.com/Avmb/deep-nmt-architectures . This should be combinable with preprocessing scripts at http://data.statmt.org/wmt17_systems/training/ (still WIP) to replicate our experiments.

**Comment by emjotde** [comment]
Great. Will take a look. The paper is not published anywhere yet (e.g. Arxiv?) to point to it on the Marian website for the deep features?

@snukky will now take over to make the deep stuff fully Nematus-compatible. We will probably introduce a special Nematus-GRU that matches your implemenation while we will use our slighlty more efficient version in other places. The main problem is that we handle layer-normalization differently.

**Comment by snukky** [comment]
We have now a new model type `--type nematus`, which supports Nematus layer normalization. It's available in `nematus` branch. We get almost identical translations to Nematus for beam-size = 1. For beam-size > 1 some translations are different, so I reported the bug #98 (as it affects all deep models).

**Comment by snukky** [comment]
Implemented.
