### ISSUE TITLE
With fixes of PR 669 marian-dev does not complile on macOS

### ISSUE THREAD

**Issue by kdavis-mozilla** [marian-nmt/marian-dev#670]
### Bug description
Applying PR 669 then running cmake and make as follows
```bash
build % cmake -DCMAKE_BUILD_TYPE=Release -DUSE_STATIC_LIBS=on -DUSE_SENTENCEPIECE=on -DCOMPILE_CUDA=off ..
...
-- Build files have been written to: .../marian-dev/build
build % make -j4  
```
causes compilation to fail due to various macOS related problems with the code.

### How to reproduce
See above

### Context
* Marian version: master
* CMake command: See above
* Log file: NA

Add any other information about the problem here.

**Comment by snukky** [comment]
Closing, PR was merged. Thanks @kdavis-mozilla!
