### ISSUE TITLE
Launch translator within marian process instead of externally

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#68]
Currently the translator is launched as a separate process for validation. That makes no sense, it should reuse the memory reserved for training instead. That way the training process would be able to use up the entire GPU memory. 

With huge models like in #67 that's actually a problem.

**Comment by geovedi** [comment]
yes, this happened to me recently, using 289ae93. it was 70M pair sentences + alignment and i have to set `no-shuffle: true` as shuffling took ages if not get killed.

```bash
terminate called after throwing an instance of 'util::Exception'
  what():  /home/xyz/workdir/src/marian-train/src/training/validator.h:178 in std::__cxx11::string marian::ScriptValidator<Builder>::exec(const string&) [with Builder = marian::Amun; std::__cxx11::string = std::__cxx11::basic_string<char>] threw util::Exception.
popen() failed!
Aborted (core dumped)
```


As workarounds, I did use `amun` with CPU instead of GPU or use `s2s` but split training files into reasonable chunks.

**Comment by snukky** [comment]
Will be solved after the upcoming merge with `nematus-dynamic`.

We will have a new validation metric called `translation`, which translates the provided validation set and passes the file with translations (a temporary file by default or the name of the file can be optionally specified with `--trans-output`) as the first argument to the validation script (`--valid-script-path`).

**Comment by emjotde** [comment]
We have this in master of marian-dev now. I would keep this issue open until we have multi-gpu support for this.

**Comment by snukky** [comment]
Already in the master branch of marian-dev.
