### ISSUE TITLE
Max length and GPU parallelism

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#695]
Broadcasting a model when the max-length value is set high enough on an older GPU seem to fail.

When the `--max-length` argument is set to a large enough value, the model doesn't seem to be able to broadcast the matrix multiplication beyond the first GPU. 

E.g. if we train a [teacher model like on the example](https://github.com/marian-nmt/marian-examples/tree/master/transformer):

```
../build/marian \
    --model model/model.npz --type transformer \
    --train-sets data/corpus.bpe.en data/corpus.bpe.de \
    --max-length 100 \
    --vocabs model/vocab.ende.yml model/vocab.ende.yml \
    --mini-batch-fit -w 10000 --maxi-batch 1000 \
    --early-stopping 10 \
    --valid-freq 5000 --save-freq 5000 --disp-freq 500 \
    --valid-metrics cross-entropy perplexity translation \
    --valid-sets data/valid.bpe.en data/valid.bpe.de \
    --valid-script-path ./scripts/validate.sh \
    --valid-translation-output data/valid.bpe.en.output --quiet-translation \
    --valid-mini-batch 64 \
    --beam-size 6 --normalize 0.6 \
    --log model/train.log --valid-log model/valid.log \
    --enc-depth 6 --dec-depth 6 \
    --transformer-heads 8 \
    --transformer-postprocess-emb d \
    --transformer-postprocess dan \
    --transformer-dropout 0.1 --label-smoothing 0.1 \
    --learn-rate 0.0003 --lr-warmup 16000 --lr-decay-inv-sqrt 16000 --lr-report \
    --optimizer-params 0.9 0.98 1e-09 --clip-norm 5 \
    --tied-embeddings-all \
    --devices $GPUS --sync-sgd --seed 1111 \
    --exponential-smoothing
```

The value `--max-length 100` seems to work on most GPU with > 8GB RAM. 

| GPU | Max RAM | #GPUs (device) |  max-length | workspace | Actual RAM usage (during train) | Active GPU with usage/volitilty | 
|:-|:-|:-:|-:|-:|-:|:-|
| GTX 1080 | 8GB | 0 1 2 3 | 200 | 5,500 | 7,900 | 0 1 2 3 | 
| GTX 1080 | 8GB | 0 1 2 3 | 300 | 5,500 | 7,900 | 0 1 2 3 | 
| GTX 1080 | 8GB | 0 1 2 3 | 400 | 5,500 | 7,900 | 0 1 2 3 | 
| GTX 1080 | 8GB | 0 1 2 3 | 500 | 5,500 | 7,900 |  0 | 
| | | | | | | | 
| V100 | 32GB | 0 1 2 3 | 1000 | 29,000 | 31,600 | 0 1 2 3 | 
| V100 | 32GB | 0 1 2 3 | 100000 | 29,000 | 31,600 | 0  | 

I'm using 3aed9143 version but I think this affects any version of Marian since the support for transformers is available. 

Going back to https://github.com/marian-nmt/marian-dev/issues/365 and my new questions are:

 - Is that the expected behavior where the model still trains but on 1 GPU when the max-length is too large for the GPU to handle?
 - If training on `max-length 100` and `--valid-max-length 1000` the theoretic capabilities of the model should be at 1000 not 100 right?
 - Is there some sort of GPUs / Workspace / max-length recommendation for training (from experience)? Spamming +10 to the max-length values on different GPUs with differing workspace manually seems to be a silly way to get the right combinations =)

**Comment by emjotde** [comment]
Why is that a bug? I honestly do not understand what you are asking here?

**Comment by alvations** [comment]
Not a bug just question, on what's the expected behavior when the max-length is large enough, would the GPU computes be stuck on the 1st? 

I think the label was automatically added =(

**Comment by emjotde** [comment]
I don't see why there would be relation between max-length and number of GPUs. Do you have any indication this is happening?

**Comment by emjotde** [comment]
Oh. I know what is going on. You have --mini-batch-fit running. It's not stuck, is pre-calculating batch sizes. And it's doing that in steps of 10. For your insane --max-length of 100K that is going to take a long time. Why not use your actual maximum length from the corpus? Is there a scenario where you ever expect 100K to work?

**Comment by emjotde** [comment]
If you want to see what is happing you can set `--log-level debug`

**Comment by alvations** [comment]
Ah yes! `mini-batch-fit: true` =)

> Why not use your actual maximum length from the corpus? 

But would that mean that the model is still limited if the original max length when using continued training on a new dataset with a larger max?

> Is there a scenario where you ever expect 100K to work?

Kind of. Esp. if a sentence is ~1000 chars. And doing some crazy `s1_1 s2_1  ...<sep> s1_2 s2_2  ...<sep> s1_3 s2_3 ...` -> `t1_1 t2_1  ...<sep> t1_2 t2_2  ...<sep> t1_3 t2_3 ...`  kind of training.

Good idea, I should use the `--log-level`!!

**Comment by emjotde** [comment]
A 100K max-length model is going to be insanely huge in memory, just the top set of activations in an encoder is going to be about 300 MB and there's probably hundreds of them in an expanded model. You can set the `--mini-batch-fit-step` to something larger, maybe 100?

Sinusoidal position embeddings are supposed to generalize beyond seen lengths, but I think the phase is only about 10K before they restart? So with 100K you would need to do model modifications.

**Comment by alvations** [comment]
Thank you for the suggestions!! Let me play around `--mini-batch-fit-step` and see how big a max-length is feasible. 

As for sinusoidal position embeddings, I guess having trainable positional embeddings might help but that's an even larger model then :P

**Comment by emjotde** [comment]
I am assuming this has solved itself :)
