### ISSUE TITLE
Marian's FBGEMM does not compile on CPUs with VNNI using GCC 9.3+

### ISSUE THREAD

**Issue by snukky** [marian-nmt/marian-dev#709]
### Bug description
It seems that Marian can not be compiled with FBGEMM on machines with new CPUs supporting VNNI using GCC 9.3 or 10.0. It produces a long list of errors like these:

    /tmp/ccWTYViL.s: Assembler messages:
    /tmp/ccWTYViL.s:49532: Error: invalid use of register

We see this occasionally on GitHub CI, e.g. [this build](https://github.com/marian-nmt/marian-dev/runs/1055063509?check_suite_focus=true), and I can reproduce it on my laptop on Ubuntu 20.04 WSL. Marian+FBGEMM compiles without issues on 1) a machine without VNNI using GCC >=9.3, or 2) on a machine with VNNI using GCC <9, tested with GCC 8.4, 7.5 and 5.5.

GCC 9.3 is the default on Ubuntu 20.04, so the issue may become more prominent over time.

`marian-nmt/fbgemm` can be compiled with any tested GCC version, however, some unit tests in PackedRequantizeAcc16Test fail. They work if compiling the latest version of `pytorch/fbgemm`. Thanks to @XapaJIaMnu for suggesting this.

@ykim362 Have you experienced this? Maybe we should try updating FBGEMM used in Marian?

### How to reproduce
Compile Marian on a machine with CPU that has `avx512_vnni` (on Ubuntu it can be checked by `cat /proc/cpuinfo | grep avx`)

    CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9 \
    cmake .. -DUSE_SENTENCEPIECE=on -DUSE_FBGEMM=on -DCOMPILE_CUDA=off -DCOMPILE_CPU=on

### Context
* Marian version: I think any recent version of marian-dev has this issue
* CMake command: see above
* Log file: [compilation logs from GitHub checks](https://github.com/marian-nmt/marian-dev/runs/1055063509?check_suite_focus=true)

CMake 3.16.3, MKL 2020.0.1/2020.0.0, GCC 9.3.0.
Tested on Ubuntu 20.04 WSL and confirmed on non-virtual Ubuntu 18.04.

**Comment by XapaJIaMnu** [comment]
Related, #607

**Comment by emjotde** [comment]
We have seen this on some of the randomly assigned machines for CI. If upstream FBGEMM works, would be good to merge. @ykim362

**Comment by ykim362** [comment]
@emjotde There are two things blocking the merge of upstream FBGEMM. The first one is the performance issue of intrinsic APIs for fp16 on windows. (This is going away in a few weeks we hope) The other one is pre-packing of the B matrix offline (without additional cache). I will ask if this can be implemented or merged into the public FBGEMM.

**Comment by ykim362** [comment]
@snukky I also heard that it had a compilation error with gcc 9.3. I will work to see if we can integrate the upstream FBGEMM (might take some time). In the meantime, I will try to merge the latest vnni code.

**Comment by ykim362** [comment]
The fix is merged to the master. Let's close this issue, too.
