### ISSUE TITLE
Replacing unknown words with most attentive source token

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian-dev#732]
In OpenNMT, it's possible to replace `<unk>` with most attentive source words https://opennmt.net/OpenNMT/translation/unknowns/

> Often times <unk> symbols will correspond to proper names that can be directly transposed between languages. The `-replace_unk` option will substitute <unk> with source words that have the highest attention weight. 

OpenNMT is checking the `<unk>` then look into the attention weights, https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translator.py#L169

Currently, it's a much cleaner to do https://github.com/marian-nmt/marian-dev/blob/master/src/translator/beam_search.cpp#L301 with `--allow-unk` but checking the hypotheses' alignment might be good to replicate OpenNMT `-replace_unk` behavior.

(Not sure how to aggregate the attention heads too. Max? Max-Pool? Average?)

(Not sure how this would work out in word pieces though, maybe trust the model to learn a source token splits into pieces retains the order of the attention?)

**Comment by emjotde** [comment]
Hi,
Have you tried that with a transformer model?

**Comment by alvations** [comment]
In OpenNMT, I've only tried that with a modified LSTM model. Not sure how they do it for transformer *shrugs...

**Comment by emjotde** [comment]
Yeah, I feel like this is a lot of effort with little return.

**Comment by alvations** [comment]
One benefit it to handle mixed inputs where the vocab doesn't have chars/sub-words from another language. E.g. 

Source: `Rāja (Sanskrit: राज) means "chief, best of its kind" or "king".`
Target: `Rāja（サンスクリット語：<unk>）は、「最高、その種の最高」または「王」を意味します。`

**Comment by emjotde** [comment]
ASCII escaping, probably more reliable.

**Comment by emjotde** [comment]
convert राज to [[e0a4b0e0a4bee0a49c]], apply sentenciepiece, translate, (hope it survives), convert back.

**Comment by emjotde** [comment]
@alvations can we close this? Basically the answer is that we are not going to do it unless someone else does.

**Comment by alvations** [comment]
Sure, I think we can close this until someone revives it.
