### ISSUE TITLE
--task transformer doesn't do anything and gives somewhat suboptimal defaults

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-dev#740]
### Bug description
It used to be the case that we had two separate `--task` possibilities: `transformer` and `transformer-big` and this is still reflected in the options ( https://github.com/marian-nmt/marian-dev/blob/master/src/common/config_parser.cpp#L536 ) or on the website.

This is supposed to be matched by an alias entry ( https://github.com/marian-nmt/marian-dev/blob/master/src/common/aliases.cpp#L74 ) but it got renamed to `transformer-base`.  As a result, new users end up putting `--task transformer` and are getting  some largely unexpected defaults.

We should update the help description and also warn/crash when unknown task is provided, so that the user knows when they are using outdated/wrong parameters.

Cheers,

Nick

**Comment by snukky** [comment]
You are right. This could have happened by a mistake, but we should not have changed the API. An error when an unknown task name is provided is also a good idea.

**Comment by emjotde** [comment]
PR anyone?
