### ISSUE TITLE
[Question] Is the marian repo deprecated?

### ISSUE THREAD

**Issue by sianvolta** [marian-nmt/marian-dev#755]
There's no action on https://github.com/marian-nmt/marian since May 2020, is it deprecated? Should there only be just the `marian-dev` (this repo)? 

Is there an official release version that new users should use in marian-dev?

**Comment by emjotde** [comment]
Hi,
https://github.com/marian-nmt/marian is the official stable release, we usually update there with every minor version update x.y.z (i.e. when y changes), Currently 1.9 is the latest stable release. I am working on getting fp16 training merged, shortly after that we will release 1.10.

**Comment by sianvolta** [comment]
Hi, 

Thank you for the explanation! Maybe it'll be good to put that somewhere in the README or on the https://marian-nmt.github.io/ site.
