### ISSUE TITLE
Default build requires install to run

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#763]
Now that the default build includes SentencePiece as a separate library but also links such libraries dynamically, by default one cannot simply run Marian out of the `build` directory.  
https://github.com/marian-nmt/marian-dev/blob/5990142047faaa50850e0e3fc5409de4fd69cd14/CMakeLists.txt#L26-L27

The result is this error:
```
error while loading shared libraries: libsentencepiece_train.so.0: cannot open shared object file: No such file or directory
```
Of course one could install Marian.  

Is that what we wanted?  My impression is most projects consider submodules to be statically linked by default.

**Comment by emjotde** [comment]
Yep, bug. Probably some option name change. Thanks.

**Comment by emjotde** [comment]
@kpu please check if it is OK now. Looks fine on my side, but I apparently had SPM installed, so never noticed that.

**Comment by kpu** [comment]
Works.
