### ISSUE TITLE
scorer (sub)word alignment 

### ISSUE THREAD

**Issue by zouharvi** [marian-nmt/marian-dev#775]
The output of the `--alignment` option seems to be an alignment on subword units rather than on the tokens themselves:

```
Hello there ||| Hallo da
0-0 1-1 2-2
Hello ||| HalloHalloHalloHallo
0-0 1-1 1-2 1-3 1-4 1-5 1-6 1-7
```

Is it possible to also retreive the text segmentaion so that the word alignment can be aggregated from "subword alignment"?

I am not an MT practicioner, so I may be misunderstanding some concepts.

**Comment by snukky** [comment]
Yes, `--no-spm-decode` will keep translations segmented into subwords.

**Comment by kpu** [comment]
He needs the source segmentation as well, yes?  

This is literally what @jerinphilip is working on for Bergamot at https://github.com/browsermt/marian-dev/pull/11

**Comment by zouharvi** [comment]
`--no-spm-decode` is part of the decoder, not scorer. My goal is to get alignment scores for a given input and output.

> He needs the source segmentation as well, yes?
Yes, this would solve the issue.

**Comment by zouharvi** [comment]
Since it's possible to get the subword segmentation using sentencepiece separatedly and hence there exitst *a* solution, I am closing this issue.

I'll keey an eye on what @jerinphilip is doing.
