### ISSUE TITLE
marian-decoder fails to use all gpus if data is fed one line at at time, can cause OOM on gpu 0

### ISSUE THREAD

**Issue by kaleidoescape** [marian-nmt/marian-dev#784]
### Bug description
When marian-decoder is invoked with multiple devices, but data is fed into it one line at a time, it seems that each line ends up going to the zeroth device. If a lot of lines are quickly fed this way, a crash occurs due to GPU OOM error.

### How to reproduce
Create a small script to feed data from a large file, one line at a time, e.g. `run.py`:

```
import sys
import subprocess

fp = sys.argv[1]
cmd = sys.argv[2:]

p = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=sys.stderr)

with open(fp, 'rb') as infile:
    for line in infile:
        p.stdin.write(line)
```

Invoke with:
```
python run.py input.txt ~/marian-dev/build/marian-decoder -c config.yml --devices 0 1 2 3
```

Watch the GPU utliziation, e.g. through `watch nvidia-smi` and you will see that only the zeroth GPU is used (even though some of the RAM of the other GPUs is filled at the start, presumably with the model).

### Context

* Marian version: `v1.9.58 737f430 2021-01-07 13:12:36 +0000`
* CMake command: `cmake .. -DCOMPILE_CPU=on -DUSE_SENTENCEPIECE=on -DCOMPILE_SERVER=on`
* Output of `--build-info all`: [build-info-all.txt](https://github.com/marian-nmt/marian-dev/files/5791619/build-info-all.txt)
* Log file: N/A

**Comment by emjotde** [comment]
Hm. I think these are multiple unrelated issues.
1) the OOM is probably happening because you have very long lines in the input? Does it go away with `--max-length 256 --max-length-crop` (this will truncate inputs, though)?
2) Is this behavior is happening with a normal Linux pipe via `cat input | marian-decoder ...`. That's how we normally use it and it works just fine. How would this here be different?

**Comment by emjotde** [comment]
Also please post your `config.yml`, let's see what is going on in there.

**Comment by kpu** [comment]
When drip-fed, read() will often return a short read with whatever is in the fifo.  I'm wondering if this is making its way up to batching.  cat is probably splicing and, if not, doing a larger batch of bytes as input.

**Comment by emjotde** [comment]
Cannot repro. Works fine for me with the exact script and all my 8 GPUs running.

**Comment by emjotde** [comment]
Might be a batching issue on your side. Make sure to use `--mini-batch 1 --maxi-batch 1` to force flushing or set it in your `config.yml`.

**Comment by kpu** [comment]
Why should one have to use `--mini-batch 1 --maxi-batch 1`?

**Comment by emjotde** [comment]
False alarm. I am now getting a weird issue where it gets stuck after about 320 sentences. But cannot tell yet whose fault that is.

**Comment by emjotde** [comment]
OK, so multi-gpu works fine. And it doesn't get stuck when I remove `stdout=subprocess.PIPE`. Is the above the correct way of handling input/output pipe in Python?

**Comment by kpu** [comment]
I believe @kaleidoescape has sent a buggy python program in that nothing is reading stdout and needs to revise the report with more information.

**Comment by emjotde** [comment]
Yeah, I think I just arrived at the same conclusion. With `stdout=subprocess.PIPE` the pipe needs to be consumed somehwere. Otherwise buffers fill and stops processing, correctly. So from my side there is no current Marian bug. All works for me.

**Comment by kaleidoescape** [comment]
Thanks for the replies. My mistake, I was trying to simplify my code for the issue, and failed to do so correctly. I will close this for now, and if I can reproduce with a more complete script, then I will reopen later. Thanks for the help.
