### ISSUE TITLE
Different results from marian-decoder and marian-server

### ISSUE THREAD

**Issue by GokulNC** [marian-nmt/marian-dev#785]
### Bug description
For some sentences, I seem to get different outputs from `marian-server` and `marian-decoder`.

### How?
I use the same `decoder.yml` file for both `marian-server` and `marian-decoder`, and pass no other additional arguments.
(Hence beam search should be read from .yml in both cases)

### Context
Both are run on the same machine.
Marian version: v1.9.0 ba94c5b9

Please let me know if I am missing something.

**Comment by GokulNC** [comment]
If you need more information:

- I run both inference (decoder and server) on CPU
- I also tried both using the latest marian-dev v1.9.58 737f4301. The inconsistency is still there.
- My model is `--type transformer`, and I use Marian's Sentence Piece Tokenizer.

**Comment by snukky** [comment]
Hi, I think we have this covered in our regression tests, but it still might be a combination of options that we don't test. Could you share your `decoder.yml` and logging outputs from both marian-server and marian-decoder? Thanks!

**Comment by GokulNC** [comment]
Really sorry, the mistake was in my server code.
There was a place where I was converting my input into lower-case during processing the input from my front-end.
Because of this, sentences that rely on proper capitalization were getting translated slightly in a different way than direct translation using decoder.

My bad, apologies, and thanks a lot. :)
