### ISSUE TITLE
Core dumped on AWS Fargate

### ISSUE THREAD

**Issue by johko** [marian-nmt/marian-dev#787]
Hey,
I don't know if any of you guys have experience with AWS Fargate, but I'm just trying to run a marian-dev build within a container on it. When it starts it immediately gives me the error _Illegal instruction (core dumped)_ and shuts down

I suppose it has something to do with the CPU used by fargate and that there are some specific build settings needed. I tried to disable the AVX options in the build but that didn't turn out successful, it still has the same error.

So if anybody has a clue about that, I would be really thankful

**Comment by kpu** [comment]
Marian compiles with `-march=native` by default.  Choose a more conservative `-DBUILD_ARCH=somegccarchname`
