### ISSUE TITLE
Forcing Marian v1.10 SentencePiece to do random-sampling for training

### ISSUE THREAD

**Issue by GokulNC** [marian-nmt/marian-dev#804]
I see the following change in the [new Marian v1.10](https://github.com/marian-nmt/marian-dev/releases/tag/1.10.0):
> _Changed default value of --sentencepiece-max-lines from 10000000 to 2000000 since apparently the new version doesn't sample automatically anymore (Not quite clear how that affects quality of the vocabulary)._

Random sampling is essential in my case because my corpus is unshuffled and multilingual.
I tried passing the following flag to SentencePiece via Marian-NMT:
```
--sentencepiece-options '--input_sentence_size=1000000 --shuffle_input_sentence=true'
```

But it seems SP's `--sentencepiece-max-lines` argument by Marian would override the above, and hence no shuffling occurs.
Is there a way you can fix this?

Thanks!

**Comment by snukky** [comment]
I think you can always create a SentencePiece vocab outside Marian and then pass it via `--vocabs`. That will give most freedom. The following command shows what Marian is basically doing when creating .spm vocabs automatically:

    build/spm_train --bos_id=-1 --eos_id=0 --unk_id=1 --input=data.txt --model_prefix=vocab --vocab_size=32000
    mv vocab.model vocab.spm

**Comment by GokulNC** [comment]
Thanks, that is what I do currently. It would be better if you could mention in the documentation that Marian SentencePiece no more performs random sampling, but instead takes the top 2M sentences.

**Comment by emjotde** [comment]
But that's not actually true. Marian always does random sampling regardless what SentencePiece is doing internally. The temporary file which gets passed into SPM is created via reservoir sampling from both corpus files. SPM version and options are irrelevant here.

**Comment by GokulNC** [comment]
Thank you for the clarification, makes sense now.
