### ISSUE TITLE
Does `--right-left` flag mean only decoder is set to RtL mode?

### ISSUE THREAD

**Issue by GokulNC** [marian-nmt/marian-dev#805]
Assume my source side script is Left-to-Right (say English) and my target side script is Right-to-Left (say Arabic).
So should I use `--right-left` only for English to Arabic?
Or should I use it even for Arabic to English?

What if both sides are RtL? (like Arabic to Persian)

Can the encoder be treated direction-agnostic and assume that only the decoding direction matters?

Thanks! (and sorry for the basic question)

**Comment by emjotde** [comment]
Arabic or Persian are only displayed RtL, no? The actual tokens after splitting would appear LtR, if I am not wrong. That corresponds to the actual underlying byte order. So you would still produce text in correct order with normal decoding, it would just be displayed RtL.

I don't think we ever used the `--right-left` flag for anything other than rescoring. But it could be used for decoding, but it will always result in time-reverse order decoding. Encoders like the transformer can be thought of as bi-directional more or less.

**Comment by GokulNC** [comment]
Thanks a lot, makes sense now.

**Comment by GokulNC** [comment]
You can also close this related issue:
https://github.com/marian-nmt/marian/issues/355
