### ISSUE TITLE
Add sampling functionality

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#81]
First step towards MRT or reinforcemnt learning, sampling from a discrete distribution. This seems to have a nice solution: 

https://github.com/tensorflow/tensorflow/issues/456

**Comment by emjotde** [comment]
@tomekd I think we need an extension of` Nth_element` to make that work. Basically, we can sample from `X` (a tensor of probabilities) by doing `Nth_element(X + Y, n)`, where `Y` is uniform noise `Y ~ U(0,1)` (a matrix of the same size as `X`). However, in that case `Nth_element` will return `x+y` as the probability, while it would be nice to directly get `x` ignoring the noise factor `y`.

**Comment by tomekd** [comment]
Why not ``Nth_element(X + Y, n) - Y`` ? You can do it now.

**Comment by emjotde** [comment]
After some discussion, the better solution is to do the noise factor directly in the kernel:
`Nth_element(X, n, uniform_noise=true)` and it would return the `n` best indices according to `x+y` (y ~ U(0,1)), but the vector of costs would be composed of `x`.

**Comment by emjotde** [comment]
I think we can also simplify the operation by assuming constant beam/sample sizes for all input sentences in the batch across time steps. It should also be turned into a differentiable graph node. Differentiable in the sense that it would just select costs. The gradient would be the same selection from the gradient times the adjoint.
