### ISSUE TITLE
PR #799 reverted on newest master

### ISSUE THREAD

**Issue by rihardsk** [marian-nmt/marian-dev#820]
24e2e010 has reverted the simple-websocket-server submodule from https://github.com/marian-nmt/Simple-WebSocket-Server/commit/1d7e84aeb3f1ebdc78f6965d79ad3ca3003789fe to https://github.com/marian-nmt/Simple-WebSocket-Server/commit/257439f5bd0a15f315c1c2733ea8a4fb0e32c1db thereby reverting #799

**Comment by emjotde** [comment]
Merge error I assume.
@snukky.
