### ISSUE TITLE
[Enhancement] Loading a model currently loads the model 2Xnum_threads times

### ISSUE THREAD

**Issue by XapaJIaMnu** [marian-nmt/marian-dev#831]
### Bug description
Currently when loading a model for decoding in marian we load the full model twice per thread. 
Once in order to load the yaml which is stored inside the model: https://github.com/marian-nmt/marian-dev/blob/f74d055d204d7ed417f3dd26ad469192d70e8112/src/translator/scorers.cpp#L69

Which calls getItem: https://github.com/marian-nmt/marian-dev/blob/f74d055d204d7ed417f3dd26ad469192d70e8112/src/common/binary.cpp#L110
Which is basically loading the model into a vector and discarding it.

And another time in order to load the actual model: https://github.com/marian-nmt/marian-dev/blob/f74d055d204d7ed417f3dd26ad469192d70e8112/src/translator/scorers.cpp#L88

Ideally we want to load the model into a Vector once by calling https://github.com/marian-nmt/marian-dev/blob/f74d055d204d7ed417f3dd26ad469192d70e8112/src/common/binary.cpp#L30

And passing this vector down to the individual threads when they create their scorers, and also reuse it to get the yaml configuration.

**Comment by emjotde** [comment]
Thanks. As you have already spent so much time on that, can you submit a PR?

**Comment by kpu** [comment]
No.  @XapaJIaMnu is looking into the memory leak and I asked him to open an issue to document this separate issue.

**Comment by kpu** [comment]
If interested @graemenail may take this up.

**Comment by emjotde** [comment]
Does this actually have an impact for you? It frees the memory correctly, yes?

**Comment by emjotde** [comment]
Ah no, cause each thread has its own memory allocation. This is modelled after the GPU where living on each GPU, once per thread, makes sense. That might actually be easy to fix. Should we just make memory-mapping the default?

**Comment by XapaJIaMnu** [comment]
I think mmap() should be promoted to a command line option. Intgemm's architecture agnostic models don't like mmap (the architecture specific are fine). NPZs also can't be mmap'd.

The problem is that every memory allocation is painfully slow in certain VM scenarios.

**Comment by emjotde** [comment]
There's probably a hybrid solution there. Create a buffer on the fly once, reuse the mmapping interface to use that buffer instead of a mmapped file.

**Comment by emjotde** [comment]
That would actually work. One could use the hardware-specific conversion mechanisms to write to memory instead of writing to a file, keep the memory around and just use the pointer-based interface. That would solve all the issues @XapaJIaMnu mentioned?

**Comment by kpu** [comment]
This is more or less what kenlm does.  When loading an ARPA file, it just builds the binary format on the fly into RAM.

**Comment by graemenail** [comment]
I'm happy to take a look at this, @kpu.
