### ISSUE TITLE
Issue with Marian FBGEMM build for cascadelake CPU (AVX512)

### ISSUE THREAD

**Issue by GokulNC** [marian-nmt/marian-dev#835]
### Bug description
I am try to build Marian-NMT for my Intel CascadeLake CPU which supports AVX512.

```sh
$ grep avx512 /proc/cpuinfo
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities
```

But I face the following error during `make`:
```
[ 27%] Building CXX object src/3rd_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/QuantUtilsAvx2.cc.o
/tmp/ccAtxjvY.s: Assembler messages:                                                              
/tmp/ccAtxjvY.s:49401: Error: invalid use of register 
...
make[2]: *** [src/3rd_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/build.make:128: src/3rd_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/QuantUtilsAvx2.cc.o] Error 1                                      
make[1]: *** [CMakeFiles/Makefile2:1053: src/3rd_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/all] Error 2                                                                                               
make: *** [Makefile:152: all] Error 2
```

 But I do not face this error on my Broadwell CPU which has support only till AVX2.

### How to reproduce

Try on a Intel Cascade Lake CPU maybe? (not sure if the issue is because of this arch)
To check if this bug is because of original FBGEMM (and not because of Marian), I tried building the latest FBGEMM from the original repo. It got built perfectly without any errors.

I have installed the latest MKL libs: `intel-mkl-64bit-2020.0-088 libmkl libmkl-avx2 libmkl-avx512`

### Context
* Marian version: v1.10.6 77c3e356
* CMake command: `cmake .. -DUSE_SENTENCEPIECE=on -DCOMPILE_CPU=on -DCOMPILE_SERVER=on -DCOMPILE_CUDA=off -DBUILD_ARCH=cascadelake -DUSE_FBGEMM=on`
[cmake.log](https://github.com/marian-nmt/marian-dev/files/6157540/cmake.log)

* Log file: 
[make.log](https://github.com/marian-nmt/marian-dev/files/6157551/make.log)

I also see that the latest fb-gemm has many new optimizations (like [`QuantUtilsAvx512.cc`](https://github.com/pytorch/FBGEMM/blob/master/src/QuantUtilsAvx512.cc)) which is not yet supported in the Marian's fork as of 055d2a099

**Comment by kpu** [comment]
`gcc --version`
You need at least 8 to use VNNI properly.

**Comment by kpu** [comment]
Oh huh you have gcc 9 in the log.

**Comment by GokulNC** [comment]
Sure. Thanks, it works with gcc 7.

Please feel free to close the issue anytime :)

**Comment by snukky** [comment]
The fix is merged into master, so we may close this. Please reopen if the issue still exists.
