### ISSUE TITLE
marian-conv onnx-encode 

### ISSUE THREAD

**Issue by krean2** [marian-nmt/marian-dev#873]
### Bug description

I finished training a model and test the model successfully! 
But when I run "marian-conv --export-as onnx-encode", get **Segmentation fault (core dumped)**.

command : ./marian-conv -f /models/mixed.spm32k-spm32k.transformer.model1.npz.best-perplexity.npz \
-V models/mixed.spm32k-spm32k.vocab.yml models/mixed.spm32k-spm32k.vocab.yml \
-t /tmp/mixed.model.onnx --export-as onnx-encode 

### How to reproduce

1. git clone https://github.com/protocolbuffers/protobuf.git & build protobuf
2. git clone https://github.com/marian-nmt/marian.git
3. cd src/3rd_party/onnx/protobuf
    protoc -I=. --cpp_out=. onnx-ml.proto
4. vi src/onnx/expression_graph_onnx_exporter.cpp 
    #include "tensors/cpu/fbgemm/expression_graph_packable.h" -> #include "tensors/cpu/expression_graph_packable.h"
     (Is it a bug?? When I build marian  with cmake .. -DUSE_ONNX=ON, get No such file error 
      "tensors/cpu/fbgemm/expression_graph_packable.h")
5. cd build & cmake .. -DUSE_ONNX=ON & make -j4
6. ./marian-conv -f /models/mixed.spm32k-spm32k.transformer.model1.npz.best-perplexity.npz \
-V models/mixed.spm32k-spm32k.vocab.yml models/mixed.spm32k-spm32k.vocab.yml \
-t /tmp/mixed.model.onnx --export-as onnx-encode 

### Context
* Marian version: 1.10.0
* CMake command: cmake .. -DUSE_ONNX=ON
* Log file: Attach your training/decoding logs
[mixed.spm32k-spm32k.transformer.valid1.log](https://github.com/marian-nmt/marian-dev/files/7005633/mixed.spm32k-spm32k.transformer.valid1.log)
[mixed.spm32k-spm32k.transformer.train1.log](https://github.com/marian-nmt/marian-dev/files/7005634/mixed.spm32k-spm32k.transformer.train1.log)

Converting marian model to onnx model is available?

**Comment by GokulNC** [comment]
@krean2 Can you please share how you solved this issue?

**Comment by xyx361100238** [comment]
@krean2  Does this problem solved?
