### ISSUE TITLE
gAdd !same index seems incorrect

### ISSUE THREAD

**Issue by AngusL** [marian-nmt/marian-dev#97]
https://github.com/marian-nmt/marian-dev/blob/master/src/kernels/tensor_operators.h#L52

Assuming I've an accurate image in my head of the broadcast-to-full and reduce-to-out, I would expect e.g. ```dimsFull[0] = dims[0]*I + i;``` instead of ```dimsFull[0] = dims[0] + i;```. As-is, I would expect some parts of the input are unintentionally ignored, while others contribute more than they should:

![gadd](https://user-images.githubusercontent.com/1119676/29457455-1f4b66a0-8412-11e7-9f79-2c6bfce35929.png)

**Comment by emjotde** [comment]
Hm, depicted case should not be executed. `Out` should either have equal dimensions as `full` or the dimension that differs should be 1

**Comment by AngusL** [comment]
OK, I saw this was the case but didn't realise it was a hard restriction. This isn't a problem, then.

**Comment by emjotde** [comment]
Should throw an exception otherwise. The reason for this would be that otherwise it is unclear how to do the reduction. You have the same type of restriction for broadcasting. Unly dimensions of size 1 can be scaled up.
