### ISSUE TITLE
Incorrect translations for deep models if beam-size > 1

### ISSUE THREAD

**Issue by snukky** [marian-nmt/marian-dev#98]
s2s with deep models (`enc-cell-depth` > 1 and/or `dec-cell-base-depth` > 2) produces different translations than amun/nematus does if beam-size > 1 is used. Some sentences are identical, some are different. Probably, it's a bug in beam search as our rescorer returns the same scores as amun/nematus.

It affects all deep models regardless of `--type` s2/amun/nematus and layer normalization.

**Comment by emjotde** [comment]
Can you prepare a model for me with examples for nematus and marian?

**Comment by snukky** [comment]
On your machine: `/work/nmt/issue-98`

**Comment by snukky** [comment]
The differences between _nematus_ and _s2s_ in terms of BLEU:

| b | nematus (cuda) | s2s (gpu) |
|---|---|---|
| 1 | 32.11 | 32.78 |
| 2 | 32.45 | 33.16 | 
| 3 | 32.73 | 33.17 | 
| 5 | 33.14 | 33.11 |
| 8 | 33.19 | 33.03 | 
| 10 | 33.18 | 32.98 | 
| 12 | 32.83 | 32.37 |

**Comment by emjotde** [comment]
There is now a fix in `nematus-dynamic` that I am now adding to master. Can you check the current behaviour fo `nematus-dynamic`?

**Comment by emjotde** [comment]
@snukky I compared now with your Nematus examples and it seems to be identical for the files in the `issue98` folder. Commiting the fix to master, but keeping the branch separate so far.

**Comment by snukky** [comment]
The same model, after the fix:

| b | nematus | s2s | s2s-fixed |
|---|---|---|---|
| 1 | 32.11 | 32.78 | 32.78 |
| 2 | 32.45 | 33.16 |  33.17 |
| 3 | 32.73 | 33.17 |  33.23 |
| 5 | 33.14 | 33.11 | 33.37 |
| 8 | 33.19 | 33.03 | 33.31 |
| 10 | 33.18 | 32.98 | 33.37 |
| 12 | 32.83 | 32.37 |  33.39 |

**Comment by emjotde** [comment]
This are quite large differences. @rsennrich Could there be a bug in nematus?

**Comment by rsennrich** [comment]
BLEU isn't the right metric to check if there's a bug in beam search. Can you please check which decoder finds the hypotheses with the better model score (and also check that the model score for the same output is the same)?

**Comment by emjotde** [comment]
OK, we are looking at a couple of more models now.

**Comment by emjotde** [comment]
@snukky for the model without layer-normalization I am getting identical results for Nematus and S2S, so that's good. Does the model you are using use LN? Can you copy it to fatboy and add a test set?

**Comment by snukky** [comment]
This has been solved also for Nematus models using LN.
